// <auto-generated>
//   Generated from AsyncDelegatingTreenumerable.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using System;

namespace Copse.Treenumerables
{
  // Async analog of Copse.Treenumerables.DelegatingTreenumerable: a composite async tree whose two
  // dimension cursors come from injected factories. This is what AsyncTree.Defer returns -- the
  // factory indirection is where "fresh tree per acquisition" lives.
  //
  // (The narrow single-dimension siblings -- AsyncDelegatingDepthFirst/BreadthFirstTreenumerable --
  // and AsyncTree.Defer/UsingDepthFirst wait for the async flat-stream layer that motivates them: a
  // forward-only async serialized stream is the only source that affords just one async dimension.)
  public sealed class DelegatingTreenumerable<TNode> : ITreenumerable<TNode>
  {
    public DelegatingTreenumerable(
      Func<ITreenumerator<TNode>> breadthFirstTreenumeratorFactory,
      Func<ITreenumerator<TNode>> depthFirstTreenumeratorFactory)
    {
      _BreadthFirstTreenumeratorFactory = breadthFirstTreenumeratorFactory;
      _DepthFirstTreenumeratorFactory = depthFirstTreenumeratorFactory;
    }

    private readonly Func<ITreenumerator<TNode>> _BreadthFirstTreenumeratorFactory;
    private readonly Func<ITreenumerator<TNode>> _DepthFirstTreenumeratorFactory;

    public ITreenumerator<TNode> GetBreadthFirstTreenumerator() => _BreadthFirstTreenumeratorFactory();

    public ITreenumerator<TNode> GetDepthFirstTreenumerator() => _DepthFirstTreenumeratorFactory();
  }
}
