// <auto-generated>
//   Generated from AsyncPreorderStreamTreenumerable.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Stores;
using Copse.Treenumerators;
using Copse.Core;
using System;

namespace Copse.Treenumerables
{
  /// <summary>
  /// An async tree streaming from a forward-only preorder source: the async analog of
  /// <c>Copse.Treenumerables.PreorderStreamTreenumerable</c>, and deliberately only an
  /// <see cref="IAsyncDepthFirstTreenumerable{TValue}"/> -- a one-pass source cannot affordably serve
  /// the breadth-first dimension. Each acquisition invokes the factory for a fresh stream and OWNS it
  /// (async disposal closes it); re-enumeration re-reads the source.
  /// </summary>
  public sealed class PreorderStreamTreenumerable<TValue, TStream> : IDepthFirstTreenumerable<TValue>
    where TStream : IPreorderStream<TValue>
  {
    public PreorderStreamTreenumerable(Func<TStream> streamFactory)
    {
      _StreamFactory = streamFactory;
    }

    private readonly Func<TStream> _StreamFactory;

    public ITreenumerator<TValue> GetDepthFirstTreenumerator()
      => new PreorderStreamDepthFirstTreenumerator<TValue, TStream>(_StreamFactory());
  }
}
