// <auto-generated>
//   Generated from AsyncTreenumerable.GetHandlesWithValues.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using System.Collections.Generic;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>
    /// The acquisition scan: every handle paired with the value it labels, in the same
    /// deliberately unspecified order as <see cref="GetHandles{TValue, THandle}"/>. The rows
    /// let value predicates pick out handles -- consumer-side, preserving the
    /// no-node-equality pledge (the library compares nothing; the consumer's predicate is the
    /// consumer's business). The search law's one earned exception: without the pairing, a
    /// value predicate mid-chain cannot reach the receiver's probe without naming it twice.
    /// </summary>
    public static IEnumerable<HandleAndValue<THandle, TValue>> GetHandlesWithValues<TValue, THandle>(
      this IWalkableTreenumerable<TValue, THandle> source)
    {
      foreach (var handle in source.GetHandles())
      {
        var value = source.GetValue(handle);

        yield return new HandleAndValue<THandle, TValue>(handle, value);
      }
    }
  }
}
