// <auto-generated>
//   Generated from AsyncTreenumerable.Extend.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Linq.Treenumerables;
using System;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>
    /// The comonad's co-bind (docs/CATEGORY_THEORY_SURVEY.md §6): relabel every node by an
    /// arbitrary OBSERVATION of its focus. The observer receives the walkable and the handle,
    /// so it can consult anything reachable from that vantage -- depth, ancestor values,
    /// subtree facts -- which is exactly what streaming <c>Select</c> cannot see. The shape
    /// and the handles are untouched (extend relabels, never reshapes); the result is a
    /// walkable whose streaming half is the Walk adapter driving the source's adjacency under
    /// the observer's labeling. The scans are this operation restricted to observations that
    /// factor through a fold along the traversal order -- pinned by the scan-coherence laws
    /// in the walker comonad suites.
    ///
    /// <para>Laws (the Store comonad's, pinned): extend of extract is the identity; extract
    /// after extend recovers the observer; and extend co-associates.</para>
    /// </summary>
    public static IWalkableTreenumerable<TResult, THandle> Extend<TValue, THandle, TResult>(
      this ITreeTopology<TValue, THandle> source,
      Func<ITreeTopology<TValue, THandle>, THandle, TResult> observer)
      => new ExtendWalkable<TValue, THandle, TResult>(source, observer);
  }
}
