// <auto-generated>
//   Generated from AsyncTreenumerable.SpanningSubtree.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse;
using System.Collections.Generic;
using System.Linq;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>
    /// The capstone, distilled (UC-32): the minimum spanning subtree of the target nodes --
    /// every node on a path between targets, re-rooted at their lowest common ancestor --
    /// returned as a WALKER standing at the spanning root. Result-typed because the
    /// operation is partial exactly twice, and each miss is a fact: NO TARGETS (the
    /// spanning subtree of nothing is nothing -- guarded here, where the semantics live,
    /// not inside a seedless fold's vocabulary-free exception) and DISJOINT TREES (targets
    /// in different trees of a forest have no common ancestor). One target is not a miss:
    /// its spanning subtree is the node alone.
    ///
    /// <para>The result stands on a NEW capture of the spanning subtree (preorder,
    /// O(kept)): its handles are that capture's own ordinals, NOT the source's -- the
    /// per-capture clause. The construction composes shipped pieces end to end:
    /// walker-climbed LCA folding (stances in, stance out; the kept-set falls out of the
    /// same climbs), the severed re-root, the HANDLE-DECORATED STREAM for the membership
    /// clamp (Extend stamps every node with its own (handle, value) pair, PruneBefore cuts
    /// off-path subtrees in handle-space -- membership is downward-closed, so prune
    /// semantics are exactly right -- and Select projects back), and one Materialize. A
    /// future membership LENS makes the clamp adjacency-side and this zero-copy; the
    /// semantics are fixed here. Target handles are presumed to be the source's own (the
    /// foreign-handle clause).</para>
    /// </summary>
    public static Option<TreeWalker<TValue, int>> SpanningSubtree<TValue, THandle>(
      this IWalkableTreenumerable<TValue, THandle> source,
      IEnumerable<THandle> targets)
    {
      // Stage C: one knock at the door, then the jump lifts every stored handle into a
      // stance (a valid target implies a nonempty forest, the trust door's usual bargain).
      var targetList = targets.ToList();

      if (targetList.Count == 0)
        return default;

      var door = source.TryGetTreeWalker();
      var targetWalkers = targetList.Select(handle => door.Value.At(handle)).ToList();

      var spanningRootResult = new Option<TreeWalker<TValue, THandle>>(targetWalkers[0]);

      for (var index = 1; index < targetWalkers.Count; index++)
      {
        spanningRootResult = LowestCommonAncestor(spanningRootResult.Value, targetWalkers[index]);

        if (!spanningRootResult.HasValue)
          return default;
      }

      var spanningRoot = spanningRootResult.Value;

      // The kept-set: every node on a target-to-root path, recorded by the climbs. Each
      // climb stops at the first already-kept ancestor (shared path segments are walked
      // once), and cannot walk past a root: the spanning root is a proven ancestor of
      // every target, and it is seeded first.
      var keptHandles = new HashSet<THandle> { spanningRoot.Focus };

      foreach (var target in targetWalkers)
      {
        var stance = target;

        while (!keptHandles.Contains(stance.Focus))
        {
          keptHandles.Add(stance.Focus);
          stance = (stance.MoveToParent()).Value;
        }
      }

      var clamped = spanningRoot.Subtree()
        .Extend((topology, handle) => PairHandleWithValue(topology, handle))
        .PruneBefore(pair => !keptHandles.Contains(pair.Handle))
        .Select(pair => pair.Value);

      return clamped.Materialize(BufferLayout.Preorder).TryGetTreeWalkerAtRootIndex();
    }

    // The handle-decorated stream's stamp, as a named observer so both colors read the same:
    // every node paired with its own handle, the membership clamp's coordinate system.
    private static HandleAndValue<THandle, TValue> PairHandleWithValue<TValue, THandle>(
      ITreeTopology<TValue, THandle> topology,
      THandle handle)
      => new HandleAndValue<THandle, TValue>(handle, topology.GetValue(handle));

    // The binary LCA, walker-first and result-typed (the axis wave will promote this to a
    // public extension; the spanning fold is its first consumer): collect one stance's
    // root path into a handle set, climb the other until the first membership hit. The
    // miss -- disjoint trees -- is a fact, never a default walker. Same-topology is
    // presumed (the walkers' topology is private even to this assembly; the check becomes
    // possible when the axis wave lands in the walker's own assembly).
    private static Option<TreeWalker<TValue, THandle>> LowestCommonAncestor<TValue, THandle>(
      TreeWalker<TValue, THandle> first,
      TreeWalker<TValue, THandle> second)
    {
      var firstRootPath = new HashSet<THandle>();
      var stance = first;

      while (true)
      {
        firstRootPath.Add(stance.Focus);

        var parent = stance.MoveToParent();

        if (!parent.HasValue)
          break;

        stance = parent.Value;
      }

      var candidate = second;

      while (!firstRootPath.Contains(candidate.Focus))
      {
        var parent = candidate.MoveToParent();

        if (!parent.HasValue)
          return default;

        candidate = parent.Value;
      }

      return new Option<TreeWalker<TValue, THandle>>(candidate);
    }
  }
}
