// <auto-generated>
//   Generated from AsyncTreenumerable.GetTreeWalkerAt.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>
    /// Enter the comonadic view: a walker standing at <paramref name="handle"/>. Walker
    /// acquisition named like treenumerator acquisition (the <c>GetEnumerator</c> sense of
    /// Get: this door MINTS its object) -- and bare Get by the Try law: choosing a focus is
    /// trust-based, so there is no typed miss here. Handles come from recording positions
    /// while consuming (<see cref="GetHandles{TNode, THandle}"/>) or from the root door
    /// (<see cref="TryGetTreeWalkerAtRootIndex{TNode, THandle}"/>), never from value
    /// search. The handle is presumed to be one this walkable issued (the foreign-handle
    /// clause). Pure construction: no probe fires here; a forged handle stays loud on the
    /// exception channel at the first probe through the walker.
    /// </summary>
    public static TreeWalker<TNode, THandle> GetTreeWalkerAt<TNode, THandle>(
      this IWalkableTreenumerable<TNode, THandle> source,
      THandle handle)
      // Re-entry goes door-then-jump -- one knock, then the trusted address.
      => (source.GetTreeWalker()).At(handle);
  }
}
