// <auto-generated>
//   Generated from AsyncTreenumerable.PruneDescendantsWhere.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Linq.Treenumerables;
using System;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>
    /// The restriction lens: <c>PruneDescendantsWhere</c> over a WALKABLE stays walkable. Same semantics
    /// and predicate flavor as the streaming overload (keeps each matching node, sheds its
    /// subtree), resolved STATICALLY by the receiver's type -- no probes, the dimension-split
    /// discipline. Lives in THIS class by the overload-unity rule: same-name cross-tier
    /// overloads share one static class, so betterness picks the specific receiver from ONE
    /// candidate set -- a class move would SILENTLY fall back to the streaming overload (it
    /// compiles; the lens's pair-citizenship just vanishes), and same-class placement makes
    /// that hazard structurally impossible. A pair citizen: the order half IS the streaming
    /// operator applied to the source (the composition lattice inside it keeps working -- a
    /// stacked lens's stream half is prune-over-prune, which the light tier merges in-tier as
    /// always); the adjacency half wraps one probe. O(1) per probe. (The positional flavor is
    /// deliberately absent: depth is not stored on a walker, so a positional predicate would
    /// price an O(depth) climb per probe -- it arrives when a caller needs it, with that cost
    /// documented.)
    /// </summary>
    public static IWalkableTreenumerable<TNode, THandle> PruneDescendantsWhere<TNode, THandle>(
      this IWalkableTreenumerable<TNode, THandle> source,
      Func<TNode, bool> predicate)
    {
      if (predicate == null)
        return source;

      return new PruneDescendantsWhereWalkable<TNode, THandle>(source, predicate);
    }
  }
}
