// <auto-generated>
//   Generated from AsyncPruneAfterTreenumerator.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Linq.Extensions;
using System;

namespace Copse.Linq.Treenumerators
{
  /// <summary>
  /// <b>async</b> <c>PruneAfter</c> and the codegen source of truth for its sync twin: strip the
  /// <c>await</c> and it becomes the synchronous driver. Forwards the inner visit stream unchanged
  /// except that a scheduled node matching the predicate keeps its own visit but sheds its subtree
  /// (<see cref="NodeTraversalStrategies.SkipDescendants"/> is added to the pull). Dimension-agnostic.
  /// </summary>
  internal sealed class PruneAfterTreenumerator<TNode>
    : TreenumeratorWrapper<TNode>
  {
    public PruneAfterTreenumerator(
      Func<ITreenumerator<TNode>> innerTreenumeratorFactory,
      Func<NodeContext<TNode>, bool> predicate)
      : base(innerTreenumeratorFactory)
    {
      _Predicate = predicate;
    }

    private readonly Func<NodeContext<TNode>, bool> _Predicate;

    protected override bool OnMoveNext(NodeTraversalStrategies nodeTraversalStrategies)
    {
      if (EnumerationFinished)
        return false;

      // Never test the pre-enumeration sentinel (ForestRoot convention: default node, mode
      // SchedulingNode): user lambdas see real nodes only.
      if (Mode == TreenumeratorMode.SchedulingNode && !Position.IsForestRoot && _Predicate(this.ToNodeContext()))
        nodeTraversalStrategies |= NodeTraversalStrategies.SkipDescendants;

      var result = InnerTreenumerator.MoveNext(nodeTraversalStrategies);

      UpdateState();

      return result;
    }

    private void UpdateState()
    {
      Mode = InnerTreenumerator.Mode;

      if (!EnumerationFinished)
      {
        Node = InnerTreenumerator.Node;
        VisitCount = InnerTreenumerator.VisitCount;
        Position = InnerTreenumerator.Position;
      }
    }
  }
}
