// <auto-generated>
//   Generated from AsyncFuncResultSelector.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using System;

namespace Copse.Linq.Treenumerables
{
  // The closure LEAF of the selector algebra: wraps ONE user-delegate result selector so it
  // can ride the struct forms (a closure-bound piece enters the splice through this leaf,
  // and chains then nest via ComposedResultSelector). A user delegate inherently costs a
  // delegate call, so this leaf keeps it -- the struct seam exists so the PLAIN operators
  // don't pay it.
  internal readonly struct FuncResultSelector<TSource, TResult> : IResultSelector<TSource, TResult>
  {
    public FuncResultSelector(Func<NodeAndPosition<TSource>, SelectWhereResult<TResult>> resultSelector)
    {
      _ResultSelector = resultSelector;
    }

    private readonly Func<NodeAndPosition<TSource>, SelectWhereResult<TResult>> _ResultSelector;

    public SelectWhereResult<TResult> GetResult(NodeAndPosition<TSource> nodeAndPosition) => _ResultSelector(nodeAndPosition);
  }
}
