// <auto-generated>
//   Generated from AsyncPositionalPruneSiblingsWhereResultSelector.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using System;

namespace Copse.Linq.Treenumerables
{
  // The positional PruneSiblingsWhere's result: the predicate sees (node, this layer's input
  // labels). Like the value form, the leg never relabels -- the matched node stays and only
  // its later siblings go.
  internal readonly struct PositionalPruneSiblingsWhereResultSelector<TNode> : IResultSelector<TNode, TNode>
  {
    public PositionalPruneSiblingsWhereResultSelector(Func<TNode, NodePosition, bool> predicate)
    {
      _Predicate = predicate;
    }

    private readonly Func<TNode, NodePosition, bool> _Predicate;

    public SelectWhereResult<TNode> GetResult(NodeAndPosition<TNode> nodeAndPosition)
      => new SelectWhereResult<TNode>(
        nodeAndPosition.Node,
        _Predicate(nodeAndPosition.Node, nodeAndPosition.Position)
          ? NodeTraversalStrategies.PruneSiblings
          : NodeTraversalStrategies.TraverseAll);
  }
}
