using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Copse.CodeGen
{
  /// <summary>
  /// The async-&gt;sync transcription (the Npgsql pattern): mechanically rewrite a direct-style async
  /// treenumerator into its synchronous twin. Public + pure (string in, string out) so both the regen
  /// tool and the drift-guard test drive the exact same transform.
  ///
  /// <para>Strips async/await/ConfigureAwait, drops async-only usings, rehomes the namespace to a
  /// sibling <c>.Generated</c>, and renames identifiers: explicit class/type renames plus a generic
  /// "strip the Async suffix from method names" rule. Trivia is preserved so the output stays close to
  /// the source. Known limitation: a sync method legitimately named <c>*Async</c> would be wrongly
  /// stripped, and cancellation plumbing is not yet elided (async-only, deferred).</para>
  /// </summary>
  public static class AsyncToSync
  {
    public static string Transform(string source, string sourceFileName)
    {
      var root = (CompilationUnitSyntax)CSharpSyntaxTree.ParseText(source).GetRoot();
      var rewritten = (CompilationUnitSyntax)new Rewriter().Visit(root);

      // Two type-name fixups that aren't identifier renames (they change to keywords): return types.
      var text = rewritten.ToFullString()
        .Replace("ValueTask<bool>", "bool")
        .Replace("ValueTask", "void");

      var header =
        "// <auto-generated>\n" +
        "//   Generated from " + sourceFileName + " by Copse.CodeGen (async->sync transcription).\n" +
        "//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen\n" +
        "// </auto-generated>\n";

      return header + text;
    }

    private sealed class Rewriter : CSharpSyntaxRewriter
    {
      // Explicit whole-token renames: the class names (Async prefix -> Generated prefix) and the type
      // names that are NOT a simple "Async" suffix strip. Method names ending in "Async" are stripped
      // generically in VisitToken, so they never need listing here -- that is what lets the tool
      // transcribe a new treenumerator without being taught its method names.
      private static readonly Dictionary<string, string> Renames = new()
      {
        ["AsyncDepthFirstTreenumerator"] = "GeneratedDepthFirstTreenumerator",
        ["AsyncBreadthFirstTreenumerator"] = "GeneratedBreadthFirstTreenumerator",
        ["AsyncWhereDepthFirstTreenumerator"] = "GeneratedWhereDepthFirstTreenumerator",
        ["AsyncWhereBreadthFirstTreenumerator"] = "GeneratedWhereBreadthFirstTreenumerator",
        ["IAsyncTreenumerator"] = "ITreenumerator",
        ["IAsyncChildEnumerator"] = "IForwardChildEnumerator",
        ["IAsyncEnumerable"] = "IEnumerable",
        ["IAsyncEnumerator"] = "IEnumerator",
        ["TAsyncChildEnumerator"] = "TChildEnumerator",
        ["GetAsyncEnumerator"] = "GetEnumerator",
      };

      // Usings that only make sense in the async source.
      private static readonly HashSet<string> DroppedUsings = new()
      {
        "Copse.Core.Async",
        "System.Threading.Tasks",
      };

      public override SyntaxNode VisitUsingDirective(UsingDirectiveSyntax node)
        => DroppedUsings.Contains(node.Name?.ToString()) ? null : base.VisitUsingDirective(node);

      public override SyntaxNode VisitNamespaceDeclaration(NamespaceDeclarationSyntax node)
      {
        // Capture the name BEFORE visiting children (the generic suffix strip below leaves the bare
        // "Async" segment alone, but reading the original name keeps this robust). Rehome the async
        // namespace to a sibling ".Generated" (Copse.Async -> Copse.Generated, Copse.Linq.Async ->
        // Copse.Linq.Generated).
        var originalNs = node.Name.ToString();
        node = (NamespaceDeclarationSyntax)base.VisitNamespaceDeclaration(node);
        if (originalNs.EndsWith(".Async"))
        {
          var generated = originalNs.Substring(0, originalNs.Length - ".Async".Length) + ".Generated";
          node = node.WithName(SyntaxFactory.ParseName(generated).WithTriviaFrom(node.Name));
        }
        return node;
      }

      // Strip `await X` -> `X`.
      public override SyntaxNode VisitAwaitExpression(AwaitExpressionSyntax node)
        => ((ExpressionSyntax)Visit(node.Expression)).WithTriviaFrom(node);

      // Strip `X.ConfigureAwait(false)` -> `X`.
      public override SyntaxNode VisitInvocationExpression(InvocationExpressionSyntax node)
      {
        if (node.Expression is MemberAccessExpressionSyntax ma && ma.Name.Identifier.ValueText == "ConfigureAwait")
          return ((ExpressionSyntax)Visit(ma.Expression)).WithTriviaFrom(node);
        return base.VisitInvocationExpression(node);
      }

      // Drop the `async` modifier.
      public override SyntaxNode VisitMethodDeclaration(MethodDeclarationSyntax node)
      {
        node = (MethodDeclarationSyntax)base.VisitMethodDeclaration(node);
        if (node.Modifiers.Any(SyntaxKind.AsyncKeyword))
          node = node.WithModifiers(
            SyntaxFactory.TokenList(node.Modifiers.Where(m => !m.IsKind(SyntaxKind.AsyncKeyword))));
        return node;
      }

      // Rename identifier tokens, preserving trivia.
      public override SyntaxToken VisitToken(SyntaxToken token)
      {
        token = base.VisitToken(token);
        if (!token.IsKind(SyntaxKind.IdentifierToken))
          return token;

        // Explicit type/class renames win first (they don't end in "Async", so the strip wouldn't
        // catch them anyway).
        if (Renames.TryGetValue(token.ValueText, out var renamed))
          return SyntaxFactory.Identifier(token.LeadingTrivia, renamed, token.TrailingTrivia);

        // Generic: strip the "Async" suffix from method identifiers (MoveNextAsync -> MoveNext, and
        // every seam method). Guarded to length > 5 so the bare "Async" namespace segment is intact.
        var text = token.ValueText;
        if (text.Length > 5 && text.EndsWith("Async", StringComparison.Ordinal))
          return SyntaxFactory.Identifier(token.LeadingTrivia, text.Substring(0, text.Length - 5), token.TrailingTrivia);

        return token;
      }
    }
  }
}
