using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Copse.CodeGen
{
  /// <summary>
  /// The async-&gt;sync transcription (the Npgsql pattern): mechanically rewrite a direct-style async
  /// treenumerator into its synchronous twin. Public + pure (string in, string out) so both the regen
  /// tool and the drift-guard test drive the exact same transform.
  ///
  /// <para>Strips async/await/ConfigureAwait, drops async-only usings, rehomes the namespace, renames
  /// the class (per-entry, so a twin can take a canonical name), and renames the async identifiers to
  /// their sync counterparts -- explicit type renames plus a generic "strip the Async suffix from
  /// method names" rule, and elides cancellation plumbing wholesale (CancellationToken
  /// parameters/fields, ThrowIfCancellationRequested guards, forwarded arguments -- see the
  /// elision block for the naming convention it relies on). Trivia is preserved. Known
  /// limitation: a sync method legitimately named <c>*Async</c> would be wrongly stripped.</para>
  /// </summary>
  public static class AsyncToSync
  {
    public static string Transform(GeneratorEntry entry, string source)
    {
      var root = (CompilationUnitSyntax)CSharpSyntaxTree.ParseText(source).GetRoot();
      var rewritten = (CompilationUnitSyntax)new Rewriter(entry.AsyncClass, entry.SyncClass, entry.SyncNamespace).Visit(root);

      // Return-type fixups that aren't identifier renames (they change to keywords). Unwrap
      // ValueTask<X> -> X (one level of nested generics -- covers ValueTask<PreorderRead<T>>), then
      // the bare ValueTask -> void. Async seams only surface as awaited expressions, so a literal
      // ValueTask<X> here is always a method return type that collapses to its synchronous result.
      var text = rewritten.ToFullString();
      // Func<ValueTask> (an awaited action-shaped thunk, e.g. a dispose action) collapses to
      // Action, not the illegal Func<void> the generic replaces below would produce. Exact-match
      // replace: Func<ValueTask<X>> does not contain this substring, so it stays with the regex.
      text = text.Replace("Func<ValueTask>", "Action");
      text = System.Text.RegularExpressions.Regex.Replace(text, @"ValueTask<((?:[^<>]|<[^<>]*>)*)>", "$1");
      text = text.Replace("ValueTask", "void");
      text = ApplyMarkerRegions(text);

      var header =
        "// <auto-generated>\n" +
        "//   Generated from " + System.IO.Path.GetFileName(entry.AsyncSource) + " by Copse.CodeGen (async->sync transcription).\n" +
        "//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen\n" +
        "// </auto-generated>\n";

      // Emit CRLF regardless of the async source's line endings (.editorconfig: end_of_line = crlf).
      return (header + text).Replace("\r\n", "\n").Replace("\n", "\r\n");
    }

    // The marker-region pair -- the escape hatch for the few places the two colors need
    // genuinely different text.
    //
    // SYNC-ONLY (injection): some sync members have NO async counterpart (the non-generic
    // IEnumerator IEnumerable.GetEnumerator(), object IEnumerator.Current, IEnumerator.Reset()).
    // The async source carries them commented out between marker lines:
    //
    //   // codegen: begin sync-only
    //   // IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
    //   // codegen: end sync-only
    //
    // so they do not compile in the async project; this post-pass drops the marker lines and
    // strips one leading "// " from each line in between, activating the members in the sync
    // twin. The region's content is written directly in SYNC form (it is comment trivia, so the
    // identifier renames above never touch it).
    //
    // ASYNC-ONLY (excision): some async members/lines have no place in the twin (an overload
    // whose transcription would collide, a dual-dispatch branch that is vestigial in sync).
    // They are REAL code between marker lines:
    //
    //   // codegen: begin async-only
    //   () => DisposeResourceAsync(resource));
    //   // codegen: end async-only
    //
    // and this post-pass deletes the region (markers included) from the twin. An async-only
    // region immediately followed by a sync-only region is the SUBSTITUTION idiom: the twin gets
    // the sync-only text where the async source had the async-only text.
    private static string ApplyMarkerRegions(string text)
    {
      if (!text.Contains("codegen: begin"))
        return text;

      var lines = text.Split('\n');
      var result = new List<string>(lines.Length);
      var inSyncOnlyRegion = false;
      var inAsyncOnlyRegion = false;

      foreach (var line in lines)
      {
        var trimmed = line.TrimStart();

        if (trimmed.StartsWith("// codegen: begin sync-only", StringComparison.Ordinal))
        {
          inSyncOnlyRegion = true;
          continue;
        }

        if (trimmed.StartsWith("// codegen: end sync-only", StringComparison.Ordinal))
        {
          inSyncOnlyRegion = false;
          continue;
        }

        if (trimmed.StartsWith("// codegen: begin async-only", StringComparison.Ordinal))
        {
          inAsyncOnlyRegion = true;
          continue;
        }

        if (trimmed.StartsWith("// codegen: end async-only", StringComparison.Ordinal))
        {
          inAsyncOnlyRegion = false;
          continue;
        }

        if (inAsyncOnlyRegion)
          continue;

        if (inSyncOnlyRegion)
        {
          var indent = line.Substring(0, line.Length - trimmed.Length);
          if (trimmed.StartsWith("// ", StringComparison.Ordinal))
            result.Add(indent + trimmed.Substring(3));
          else if (trimmed.TrimEnd() == "//")
            result.Add(indent.TrimEnd());
          else
            result.Add(line); // blank line inside the region
          continue;
        }

        result.Add(line);
      }

      return string.Join("\n", result);
    }

    private sealed class Rewriter : CSharpSyntaxRewriter
    {
      // Type renames that are NOT a simple "Async" suffix strip. The CLASS rename is per-entry (below);
      // method names ending in "Async" are stripped generically in VisitToken, so they never need
      // listing here -- that is what lets the tool transcribe a new treenumerator untaught.
      private static readonly Dictionary<string, string> Renames = new()
      {
        ["IAsyncTreenumerator"] = "ITreenumerator",
        ["AsyncTreenumeratorBase"] = "TreenumeratorBase",
        ["AsyncTreenumeratorWrapper"] = "TreenumeratorWrapper",
        ["IAsyncDisposable"] = "IDisposable",
        ["IAsyncChildEnumerator"] = "IChildEnumerator",
        ["IAsyncPreorderStream"] = "IPreorderStream",
        ["IAsyncLevelOrderStream"] = "ILevelOrderStream",
        ["IAsyncPreorderStore"] = "IPreorderStore",
        ["IAsyncLevelOrderStore"] = "ILevelOrderStore",
        ["IAsyncTreenumerable"] = "ITreenumerable",
        ["IAsyncDepthFirstTreenumerable"] = "IDepthFirstTreenumerable",
        ["IAsyncBreadthFirstTreenumerable"] = "IBreadthFirstTreenumerable",
        ["GetAsyncDepthFirstTreenumerator"] = "GetDepthFirstTreenumerator",
        ["GetAsyncBreadthFirstTreenumerator"] = "GetBreadthFirstTreenumerator",
        ["AsyncValueTokenStreamScanner"] = "ValueTokenStreamScanner",
        ["IAsyncEnumerable"] = "IEnumerable",
        ["IAsyncEnumerator"] = "IEnumerator",
        ["TAsyncChildEnumerator"] = "TChildEnumerator",
        ["GetAsyncEnumerator"] = "GetEnumerator",
        ["IAsyncTreenumerableBuffer"] = "ITreenumerableBuffer",
        ["IAsyncMemoizeTreenumerableBuffer"] = "IMemoizeTreenumerableBuffer",
        ["AsyncRefCountDisposable"] = "RefCountDisposable",
        ["AsyncDisposable"] = "Disposable",
        ["GetAsyncTreenumerator"] = "GetTreenumerator",
        ["IAsyncFusableTreenumerable"] = "IFusableTreenumerable",
      };

      private static readonly HashSet<string> DroppedUsings = new()
      {
        "Copse.Async",
        "System.Threading.Tasks",
        // Only ever imported for CancellationToken (the GetAsyncEnumerator parameter, which the
        // transcription removes -- see VisitMethodDeclaration). No manifest source uses any other
        // System.Threading type; if one ever needs Interlocked/Volatile in its sync twin, this
        // entry has to become smarter.
        "System.Threading",
      };

      // Async-only namespaces that MAP to a sync namespace rather than drop: a source that imports
      // only the async contract (e.g. a treenumerable over IAsyncTreenumerable) still needs the
      // sync contract's namespace after transcription. A source that imports BOTH (the engine
      // treenumerators) maps the async one onto its existing sync one; the duplicate is deduped in
      // VisitCompilationUnit, keeping the original's position -- so those outputs are unchanged.
      private static readonly Dictionary<string, string> MappedUsings = new()
      {
        ["Copse.Core.Async"] = "Copse.Core",
        ["Copse.Async.Treenumerators"] = "Copse.Treenumerators",
        ["Copse.Async.Treenumerables"] = "Copse.Treenumerables",
        ["Copse.Async.Stores"] = "Copse.Stores",
        ["Copse.Linq.Async"] = "Copse.Linq.Treenumerators",
        ["Copse.Linq.Async.Treenumerators"] = "Copse.Linq.Treenumerators",
        ["Copse.Linq.Async.Treenumerables"] = "Copse.Linq.Treenumerables",
        ["Copse.Linq.Async.Stores"] = "Copse.Linq.Stores",
      };

      private readonly string _asyncClass;
      private readonly string _syncClass;
      private readonly string _syncNamespace;

      public Rewriter(string asyncClass, string syncClass, string syncNamespace)
      {
        _asyncClass = asyncClass;
        _syncClass = syncClass;
        _syncNamespace = syncNamespace;
      }

      // A sync-completing wrap -- new ValueTask<X>(expr) in a non-async ValueTask-returning
      // method -- collapses to its payload expression in the sync twin. (The text-level
      // ValueTask<X> fixup only rewrites the TYPE, which would otherwise leave `new X(expr)`.)
      public override SyntaxNode VisitObjectCreationExpression(ObjectCreationExpressionSyntax node)
      {
        if (node.Type is GenericNameSyntax generic
          && generic.Identifier.Text == "ValueTask"
          && node.ArgumentList?.Arguments.Count == 1)
        {
          var argument = (ExpressionSyntax)Visit(node.ArgumentList.Arguments[0].Expression);
          return argument.WithTriviaFrom(node);
        }

        return base.VisitObjectCreationExpression(node);
      }

      // ----- The ValueTask fast-path idiom (the async seam eliminator). A hot method stays
      // NON-async by probing a grow call's ValueTask and deferring to an async continuation only
      // when it is genuinely pending:
      //
      //   var closed = _Store.EnsureSubtreeClosedAsync(index);
      //
      //   if (!closed.IsCompletedSuccessfully)
      //     return AwaitThenTryPushNextChildAsync(closed);
      //
      //   var candidate = index + closed.Result;
      //
      // The sync twin can never be pending, so the guard statement VANISHES and `closed.Result`
      // collapses to `closed` -- leaving exactly the hand-written sync shape (the continuation
      // methods live in async-only marker regions). The member names are RESERVED by these two
      // rules: `.IsCompletedSuccessfully` and `.Result` in a manifest source always mean this
      // idiom -- neither appears anywhere else, and a future non-idiom use would transcribe
      // wrongly rather than fail loudly.

      public override SyntaxNode VisitIfStatement(IfStatementSyntax node)
      {
        if (node.Else == null
          && node.Condition is PrefixUnaryExpressionSyntax negation
          && negation.IsKind(SyntaxKind.LogicalNotExpression)
          && negation.Operand is MemberAccessExpressionSyntax probe
          && probe.Name.Identifier.ValueText == "IsCompletedSuccessfully")
          return null;

        return base.VisitIfStatement(node);
      }

      public override SyntaxNode VisitMemberAccessExpression(MemberAccessExpressionSyntax node)
      {
        if (node.Name.Identifier.ValueText == "Result")
          return ((ExpressionSyntax)Visit(node.Expression)).WithTriviaFrom(node);

        return base.VisitMemberAccessExpression(node);
      }

      public override SyntaxNode VisitUsingDirective(UsingDirectiveSyntax node)
      {
        var name = node.Name?.ToString();

        if (name != null && DroppedUsings.Contains(name))
          return null;

        if (name != null && MappedUsings.TryGetValue(name, out var mapped))
          return node.WithName(SyntaxFactory.ParseName(mapped).WithTriviaFrom(node.Name));

        return base.VisitUsingDirective(node);
      }

      // Dedup usings after mapping (a source importing both Copse.Core and Copse.Core.Async maps to
      // Copse.Core twice); keep the first occurrence so its position/trivia is preserved.
      public override SyntaxNode VisitCompilationUnit(CompilationUnitSyntax node)
      {
        node = (CompilationUnitSyntax)base.VisitCompilationUnit(node);

        var seen = new HashSet<string>();
        var deduped = SyntaxFactory.List(node.Usings.Where(u => seen.Add(u.Name?.ToString() ?? "")));

        return node.WithUsings(deduped);
      }

      public override SyntaxNode VisitNamespaceDeclaration(NamespaceDeclarationSyntax node)
      {
        node = (NamespaceDeclarationSyntax)base.VisitNamespaceDeclaration(node);
        return node.WithName(SyntaxFactory.ParseName(_syncNamespace).WithTriviaFrom(node.Name));
      }

      // Strip `await X` -> `X`.
      public override SyntaxNode VisitAwaitExpression(AwaitExpressionSyntax node)
        => ((ExpressionSyntax)Visit(node.Expression)).WithTriviaFrom(node);

      // Strip `X.ConfigureAwait(false)` -> `X`.
      public override SyntaxNode VisitInvocationExpression(InvocationExpressionSyntax node)
      {
        if (node.Expression is MemberAccessExpressionSyntax ma && ma.Name.Identifier.ValueText == "ConfigureAwait")
          return ((ExpressionSyntax)Visit(ma.Expression)).WithTriviaFrom(node);
        return base.VisitInvocationExpression(node);
      }

      // Drop the `async` modifier.
      public override SyntaxNode VisitMethodDeclaration(MethodDeclarationSyntax node)
      {
        node = (MethodDeclarationSyntax)base.VisitMethodDeclaration(node);
        if (node.Modifiers.Any(SyntaxKind.AsyncKeyword))
          node = node.WithModifiers(
            SyntaxFactory.TokenList(node.Modifiers.Where(m => !m.IsKind(SyntaxKind.AsyncKeyword))));

        return node;
      }

      // ----- Cancellation plumbing elision. The sync twin has no cancellation concept, so the
      // transform strips it wholesale, under the repo convention: the parameter is always named
      // `cancellationToken` (optionally [EnumeratorCancellation]), a stored copy is always the
      // field `_CancellationToken`, guards are always standalone
      // `...ThrowIfCancellationRequested();` statements, and call sites forward one of those two
      // names verbatim. (This also covers GetAsyncEnumerator(CancellationToken) -> the
      // parameterless IEnumerable<T>.GetEnumerator().)

      private static bool IsCancellationTokenType(TypeSyntax type)
        => type != null && type.ToString().TrimEnd('?') == "CancellationToken";

      private static bool IsCancellationIdentifier(ExpressionSyntax expression)
        => expression is IdentifierNameSyntax identifier
          && (identifier.Identifier.ValueText == "cancellationToken"
            || identifier.Identifier.ValueText == "_CancellationToken");

      public override SyntaxNode VisitParameterList(ParameterListSyntax node)
      {
        node = (ParameterListSyntax)base.VisitParameterList(node);

        var removed = node.Parameters.Where(p => IsCancellationTokenType(p.Type)).ToList();
        if (removed.Count == 0)
          return node;

        // RemoveNodes drops each parameter with its adjacent separator, preserving the
        // remaining separators' trivia (a rebuilt SeparatedList would lose the ", " spacing).
        return node.RemoveNodes(removed, SyntaxRemoveOptions.KeepNoTrivia);
      }

      public override SyntaxNode VisitArgumentList(ArgumentListSyntax node)
      {
        node = (ArgumentListSyntax)base.VisitArgumentList(node);

        var removed = node.Arguments.Where(a => IsCancellationIdentifier(a.Expression)).ToList();
        if (removed.Count == 0)
          return node;

        return node.RemoveNodes(removed, SyntaxRemoveOptions.KeepNoTrivia);
      }

      // Drop `CancellationToken _CancellationToken;` fields.
      public override SyntaxNode VisitFieldDeclaration(FieldDeclarationSyntax node)
      {
        if (IsCancellationTokenType(node.Declaration.Type))
          return null;

        return base.VisitFieldDeclaration(node);
      }

      // Drop `..ThrowIfCancellationRequested();` guards and `_CancellationToken = cancellationToken;`
      // constructor assignments.
      public override SyntaxNode VisitExpressionStatement(ExpressionStatementSyntax node)
      {
        if (node.Expression is InvocationExpressionSyntax invocation
          && invocation.Expression is MemberAccessExpressionSyntax guardAccess
          && guardAccess.Name.Identifier.ValueText == "ThrowIfCancellationRequested"
          && IsCancellationIdentifier(guardAccess.Expression))
          return null;

        if (node.Expression is AssignmentExpressionSyntax assignment
          && IsCancellationIdentifier(assignment.Left)
          && IsCancellationIdentifier(assignment.Right))
          return null;

        return base.VisitExpressionStatement(node);
      }

      // Drop the `async` modifier from local functions (async iterator helpers in the fluent layer).
      public override SyntaxNode VisitLocalFunctionStatement(LocalFunctionStatementSyntax node)
      {
        node = (LocalFunctionStatementSyntax)base.VisitLocalFunctionStatement(node);
        if (node.Modifiers.Any(SyntaxKind.AsyncKeyword))
          node = node.WithModifiers(
            SyntaxFactory.TokenList(node.Modifiers.Where(m => !m.IsKind(SyntaxKind.AsyncKeyword))));
        return node;
      }

      // `await foreach (...)` -> `foreach (...)`; the await keyword's leading trivia (the
      // statement's indentation) transfers to the foreach keyword.
      public override SyntaxNode VisitForEachStatement(ForEachStatementSyntax node)
      {
        node = (ForEachStatementSyntax)base.VisitForEachStatement(node);
        if (node.AwaitKeyword.IsKind(SyntaxKind.AwaitKeyword))
          node = node
            .WithForEachKeyword(node.ForEachKeyword.WithLeadingTrivia(node.AwaitKeyword.LeadingTrivia))
            .WithAwaitKeyword(default);
        return node;
      }

      // `await using (...) { }` -> `using (...) { }`; same trivia transfer.
      public override SyntaxNode VisitUsingStatement(UsingStatementSyntax node)
      {
        node = (UsingStatementSyntax)base.VisitUsingStatement(node);
        if (node.AwaitKeyword.IsKind(SyntaxKind.AwaitKeyword))
          node = node
            .WithUsingKeyword(node.UsingKeyword.WithLeadingTrivia(node.AwaitKeyword.LeadingTrivia))
            .WithAwaitKeyword(default);
        return node;
      }

      // `await using var x = ...;` -> `using var x = ...;` (the declaration form); same trivia transfer.
      public override SyntaxNode VisitLocalDeclarationStatement(LocalDeclarationStatementSyntax node)
      {
        node = (LocalDeclarationStatementSyntax)base.VisitLocalDeclarationStatement(node);
        if (node.AwaitKeyword.IsKind(SyntaxKind.AwaitKeyword))
          node = node
            .WithUsingKeyword(node.UsingKeyword.WithLeadingTrivia(node.AwaitKeyword.LeadingTrivia))
            .WithAwaitKeyword(default);
        return node;
      }

      // Rename identifier tokens, preserving trivia.
      public override SyntaxToken VisitToken(SyntaxToken token)
      {
        token = base.VisitToken(token);
        if (!token.IsKind(SyntaxKind.IdentifierToken))
          return token;

        var text = token.ValueText;

        // Per-entry class rename (async class -> canonical/Generated sync class).
        if (text == _asyncClass)
          return SyntaxFactory.Identifier(token.LeadingTrivia, _syncClass, token.TrailingTrivia);

        // Explicit type renames (interfaces, type params, and any that don't strip by rule).
        if (Renames.TryGetValue(text, out var renamed))
          return SyntaxFactory.Identifier(token.LeadingTrivia, renamed, token.TrailingTrivia);

        // Generic: strip a leading "Async" from concrete type names (AsyncFooTreenumerable ->
        // FooTreenumerable) so a body reference to a sibling async class transcribes untaught.
        // Interfaces (IAsync...) and type params (TAsync...) don't start with "Async", so they go
        // through the map above; the bare "Async" namespace segment is length 5, so it is intact.
        if (text.Length > 5 && text.StartsWith("Async", StringComparison.Ordinal))
          return SyntaxFactory.Identifier(token.LeadingTrivia, text.Substring(5), token.TrailingTrivia);

        // Generic: strip the "Async" suffix from method identifiers (MoveNextAsync -> MoveNext, and
        // every seam method). Guarded to length > 5 so the bare "Async" segment is intact.
        if (text.Length > 5 && text.EndsWith("Async", StringComparison.Ordinal))
          return SyntaxFactory.Identifier(token.LeadingTrivia, text.Substring(0, text.Length - 5), token.TrailingTrivia);

        return token;
      }
    }
  }
}
