namespace Copse.Dags
{
  public static partial class Dagnumerable
  {
    /// <summary>The upward flow: <c>dag.Sinkfix().Scan  /// <summary>The upward flow door: <c>dag.Sinkfix().Scan&lt;TResult&gt;(…)</c> / <c>.Dispatch&lt;TDispatch&gt;(…)</c> / <c>.DispatchEdges&lt;TDispatch&gt;(…)</c> with one type argument (see <see cref="DagFlow{TNode, TEdge}"/>).</summary>lt;TResult  /// <summary>The upward flow door: <c>dag.Sinkfix().Scan&lt;TResult&gt;(…)</c> / <c>.Dispatch&lt;TDispatch&gt;(…)</c> / <c>.DispatchEdges&lt;TDispatch&gt;(…)</c> with one type argument (see <see cref="DagFlow{TNode, TEdge}"/>).</summary>gt;(…)</c> / <c>.Dispatch  /// <summary>The upward flow door: <c>dag.Sinkfix().Scan&lt;TResult&gt;(…)</c> / <c>.Dispatch&lt;TDispatch&gt;(…)</c> / <c>.DispatchEdges&lt;TDispatch&gt;(…)</c> with one type argument (see <see cref="DagFlow{TNode, TEdge}"/>).</summary>lt;TDispatch  /// <summary>The upward flow door: <c>dag.Sinkfix().Scan&lt;TResult&gt;(…)</c> / <c>.Dispatch&lt;TDispatch&gt;(…)</c> / <c>.DispatchEdges&lt;TDispatch&gt;(…)</c> with one type argument (see <see cref="DagFlow{TNode, TEdge}"/>).</summary>gt;(…)</c> / <c>.DispatchEdges  /// <summary>The upward flow door: <c>dag.Sinkfix().Scan&lt;TResult&gt;(…)</c> / <c>.Dispatch&lt;TDispatch&gt;(…)</c> / <c>.DispatchEdges&lt;TDispatch&gt;(…)</c> with one type argument (see <see cref="DagFlow{TNode, TEdge}"/>).</summary>lt;TDispatch  /// <summary>The upward flow door: <c>dag.Sinkfix().Scan&lt;TResult&gt;(…)</c> / <c>.Dispatch&lt;TDispatch&gt;(…)</c> / <c>.DispatchEdges&lt;TDispatch&gt;(…)</c> with one type argument (see <see cref="DagFlow{TNode, TEdge}"/>).</summary>gt;(…)</c> -- THE spelling of the sinkfix family (see <see cref="DagFlow{TNode, TEdge}"/>).</summary>
    public static DagFlow<TNode, TEdge> Sinkfix<TNode, TEdge>(this IDagnumerable<TNode, TEdge> source)
      => new DagFlow<TNode, TEdge>(source, DagFlowOrientation.Sinkfix);
  }
}
