// <auto-generated>
//   Generated from AsyncSelectWhereTreenumerable.cs by Copse.CodeGen (composite->narrow transcription).
//   Do not edit; edit the composite-width source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Linq.Treenumerators;
using Copse.Core;
using Copse.Linq;
using System;

namespace Copse.Linq.Treenumerables
{
  // The reified operator chain (design-docs/OPERATOR_COMPOSITION_DESIGN.md, "the result
  // monad"): one wrapper holding the Kleisli-composed result of every composed operator, so
  // chains of any length and order collapse to ONE layer over the source. Plain operators
  // instantiate with their bespoke selector STRUCT (inlined by the JIT -- zero seam cost);
  // composed chains nest those structs in the TYPE via AsyncComposedResultSelector (a user
  // delegate enters only as a AsyncFuncResultSelector leaf). Splicing is total: every legality
  // decision was made outer-side.
  internal sealed partial class AsyncSelectWhereDepthFirstTreenumerable<TSource, TResult, TResultSelector> : IAsyncSelectWhereDepthFirstTreenumerable<TResult>
    where TResultSelector : struct, IAsyncResultSelector<TSource, TResult>
  {
    public AsyncSelectWhereDepthFirstTreenumerable(
      IAsyncDepthFirstTreenumerable<TSource> source,
      TResultSelector resultSelector)
    {
      _Source = source;
      _ResultSelector = resultSelector;
    }

    private readonly IAsyncDepthFirstTreenumerable<TSource> _Source;
    private readonly TResultSelector _ResultSelector;

    public IAsyncTreenumerator<TResult> GetAsyncDepthFirstTreenumerator() =>
      new AsyncWhereDepthFirstTreenumerator<TSource, TResult, TResultSelector>(
        _Source.GetAsyncDepthFirstTreenumerator, _ResultSelector);

    // The composition law under this representation's successor choice: the general
    // wrapper composes to a general wrapper, and the chain nests in the type -- every leg
    // inlinable.
    public IAsyncDepthFirstTreenumerable<TOuterResult> Compose<TOuterResult, TOuterSelector>(
      TOuterSelector outerSelector,
      bool relabels)
      where TOuterSelector : struct, IAsyncResultSelector<TResult, TOuterResult>
      => Splice<TOuterResult, TOuterSelector>(outerSelector);

    // The context-shaped projection door: the projection rides an inlinable struct leg
    // (the caller has already applied the join rule for positional legs).
    public IAsyncDepthFirstTreenumerable<TOuterResult> Compose<TOuterResult>(Func<NodeAndPosition<TResult>, TOuterResult> selector)
      => Splice<TOuterResult, AsyncSelectResultSelector<TResult, TOuterResult>>(
        new AsyncSelectResultSelector<TResult, TOuterResult>(selector));

    // THE ONE CONSTRUCTION of a composed successor: every door that splices a leg lands
    // here, so the nested-selector spelling has a single home. It returns the concrete type
    // because an interface implementation cannot -- which is what lets the public
    // projection door (the citizenship part) reuse it rather than respell it.
    private AsyncSelectWhereDepthFirstTreenumerable<TSource, TOuterResult, AsyncComposedResultSelector<TSource, TResult, TOuterResult, TResultSelector, TOuterSelector>> Splice<TOuterResult, TOuterSelector>(
      TOuterSelector outerSelector)
      where TOuterSelector : struct, IAsyncResultSelector<TResult, TOuterResult>
      => new AsyncSelectWhereDepthFirstTreenumerable<TSource, TOuterResult, AsyncComposedResultSelector<TSource, TResult, TOuterResult, TResultSelector, TOuterSelector>>(
        _Source,
        new AsyncComposedResultSelector<TSource, TResult, TOuterResult, TResultSelector, TOuterSelector>(_ResultSelector, outerSelector));

    // ---- The position-reading doors: this driver STACKS ----
    //
    // A spliced leg is evaluated against this driver's INNER coordinates, which are not the
    // ones it publishes -- promotion has moved them. So a position-reading leg goes into a
    // wrapper over this driver, where it reads published labels by construction. Nothing is
    // consulted: a driver exists because something rejected, and rejection is what moves
    // labels.
    public IAsyncDepthFirstTreenumerable<TOuterResult> ComposePositional<TOuterResult>(Func<NodeAndPosition<TResult>, TOuterResult> selector)
      => new AsyncSelectDepthFirstTreenumerable<TResult, TOuterResult>(this, selector);

    public IAsyncDepthFirstTreenumerable<TOuterResult> ComposePositional<TOuterResult, TOuterSelector>(
      TOuterSelector outerSelector,
      bool relabels)
      where TOuterSelector : struct, IAsyncResultSelector<TResult, TOuterResult>
      => new AsyncSelectWhereDepthFirstTreenumerable<TResult, TOuterResult, TOuterSelector>(this, outerSelector);

    // The context-shaped prune-after door: prune-afters compose in-tier only, so the light
    // prune wrapper STACKS over the driver rather than demoting its representation for a
    // layer that costs almost nothing.
    public IAsyncDepthFirstTreenumerable<TResult> ComposePruneDescendantsWhere(Func<NodeAndPosition<TResult>, bool> predicate)
      => new AsyncPruneDescendantsWhereDepthFirstTreenumerable<TResult>(this, predicate);
  }
}
