// <auto-generated>
//   Generated from IAsyncSelectWhereTreenumerable.cs by Copse.CodeGen (composite->narrow transcription).
//   Do not edit; edit the composite-width source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core.Async;
using System;

namespace Copse.Linq.Async.Treenumerables
{
  // The composition recipe surface (design-docs/OPERATOR_COMPOSITION_DESIGN.md): appending an operator is
  // ONE call -- the wrapper unwraps its own mapping, composes the result selector onto it, discards
  // itself, and constructs the successor treenumerable. The operator composes with bare
  // lambdas (it knows its own flavor and reads Relabels for the join rule);
  // the wrapper, which knows the erased source type, binds it and constructs.
  //
  // ONE method covers the whole selector algebra: a projection is just a result selector that never
  // rejects (its results carry TraverseAll), and the composition law handles it without
  // being told. The light projection-only representation is not this contract's business --
  // it is the capability of the one wrapper that has it (AsyncSelectTreenumerable).
  //
  // Deliberately INTERNAL: a public recipe would make these operators' correctness depend on
  // foreign implementations, and the older TFMs' lack of default interface members would make
  // every evolution a breaking change.
  //
  // THE REVERSED HIERARCHY (PUBLIC_COMPOSITION_SURFACE_DESIGN.md): this interface EXTENDS
  // the public capability bases -- the strategy-expressible fragment (projection,
  // prune-after) is public at the root; the driver algebra (rejection, relabeling, the
  // struct splice) is this internal layer above it. Every member of this surface therefore
  // answers the public doors, each with ITS OWN best machinery (the door-optimality law:
  // the light wrappers stay light, the driver nests a leg, the scan citizens re-plant).
  // The narrow twins strip the public bases in the fan-out -- narrow parity is deferred,
  // so the public doors are composite-width only.
  internal interface IAsyncSelectWhereDepthFirstTreenumerable<TNode>
    : IAsyncDepthFirstTreenumerable<TNode>  {
    // True once any relabeling operator is aboard; the operators' positional flavors read this
    // to apply the join rule before composing.
    bool Relabels { get; }

    // Compose a result selector onto the accumulated mapping and return the successor treenumerable.
    // relabels: whether THIS operator moves surviving nodes' labels (Where and PruneBefore do;
    // PruneAfter and projections do not).
    IAsyncDepthFirstTreenumerable<TOuterResult> Compose<TOuterResult>(
      Func<NodeContext<TNode>, SelectWhereResult<TOuterResult>> resultSelector,
      bool relabels);

    // The STRUCT-composed form (the reunification gate): the outer piece arrives as an
    // inlinable selector struct, so the successor's composed chain nests in the TYPE and the
    // splice costs no delegate hops. The Func form above remains for pieces that are
    // inherently closures.
    IAsyncDepthFirstTreenumerable<TOuterResult> Compose<TOuterResult, TOuterSelector>(
      TOuterSelector outerSelector,
      bool relabels)
      where TOuterSelector : struct, IResultSelector<TNode, TOuterResult>;

    // The context-shaped projection door (the light tier's door, absorbed here when the
    // conjunction marker retired): the leg is a pure projection that MAY read positions --
    // the caller has already applied the join rule (the positional flavors check Relabels
    // before knocking). Per the door-optimality law: light wrappers compose in-tier and
    // stay light; the driver splices a struct leg; the scan citizens splice into the
    // fold-carrying driver.
    IAsyncDepthFirstTreenumerable<TOuterResult> Compose<TOuterResult>(Func<NodeContext<TNode>, TOuterResult> selector);

    // The context-shaped prune-after door (same absorption). Per the in-tier-only boundary
    // ruling (2026-08-04, the surviving half): light wrappers merge in-tier; every other
    // member STACKS the light prune wrapper over itself -- joining would demote its
    // representation for a layer that costs almost nothing.
    IAsyncDepthFirstTreenumerable<TNode> ComposePruneAfter(Func<NodeContext<TNode>, bool> predicate);
  }
}
