// <auto-generated>
//   Generated from AsyncBreadthFirstTreeTokenizer.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Linq.TreeTokenizer.BreadthFirstTree;
using System.Collections;
using System.Collections.Generic;

namespace Copse.Linq.TreeTokenizer.BreadthFirstTree
{
  // Intentionally kept though nothing consumes it yet: the symmetric pair of
  // AsyncDepthFirstTreeTokenizer (which backs ToFormattedLines / the pretty-printer). Not dead code
  // to be swept -- the asymmetry of dropping only the breadth-first half isn't worth it, and
  // this is the half a future level-order tokenizer-based serializer would want.
  public sealed class BreadthFirstTreeTokenizer<TNode> : IBreadthFirstTreeTokenizer<TNode>
  {
    public BreadthFirstTreeTokenizer(IBreadthFirstTreenumerable<TNode> treenumerable)
    {
      _Treenumerable = treenumerable;
    }

    public BreadthFirstTreeTokenizer(IEnumerable<BreadthFirstTreeToken<TNode>> enumerable)
    {
      _Enumerable = enumerable;
    }

    private readonly IBreadthFirstTreenumerable<TNode> _Treenumerable;
    private readonly IEnumerable<BreadthFirstTreeToken<TNode>> _Enumerable;

    public IEnumerator<BreadthFirstTreeToken<TNode>> GetEnumerator()
    {
      return
        _Enumerable != null
          ? _Enumerable.GetEnumerator()
          : new BreadthFirstTreeTokenEnumerator<TNode>(_Treenumerable.GetBreadthFirstTreenumerator());
    }

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
  }
}
