// <auto-generated>
//   Generated from AsyncTreenumerable.ToDepthFirstTreeTokenizer.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Linq.TreeTokenizer.DepthFirstTree;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    public static IDepthFirstTreeTokenizer<TNode> ToDepthFirstTreeTokenizer<TNode>(
      this IDepthFirstTreenumerable<TNode> source)
    {
      return new DepthFirstTreeTokenizer<TNode>(source);
    }
  }
}
