// <auto-generated>
//   Generated from AsyncTreenumerable.Select.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Linq.Treenumerators;
using Copse.Linq.Treenumerables;
using System;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>
    /// Async <c>Select</c>: maps each node's context, forwarding the visit stream unchanged.
    /// Deferred. Takes the selector over <see cref="NodeContext{TSource}"/> like the sync twin
    /// (position-aware selection is the tree-shaped contract; a value-only selector is
    /// <c>nc =&gt; f(nc.Node)</c>). Consecutive selects fuse: selecting over a select composes the
    /// selectors instead of stacking wrappers.
    /// </summary>
    public static ITreenumerable<TResult> Select<TSource, TResult>(
      this ITreenumerable<TSource> source,
      Func<NodeContext<TSource>, TResult> selector)
    {
      if (source is ISelectTreenumerable<TSource> innerSelectTreenumerable)
        return innerSelectTreenumerable.Compose(selector);
      else
        return new SelectTreenumerable<TSource, TResult>(source, selector);
    }

    public static IDepthFirstTreenumerable<TResult> Select<TSource, TResult>(
      this IDepthFirstTreenumerable<TSource> source,
      Func<NodeContext<TSource>, TResult> selector)
      => TreenumerableFactory.CreateDepthFirst(
        () => new SelectTreenumerator<TSource, TResult>(source.GetDepthFirstTreenumerator, selector));

    public static IBreadthFirstTreenumerable<TResult> Select<TSource, TResult>(
      this IBreadthFirstTreenumerable<TSource> source,
      Func<NodeContext<TSource>, TResult> selector)
      => TreenumerableFactory.CreateBreadthFirst(
        () => new SelectTreenumerator<TSource, TResult>(source.GetBreadthFirstTreenumerator, selector));
  }
}
