// <auto-generated>
//   Generated from AsyncTreenumerable.GetLeaves.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using System.Collections.Generic;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>The tree's leaf nodes in preorder, as a lazy async sequence (depth-first dimension).</summary>
    public static IEnumerable<TNode> GetLeaves<TNode>(this IDepthFirstTreenumerable<TNode> source)
    {
      var treenumerator = source.GetDepthFirstTreenumerator();
      using (treenumerator)
      {
        if (!treenumerator.MoveNext(NodeTraversalStrategies.TraverseAll))
          yield break;

        TNode previousNode = treenumerator.Node;
        int previousDepth = treenumerator.Position.Depth;

        while (treenumerator.MoveNext(NodeTraversalStrategies.SkipNode))
        {
          if (previousDepth >= treenumerator.Position.Depth)
            yield return previousNode;

          previousNode = treenumerator.Node;
          previousDepth = treenumerator.Position.Depth;
        }

        yield return previousNode;
      }
    }

    /// <summary>
    /// The tree's leaf nodes in LEVEL order (breadth-first dimension). "Leaf" is exactly "first visit
    /// not followed by a child schedule" -- one pending slot of state.
    /// </summary>
    public static IEnumerable<TNode> GetLeaves<TNode>(this IBreadthFirstTreenumerable<TNode> source)
    {
      var treenumerator = source.GetBreadthFirstTreenumerator();
      using (treenumerator)
      {
        var hasPending = false;
        var pending = default(TNode);

        while (treenumerator.MoveNext(NodeTraversalStrategies.TraverseAll))
        {
          if (treenumerator.Mode == TreenumeratorMode.SchedulingNode)
          {
            // The pending first-visited node just scheduled a child: not a leaf.
            hasPending = false;
          }
          else if (treenumerator.VisitCount == 1)
          {
            if (hasPending)
              yield return pending;

            pending = treenumerator.Node;
            hasPending = true;
          }
        }

        if (hasPending)
          yield return pending;
      }
    }

    /// <summary>
    /// With both narrow overloads present, a full <see cref="IAsyncTreenumerable{TNode}"/> needs its own
    /// overload to resolve (neither narrow one is better); it keeps the depth-first behavior.
    /// </summary>
    public static IEnumerable<TNode> GetLeaves<TNode>(this ITreenumerable<TNode> source)
      => GetLeaves((IDepthFirstTreenumerable<TNode>)source);
  }
}
