// <auto-generated>
//   Generated from AsyncTreenumerable.Select.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Linq.Treenumerators;
using Copse.Linq.Treenumerables;
using System;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>
    /// Async <c>Select</c> over node VALUES: maps each node, forwarding the visit stream
    /// unchanged (positions never move under a projection). Deferred. Consecutive selects
    /// collapse by selector composition, and a following Where (either flavor) composes into
    /// the projection-carrying filter driver (docs/OPERATOR_FUSION_DESIGN.md).
    /// </summary>
    public static ITreenumerable<TResult> Select<TSource, TResult>(
      this ITreenumerable<TSource> source,
      Func<TSource, TResult> selector)
    {
      // A value selector observes no coordinates, so it composes unconditionally. The fast
      // path first: a projection-only chain composes selectors and stays on the light
      // acquisition; anything else composes the projection as a never-rejecting selector.
      if (source is ISelectPruneAfterTreenumerable<TSource> selectPruneAfterSource)
        return selectPruneAfterSource.Compose(nodeContext => selector(nodeContext.Node));

      if (source is ISelectWhereTreenumerable<TSource> selectWhereSource)
        return selectWhereSource.Compose(
          nodeContext => new SelectWhereResult<TResult>(selector(nodeContext.Node), NodeTraversalStrategies.TraverseAll),
          relabels: false);

      return SelectCore(source, nodeContext => selector(nodeContext.Node));
    }

    /// <summary>
    /// Async <c>Select</c> over (node, position) -- the positional analog of LINQ's indexed
    /// Select. Positions never move under a projection, so this flavor composes exactly like
    /// the value-only one.
    /// </summary>
    public static ITreenumerable<TResult> Select<TSource, TResult>(
      this ITreenumerable<TSource> source,
      Func<TSource, NodePosition, TResult> selector)
    {
      // The join rule (see Where's positional overload): splice only over a label-preserving
      // chain; otherwise stack, so the selector reads genuinely emitted labels.
      if (source is ISelectPruneAfterTreenumerable<TSource> selectPruneAfterSource && !selectPruneAfterSource.Relabels)
        return selectPruneAfterSource.Compose(nodeContext => selector(nodeContext.Node, nodeContext.Position));

      if (source is ISelectWhereTreenumerable<TSource> selectWhereSource && !selectWhereSource.Relabels)
        return selectWhereSource.Compose(
          nodeContext => new SelectWhereResult<TResult>(selector(nodeContext.Node, nodeContext.Position), NodeTraversalStrategies.TraverseAll),
          relabels: false);

      return SelectCore(source, nodeContext => selector(nodeContext.Node, nodeContext.Position));
    }

    private static ITreenumerable<TResult> SelectCore<TSource, TResult>(
      ITreenumerable<TSource> source,
      Func<NodeContext<TSource>, TResult> selector)
    {
      return new SelectTreenumerable<TSource, TResult>(source, selector);
    }

    public static IDepthFirstTreenumerable<TResult> Select<TSource, TResult>(
      this IDepthFirstTreenumerable<TSource> source,
      Func<TSource, TResult> selector)
      => TreenumerableFactory.CreateDepthFirst(
        () => new SelectTreenumerator<TSource, TResult>(
          source.GetDepthFirstTreenumerator, nodeContext => selector(nodeContext.Node)));

    public static IDepthFirstTreenumerable<TResult> Select<TSource, TResult>(
      this IDepthFirstTreenumerable<TSource> source,
      Func<TSource, NodePosition, TResult> selector)
      => TreenumerableFactory.CreateDepthFirst(
        () => new SelectTreenumerator<TSource, TResult>(
          source.GetDepthFirstTreenumerator, nodeContext => selector(nodeContext.Node, nodeContext.Position)));

    public static IBreadthFirstTreenumerable<TResult> Select<TSource, TResult>(
      this IBreadthFirstTreenumerable<TSource> source,
      Func<TSource, TResult> selector)
      => TreenumerableFactory.CreateBreadthFirst(
        () => new SelectTreenumerator<TSource, TResult>(
          source.GetBreadthFirstTreenumerator, nodeContext => selector(nodeContext.Node)));

    public static IBreadthFirstTreenumerable<TResult> Select<TSource, TResult>(
      this IBreadthFirstTreenumerable<TSource> source,
      Func<TSource, NodePosition, TResult> selector)
      => TreenumerableFactory.CreateBreadthFirst(
        () => new SelectTreenumerator<TSource, TResult>(
          source.GetBreadthFirstTreenumerator, nodeContext => selector(nodeContext.Node, nodeContext.Position)));
  }
}
