// <auto-generated>
//   Generated from AsyncTreenumerable.LeaffixDoScan.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Linq.Treenumerables;
using System;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>
    /// The IMPURE leaffix fold (SPIKE, feature/do-scan): LeaffixScan's Do twin -- map-then-combine
    /// up the tree, with each node's completed accumulation landing on the caller's objects via
    /// <paramref name="store"/> and the nodes passing through unchanged. Every node's
    /// accumulation starts at <paramref name="nodeSelector"/> (a leaf is the projection
    /// unchanged) and each child's completed accumulation is combined in by
    /// <paramref name="accumulator"/>, one child at a time in sibling order.
    ///
    /// <para>WHY <paramref name="store"/> KEEPS ITS SEAT HERE when RootfixDoScan's merged away
    /// (ruled 2026-08-04): the binary combine fires per CHILD EDGE -- zero times on leaves, k
    /// times on a k-child node, and no invocation can know it is the last -- so no fold
    /// invocation ever holds a node's completed accumulation to land. <paramref name="store"/>
    /// is the only node-grained channel; the rootfix fold, the family's one
    /// once-per-node-with-value-in-hand callback, is the only shape where landing rides the
    /// return. <paramref name="nodeSelector"/> and <paramref name="accumulator"/> are PURE;
    /// <paramref name="store"/> is the declared effect point -- EXACTLY once per node per
    /// build, preorder order, the (node, accumulation) pairing. Effect count follows the
    /// laziness class: leaffix folds are CAPTURES (children-first), so effects fire once per
    /// operator instance at the first drain and replays never re-fire -- unlike the streaming
    /// RootfixDoScan's per-drain contract, and for the same rule. Sequencing (via the dispatch
    /// build): stores fire in preorder AFTER the whole fold pass completes, so a throwing
    /// <paramref name="accumulator"/> lands nothing, while a throwing <paramref name="store"/>
    /// leaves the prefix already landed -- disclosed, not contracted against. Composition
    /// barrier like <c>Do</c>.</para>
    ///
    /// <para>Sugar over <see cref="LeaffixDoDispatch{TSource, TAccumulate}"/>, the pure pair's
    /// own delegation LEGITIMATELY mirrored: both leaffix tiers share one cost class, so the
    /// fold rides the sibling-complete build at the measured wrapper premium and improvements
    /// land once. Anything needing all children at once is a survey -- use LeaffixDoDispatch.</para>
    /// </summary>
    public static ITreenumerableBuffer<TSource> LeaffixDoScan<TSource, TAccumulate>(
      this IDepthFirstTreenumerable<TSource> source,
      Func<TSource, TAccumulate> nodeSelector,
      Func<TAccumulate, TAccumulate, TAccumulate> accumulator,
      Action<TSource, TAccumulate> store)
      => LeaffixDoDispatch(source, nodeSelector, DoFoldSurvey(nodeSelector, accumulator), store);

    /// <summary>
    /// The context flavor: the combine also sees the FOLDING node's value, for rules like
    /// weighting each child's rollup by the folding node's own factor. Needs more than that --
    /// other children, child identity -- it is a survey: use LeaffixDoDispatch.
    /// </summary>
    public static ITreenumerableBuffer<TSource> LeaffixDoScan<TSource, TAccumulate>(
      this IDepthFirstTreenumerable<TSource> source,
      Func<TSource, TAccumulate> nodeSelector,
      Func<TSource, TAccumulate, TAccumulate, TAccumulate> accumulator,
      Action<TSource, TAccumulate> store)
      => LeaffixDoDispatch(source, nodeSelector, DoFoldSurvey(nodeSelector, accumulator), store);

    /// <summary>The breadth-first-only source overload; the disclosure-rule escalation is LeaffixDoDispatch's.</summary>
    public static ITreenumerableBuffer<TSource> LeaffixDoScan<TSource, TAccumulate>(
      this IBreadthFirstTreenumerable<TSource> source,
      Func<TSource, TAccumulate> nodeSelector,
      Func<TAccumulate, TAccumulate, TAccumulate> accumulator,
      Action<TSource, TAccumulate> store)
      => LeaffixDoDispatch(source, nodeSelector, DoFoldSurvey(nodeSelector, accumulator), store);

    public static ITreenumerableBuffer<TSource> LeaffixDoScan<TSource, TAccumulate>(
      this IBreadthFirstTreenumerable<TSource> source,
      Func<TSource, TAccumulate> nodeSelector,
      Func<TSource, TAccumulate, TAccumulate, TAccumulate> accumulator,
      Action<TSource, TAccumulate> store)
      => LeaffixDoDispatch(source, nodeSelector, DoFoldSurvey(nodeSelector, accumulator), store);

    /// <summary>Disambiguation overloads for full trees; keep the historical depth-first consumption.</summary>
    public static ITreenumerableBuffer<TSource> LeaffixDoScan<TSource, TAccumulate>(
      this ITreenumerable<TSource> source,
      Func<TSource, TAccumulate> nodeSelector,
      Func<TAccumulate, TAccumulate, TAccumulate> accumulator,
      Action<TSource, TAccumulate> store)
      => LeaffixDoScan((IDepthFirstTreenumerable<TSource>)source, nodeSelector, accumulator, store);

    public static ITreenumerableBuffer<TSource> LeaffixDoScan<TSource, TAccumulate>(
      this ITreenumerable<TSource> source,
      Func<TSource, TAccumulate> nodeSelector,
      Func<TSource, TAccumulate, TAccumulate, TAccumulate> accumulator,
      Action<TSource, TAccumulate> store)
      => LeaffixDoScan((IDepthFirstTreenumerable<TSource>)source, nodeSelector, accumulator, store);

    // The fold expressed as a survey, value-flavored (the Do tier's grammar): start at the
    // node's own projection, combine each child's completed accumulation in sibling order.
    private static Func<TSource, DispatchSources<TSource, TAccumulate>, TAccumulate> DoFoldSurvey<TSource, TAccumulate>(
      Func<TSource, TAccumulate> nodeSelector,
      Func<TAccumulate, TAccumulate, TAccumulate> accumulator)
      => (node, children) =>
      {
        var accumulate = nodeSelector(node);
        foreach (var child in children)
          accumulate = accumulator(accumulate, child.Accumulate);
        return accumulate;
      };

    private static Func<TSource, DispatchSources<TSource, TAccumulate>, TAccumulate> DoFoldSurvey<TSource, TAccumulate>(
      Func<TSource, TAccumulate> nodeSelector,
      Func<TSource, TAccumulate, TAccumulate, TAccumulate> accumulator)
      => (node, children) =>
      {
        var accumulate = nodeSelector(node);
        foreach (var child in children)
          accumulate = accumulator(node, accumulate, child.Accumulate);
        return accumulate;
      };
  }
}
