// <auto-generated>
//   Generated from AsyncTreenumerable.GetRoots.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using System.Collections.Generic;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>
    /// The forest's root nodes, as a lazy async sequence. Drives with SkipNodeAndDescendants so each
    /// root is scheduled once and its subtree skipped. Deferred sequence -&gt; keeps the sync name (returns
    /// <see cref="IAsyncEnumerable{TNode}"/>, the async analog of the sync <c>IEnumerable</c> result).
    /// </summary>
    public static IEnumerable<TNode> GetRoots<TNode>(this IDepthFirstTreenumerable<TNode> source)
    {
      var treenumerator = source.GetDepthFirstTreenumerator();
      using (treenumerator)
      {
        while (treenumerator.MoveNext(NodeTraversalStrategies.SkipNodeAndDescendants))
        {
          yield return treenumerator.Node;
        }
      }
    }
  }
}
