// <auto-generated>
//   Generated from AsyncTreenumerable.LeaffixScan.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Treenumerables;
using Copse.Treenumerators;
using Copse.Core;
using Copse.Linq.Treenumerables;
using Copse.Linq.Treenumerators;
using Copse.Linq.Extensions;
using System;
using System.Collections.Generic;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>
    /// Bottom-up scan: every node gets an accumulated value -- leaves from
    /// <paramref name="leafNodeSelector"/>, internal nodes from <paramref name="accumulator"/>
    /// over their children's accumulated values. The result tree has the same shape as the source.
    ///
    /// <para>Returns an <see cref="IAsyncTreenumerableBuffer{TValue}"/> because LeaffixScan
    /// MANUFACTURES owned O(n) storage: the projected accumulations are new values that exist
    /// nowhere in the source, and a root's value IS its whole subtree's aggregate -- the source
    /// is fully consumed before the first result visit can be published, so the result is a
    /// completed capture, not a lazy stream. Deferred like the sync twin (hence the sync name):
    /// the awaited build runs ONCE, on the first replay pull, through the lazy-built store's
    /// grow seam -- async cannot defer inside a sync-signature treenumerator factory the way the
    /// sync operator's <c>Lazy&lt;&gt;</c> does. The source is consumed depth-first only, so a
    /// streamed narrow source can leaffix.</para>
    ///
    /// <para>Single forward DFS pass into flat pre-order arrays; see the sync operator for the
    /// construction notes (subtree-size hop, O(depth) working set).</para>
    /// </summary>
    public static ITreenumerableBuffer<TAccumulate> LeaffixScan<TSource, TAccumulate>(
      this IDepthFirstTreenumerable<TSource> source,
      Func<NodeContext<TSource>, TAccumulate> leafNodeSelector,
      Func<NodeContext<TSource>, ChildAccumulations<TAccumulate>, TAccumulate> accumulator)
    {
      var scanned = new LazyBuiltPreorderStore<TAccumulate>(
        () => BuildLeaffixScan(source, leafNodeSelector, accumulator));

      return new CompletedTreenumerableBuffer<TAccumulate>(
        new DelegatingTreenumerable<TAccumulate>(
          () => new PreorderStoreBreadthFirstTreenumerator<TAccumulate, LazyBuiltPreorderStore<TAccumulate>>(scanned),
          () => new PreorderStoreDepthFirstTreenumerator<TAccumulate, LazyBuiltPreorderStore<TAccumulate>>(scanned)));
    }

    private static PreorderArrayStore<TAccumulate> BuildLeaffixScan<TSource, TAccumulate>(
      IDepthFirstTreenumerable<TSource> source,
      Func<NodeContext<TSource>, TAccumulate> leafNodeSelector,
      Func<NodeContext<TSource>, ChildAccumulations<TAccumulate>, TAccumulate> accumulator)
    {
      var accumulations = new List<TAccumulate>();
      var subtreeSizes = new List<int>();
      var path = new Stack<PendingNode<TSource>>(); // open ancestors of the current node

      void Close()
      {
        var pending = path.Pop();
        var index = pending.Index;

        subtreeSizes[index] = accumulations.Count - index;
        accumulations[index] =
          subtreeSizes[index] == 1
          ? leafNodeSelector(pending.Context)
          : accumulator(pending.Context, new ChildAccumulations<TAccumulate>(accumulations, subtreeSizes, index));
      }

      var treenumerator = source.GetDepthFirstTreenumerator();
      using (treenumerator)
      {
        while (treenumerator.MoveNext(NodeTraversalStrategies.TraverseAll))
        {
          if (treenumerator.Mode != TreenumeratorMode.SchedulingNode)
            continue;

          // Returning to this depth (or shallower) means every deeper open node is complete.
          while (path.Count > treenumerator.Position.Depth)
            Close();

          path.Push(new PendingNode<TSource>(accumulations.Count, treenumerator.ToNodeContext()));
          accumulations.Add(default); // backfilled when this node closes
          subtreeSizes.Add(0);
        }
      }

      while (path.Count > 0)
        Close();

      return new PreorderArrayStore<TAccumulate>(accumulations.ToArray(), subtreeSizes.ToArray());
    }
  }
}
