// <auto-generated>
//   Generated from AsyncTreenumerable.PruneAfter.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Linq.Treenumerators;
using Copse.Linq.Treenumerables;
using System;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>
    /// Async <c>PruneAfter</c> over node VALUES: keeps each matching node but sheds its subtree
    /// (the matched node is the deepest of its lineage kept). Deferred. PruneAfter is
    /// label-preserving: survivors keep their coordinates.
    /// </summary>
    public static ITreenumerable<T> PruneAfter<T>(
      this ITreenumerable<T> source,
      Func<T, bool> predicate)
    {
      if (predicate == null)
        return source;

      // A value predicate observes no coordinates, so it composes unconditionally. The stage
      // comes from the wrapper's CreateStage: the operator's semantics, stated once.
      if (source is ISelectWhereTreenumerable<T> selectWhereSource)
        return selectWhereSource.Compose(
          PruneAfterTreenumerable<T>.CreateStage(nodeContext => predicate(nodeContext.Node)),
          relabels: false);

      return new PruneAfterTreenumerable<T>(source, nodeContext => predicate(nodeContext.Node));
    }

    /// <summary>
    /// Async <c>PruneAfter</c> over (node, position). Deferred. The positional predicate sees
    /// ITS input tree's labels.
    /// </summary>
    public static ITreenumerable<T> PruneAfter<T>(
      this ITreenumerable<T> source,
      Func<T, NodePosition, bool> predicate)
    {
      if (predicate == null)
        return source;

      // The join rule: a positional predicate composes only over a label-preserving chain.
      if (source is ISelectWhereTreenumerable<T> selectWhereSource && !selectWhereSource.ContainsRelabelingStage)
        return selectWhereSource.Compose(
          PruneAfterTreenumerable<T>.CreateStage(nodeContext => predicate(nodeContext.Node, nodeContext.Position)),
          relabels: false);

      return new PruneAfterTreenumerable<T>(source, nodeContext => predicate(nodeContext.Node, nodeContext.Position));
    }

    public static IDepthFirstTreenumerable<T> PruneAfter<T>(
      this IDepthFirstTreenumerable<T> source,
      Func<T, bool> predicate)
    {
      if (predicate == null)
        return source;

      return
        TreenumerableFactory.CreateDepthFirst(
          () => new PruneAfterTreenumerator<T>(
            source.GetDepthFirstTreenumerator, nodeContext => predicate(nodeContext.Node)));
    }

    public static IDepthFirstTreenumerable<T> PruneAfter<T>(
      this IDepthFirstTreenumerable<T> source,
      Func<T, NodePosition, bool> predicate)
    {
      if (predicate == null)
        return source;

      return
        TreenumerableFactory.CreateDepthFirst(
          () => new PruneAfterTreenumerator<T>(
            source.GetDepthFirstTreenumerator, nodeContext => predicate(nodeContext.Node, nodeContext.Position)));
    }

    public static IBreadthFirstTreenumerable<T> PruneAfter<T>(
      this IBreadthFirstTreenumerable<T> source,
      Func<T, bool> predicate)
    {
      if (predicate == null)
        return source;

      return
        TreenumerableFactory.CreateBreadthFirst(
          () => new PruneAfterTreenumerator<T>(
            source.GetBreadthFirstTreenumerator, nodeContext => predicate(nodeContext.Node)));
    }

    public static IBreadthFirstTreenumerable<T> PruneAfter<T>(
      this IBreadthFirstTreenumerable<T> source,
      Func<T, NodePosition, bool> predicate)
    {
      if (predicate == null)
        return source;

      return
        TreenumerableFactory.CreateBreadthFirst(
          () => new PruneAfterTreenumerator<T>(
            source.GetBreadthFirstTreenumerator, nodeContext => predicate(nodeContext.Node, nodeContext.Position)));
    }
  }
}
