// <auto-generated>
//   Generated from AsyncTreenumerable.RootfixDoDispatch.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Stores;
using Copse.Treenumerables;
using Copse.Core;
using Copse.Linq.Treenumerables;
using Copse.Linq.Stores;
using System;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>
    /// The IMPURE survey-shaped downward pass (SPIKE, feature/do-scan): RootfixDispatch's Do
    /// twin, for the mutable-node workload. Nodes pass through unchanged (the result is the
    /// SOURCE tree; no <see cref="ScanResult{TSource, TDispatch}"/> decoration ever reaches
    /// the caller -- Do means the nodes ARE the result), and the flow lands where the caller wants it via <paramref name="store"/>.
    ///
    /// <para>Two callbacks, two contracts -- the purity boundary sits between them.
    /// <paramref name="survey"/> is PURE and speaks only the exactly-once slot protocol, with
    /// the pure operator's identical shape: the parent's value, its arrival, and the complete
    /// live child list as write-handles (a setter-callback allocator plugs in verbatim --
    /// <c>(child, amount) =&gt; child.Dispatch(amount)</c> IS its assignment callback; missed
    /// and doubled slots throw). <paramref name="store"/> is the declared effect point: it
    /// fires EXACTLY ONCE per node per build, in preorder order, receiving the
    /// (node, arrival) pairing -- roots receive the seed, leaves their arrivals, so coverage
    /// is total. Where the pure build writes each (value, arrival) pair into its decoration,
    /// this build hands the same pair to store; keeping the entity-write out of the survey is
    /// what makes flow-versus-field divergence inexpressible.</para>
    ///
    /// <para>Effect count follows the operator's laziness class, which the return type
    /// discloses: a buffer is a deferred-once capture (Tree.Lazy pins the build to the first
    /// treenumerator acquisition), so the effects fire ONCE per operator instance, at first
    /// drain -- replays never re-fire. Re-running against mutated state is a fresh expression
    /// (or <c>Tree.Defer</c>, the disclosed freshness vocabulary). Like <c>Do</c>, this
    /// operator is a composition barrier: nothing may fuse across the declared effect point.</para>
    ///
    /// <para>Rides the pure operator's shared dispatch pass and is STRICTLY CHEAPER than it:
    /// pass-through needs no result storage of its own -- the returned buffer reuses the
    /// capture's value and subtree-size arrays as-is.</para>
    /// </summary>
    public static ITreenumerableBuffer<TSource> RootfixDoDispatch<TSource, TDispatch>(
      this IDepthFirstTreenumerable<TSource> source,
      TDispatch seed,
      Action<TSource, TDispatch, DispatchTargets<TSource, TDispatch>> survey,
      Action<TSource, TDispatch> store)
      => RootfixDoDispatch(source, _ => seed, survey, store);

    /// <summary>
    /// The forest-correct seeding form: every root's arrival comes from
    /// <paramref name="rootNodeSelector"/>, so each tree of a forest seeds independently.
    /// On the Do tier the selector is also the FRESHNESS form (the seed-semantics-follow-purity
    /// rule): it runs during the build, so a closure reads live state at effect time.
    /// </summary>
    public static ITreenumerableBuffer<TSource> RootfixDoDispatch<TSource, TDispatch>(
      this IDepthFirstTreenumerable<TSource> source,
      Func<TSource, TDispatch> rootNodeSelector,
      Action<TSource, TDispatch, DispatchTargets<TSource, TDispatch>> survey,
      Action<TSource, TDispatch> store)
      => new TreenumerableBuffer<TSource>(
        Tree.Lazy(() => PreorderRootfixDoDispatch(source, (node, _) => rootNodeSelector(node), survey, store)), BufferLayout.Preorder);

    /// <summary>The positional selector flavor (the Select/Where arity-split grammar): the root's value and its position -- seeding by root ordinal.</summary>
    public static ITreenumerableBuffer<TSource> RootfixDoDispatch<TSource, TDispatch>(
      this IDepthFirstTreenumerable<TSource> source,
      Func<TSource, NodePosition, TDispatch> rootNodeSelector,
      Action<TSource, TDispatch, DispatchTargets<TSource, TDispatch>> survey,
      Action<TSource, TDispatch> store)
      => new TreenumerableBuffer<TSource>(
        Tree.Lazy(() => PreorderRootfixDoDispatch(source, rootNodeSelector, survey, store)), BufferLayout.Preorder);

    /// <summary>
    /// The breadth-first-only source overload -- the disclosure rule's escalation, mirrored
    /// from the pure operator: the pass runs depth-first, so the source is captured and the
    /// pass runs over the capture's depth-first replay.
    /// </summary>
    public static ITreenumerableBuffer<TSource> RootfixDoDispatch<TSource, TDispatch>(
      this IBreadthFirstTreenumerable<TSource> source,
      TDispatch seed,
      Action<TSource, TDispatch, DispatchTargets<TSource, TDispatch>> survey,
      Action<TSource, TDispatch> store)
      => RootfixDoDispatch(source, _ => seed, survey, store);

    public static ITreenumerableBuffer<TSource> RootfixDoDispatch<TSource, TDispatch>(
      this IBreadthFirstTreenumerable<TSource> source,
      Func<TSource, TDispatch> rootNodeSelector,
      Action<TSource, TDispatch, DispatchTargets<TSource, TDispatch>> survey,
      Action<TSource, TDispatch> store)
      => new TreenumerableBuffer<TSource>(
        Tree.Lazy(() => PreorderRootfixDoDispatchBreadthFirstSource(source, (node, _) => rootNodeSelector(node), survey, store)), BufferLayout.Preorder);

    public static ITreenumerableBuffer<TSource> RootfixDoDispatch<TSource, TDispatch>(
      this IBreadthFirstTreenumerable<TSource> source,
      Func<TSource, NodePosition, TDispatch> rootNodeSelector,
      Action<TSource, TDispatch, DispatchTargets<TSource, TDispatch>> survey,
      Action<TSource, TDispatch> store)
      => new TreenumerableBuffer<TSource>(
        Tree.Lazy(() => PreorderRootfixDoDispatchBreadthFirstSource(source, rootNodeSelector, survey, store)), BufferLayout.Preorder);

    /// <summary>Disambiguation overloads for full trees; keep the depth-first consumption.</summary>
    public static ITreenumerableBuffer<TSource> RootfixDoDispatch<TSource, TDispatch>(
      this ITreenumerable<TSource> source,
      TDispatch seed,
      Action<TSource, TDispatch, DispatchTargets<TSource, TDispatch>> survey,
      Action<TSource, TDispatch> store)
      => RootfixDoDispatch((IDepthFirstTreenumerable<TSource>)source, seed, survey, store);

    public static ITreenumerableBuffer<TSource> RootfixDoDispatch<TSource, TDispatch>(
      this ITreenumerable<TSource> source,
      Func<TSource, TDispatch> rootNodeSelector,
      Action<TSource, TDispatch, DispatchTargets<TSource, TDispatch>> survey,
      Action<TSource, TDispatch> store)
      => RootfixDoDispatch((IDepthFirstTreenumerable<TSource>)source, rootNodeSelector, survey, store);

    public static ITreenumerableBuffer<TSource> RootfixDoDispatch<TSource, TDispatch>(
      this ITreenumerable<TSource> source,
      Func<TSource, NodePosition, TDispatch> rootNodeSelector,
      Action<TSource, TDispatch, DispatchTargets<TSource, TDispatch>> survey,
      Action<TSource, TDispatch> store)
      => RootfixDoDispatch((IDepthFirstTreenumerable<TSource>)source, rootNodeSelector, survey, store);

    private static ITreenumerable<TSource> PreorderRootfixDoDispatch<TSource, TDispatch>(
      IDepthFirstTreenumerable<TSource> source,
      Func<TSource, NodePosition, TDispatch> rootNodeSelector,
      Action<TSource, TDispatch, DispatchTargets<TSource, TDispatch>> survey,
      Action<TSource, TDispatch> store)
    {
      var stored = new LazyPreorderStore<TSource>(
        () => BuildRootfixDoDispatch(source, rootNodeSelector, survey, store));

      return new PreorderTreenumerable<TSource, LazyPreorderStore<TSource>>(stored);
    }

    private static ITreenumerable<TSource> PreorderRootfixDoDispatchBreadthFirstSource<TSource, TDispatch>(
      IBreadthFirstTreenumerable<TSource> source,
      Func<TSource, NodePosition, TDispatch> rootNodeSelector,
      Action<TSource, TDispatch, DispatchTargets<TSource, TDispatch>> survey,
      Action<TSource, TDispatch> store)
    {
      var stored = new LazyPreorderStore<TSource>(
        () => BuildRootfixDoDispatchFromBreadthFirst(source, rootNodeSelector, survey, store));

      return new PreorderTreenumerable<TSource, LazyPreorderStore<TSource>>(stored);
    }

    private static PreorderArrayStore<TSource> BuildRootfixDoDispatchFromBreadthFirst<TSource, TDispatch>(
      IBreadthFirstTreenumerable<TSource> source,
      Func<TSource, NodePosition, TDispatch> rootNodeSelector,
      Action<TSource, TDispatch, DispatchTargets<TSource, TDispatch>> survey,
      Action<TSource, TDispatch> store)
    {
      var capture = source.Materialize();

      return BuildRootfixDoDispatch(capture, rootNodeSelector, survey, store);
    }

    // The Do finisher over the shared dispatch pass: where the pure build zips each
    // (value, arrival) pair into its decoration, this one hands the same pair to store --
    // preorder order, exactly once per node -- and the result reuses the capture's own arrays:
    // pass-through needs no storage of its own.
    private static PreorderArrayStore<TSource> BuildRootfixDoDispatch<TSource, TDispatch>(
      IDepthFirstTreenumerable<TSource> source,
      Func<TSource, NodePosition, TDispatch> rootNodeSelector,
      Action<TSource, TDispatch, DispatchTargets<TSource, TDispatch>> survey,
      Action<TSource, TDispatch> store)
    {
      var (values, subtreeSizes, arrivals) = RunRootfixDispatchPass(source, rootNodeSelector, survey);

      for (var nodeIndex = 0; nodeIndex < values.Length; nodeIndex++)
        store(values[nodeIndex], arrivals[nodeIndex]);

      return new PreorderArrayStore<TSource>(values, subtreeSizes);
    }
  }
}
