// <auto-generated>
//   Generated from AsyncTreenumerable.Invert.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Treenumerables;
using Copse.Treenumerators;
using Copse.Core;
using Copse.Linq.Treenumerables;
using Copse.Linq.Treenumerators;
using System.Collections.Generic;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>
    /// Mirror: reverse the order of every node's children (and the roots). Two regimes, by what
    /// the source can afford (see TRAVERSAL_DIMENSION_SPLIT.md), mirroring the sync operator:
    /// a breadth-first-ONLY source streams its mirror in O(width) and stays narrow; anything
    /// else captures and returns a completed <see cref="IAsyncTreenumerableBuffer{TValue}"/>.
    ///
    /// <para>This overload is the streaming regime: reversing every sibling group reverses each
    /// level end-to-end, so no capture is needed and the result stays a narrow breadth-first
    /// treenumerable.</para>
    /// </summary>
    public static IBreadthFirstTreenumerable<TNode> Invert<TNode>(this IBreadthFirstTreenumerable<TNode> source)
      => new LevelOrderStreamTreenumerable<TNode, InvertedLevelOrderStream<TNode>>(
        () => new InvertedLevelOrderStream<TNode>(source.GetBreadthFirstTreenumerator()));

    /// <summary>
    /// The depth-first-only mirror cannot stream (the mirror owes the original's LAST child right
    /// after the root), so it captures: one awaited depth-first walk into mirrored preorder
    /// arrays, deferred to the first replay pull (async cannot defer inside a sync-signature
    /// treenumerator factory, so the deferral rides the lazy-built store's grow seam -- one step
    /// LAZIER than the sync twin, which captures at call time). The O(n) is disclosed by the
    /// buffer return type.
    /// </summary>
    public static ITreenumerableBuffer<TNode> Invert<TNode>(this IDepthFirstTreenumerable<TNode> source)
      => DeferredMirror(source);

    /// <summary>
    /// The full-source convenience overload (also the disambiguator for a source that is both
    /// breadth- and depth-first): capture, then serve the mirror from the capture.
    /// </summary>
    public static ITreenumerableBuffer<TNode> Invert<TNode>(this ITreenumerable<TNode> source)
      => DeferredMirror(source);

    /// <summary>
    /// The buffer overload: a capture in hand makes the mirror's depth-first dimension affordable,
    /// so the mirror is a full citizen -- returned as a completed buffer (the mirror owns fresh
    /// arrays; there is no live feed, so the non-disposable base). Built once, on the first replay
    /// pull, by walking the capture's depth-first replay into mirrored preorder arrays; the
    /// original source is never re-enumerated.
    /// </summary>
    public static ITreenumerableBuffer<TNode> Invert<TNode>(this ITreenumerableBuffer<TNode> source)
      => DeferredMirror(source);

    private static ITreenumerableBuffer<TNode> DeferredMirror<TNode>(IDepthFirstTreenumerable<TNode> source)
    {
      var mirror = new LazyBuiltPreorderStore<TNode>(() => BuildMirror(source));

      return new CompletedTreenumerableBuffer<TNode>(
        new DelegatingTreenumerable<TNode>(
          () => new PreorderStoreBreadthFirstTreenumerator<TNode, LazyBuiltPreorderStore<TNode>>(mirror),
          () => new PreorderStoreDepthFirstTreenumerator<TNode, LazyBuiltPreorderStore<TNode>>(mirror)));
    }

    private static PreorderArrayStore<TNode> BuildMirror<TNode>(IDepthFirstTreenumerable<TNode> source)
    {
      // 1. Capture flat preorder arrays (value + subtree size per node) from one awaited
      //    depth-first walk of the source.
      var values = new List<TNode>();
      var subtreeSizes = new List<int>();
      var open = new Stack<int>();

      var treenumerator = source.GetDepthFirstTreenumerator();
      using (treenumerator)
      {
        while (treenumerator.MoveNext(NodeTraversalStrategies.TraverseAll))
        {
          if (treenumerator.Mode != TreenumeratorMode.SchedulingNode)
            continue;

          while (open.Count > treenumerator.Position.Depth)
          {
            var closed = open.Pop();
            subtreeSizes[closed] = values.Count - closed;
          }

          open.Push(values.Count);
          values.Add(treenumerator.Node);
          subtreeSizes.Add(0);
        }
      }

      while (open.Count > 0)
      {
        var closed = open.Pop();
        subtreeSizes[closed] = values.Count - closed;
      }

      // 2. Emit the mirror. Pushing roots/children in forward order makes them pop in reverse,
      //    which is exactly the mirror's preorder. Each subtree keeps its size; only ordering
      //    changes.
      var count = values.Count;
      var mirroredValues = new TNode[count];
      var mirroredSubtreeSizes = new int[count];
      var stack = new Stack<int>();

      for (var root = 0; root < count; root += subtreeSizes[root])
        stack.Push(root);

      var output = 0;

      while (stack.Count > 0)
      {
        var index = stack.Pop();

        mirroredValues[output] = values[index];
        mirroredSubtreeSizes[output] = subtreeSizes[index];
        output++;

        var end = index + subtreeSizes[index];

        for (var child = index + 1; child < end; child += subtreeSizes[child])
          stack.Push(child);
      }

      return new PreorderArrayStore<TNode>(mirroredValues, mirroredSubtreeSizes);
    }
  }
}
