// <auto-generated>
//   Generated from AsyncTreenumerable.TakeLastTrees.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using System;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>
    /// Keeps only the last <paramref name="count"/> root trees. Awaits a root count first (the source
    /// is enumerated once to count, then again to skip), so it is a void-returning terminal-builder.
    /// </summary>
    public static ITreenumerable<TNode> TakeLastTrees<TNode>(
      this ITreenumerable<TNode> source,
      int count)
    {
      var treeCount = source.CountTrees();

      var skipCount = Math.Max(treeCount - count, 0);

      return source.SkipTrees(skipCount);
    }

    /// <summary>The depth-first-narrow twin: the same two passes (count the roots, then skip), staying narrow.</summary>
    public static IDepthFirstTreenumerable<TNode> TakeLastTrees<TNode>(
      this IDepthFirstTreenumerable<TNode> source,
      int count)
    {
      var treeCount = source.CountTrees();

      var skipCount = Math.Max(treeCount - count, 0);

      return source.SkipTrees(skipCount);
    }

    /// <summary>
    /// The breadth-first-narrow twin. The counting pass is nearly free in this dimension: the
    /// roots are the whole of level 0, so it drains one level and pulls nothing deeper.
    /// </summary>
    public static IBreadthFirstTreenumerable<TNode> TakeLastTrees<TNode>(
      this IBreadthFirstTreenumerable<TNode> source,
      int count)
    {
      var treeCount = source.CountTrees();

      var skipCount = Math.Max(treeCount - count, 0);

      return source.SkipTrees(skipCount);
    }
  }
}
