// <auto-generated>
//   Generated from AsyncTreenumerable.ToFormattedString.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using System;
using System.Collections.Generic;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>The tree rendered as a single box-drawing string (lines joined by the platform newline).</summary>
    public static string ToFormattedString<TNode>(this IDepthFirstTreenumerable<TNode> source)
    {
      return source.ToFormattedString(node => node.ToString(), 0);
    }

    /// <summary>The tree rendered as a single box-drawing string with the given branch padding width.</summary>
    public static string ToFormattedString<TNode>(
      this IDepthFirstTreenumerable<TNode> source,
      int paddingSize)
    {
      return source.ToFormattedString(node => node.ToString(), paddingSize);
    }

    /// <summary>The tree rendered as a single box-drawing string with a custom node formatter and branch padding.</summary>
    public static string ToFormattedString<TNode>(
      this IDepthFirstTreenumerable<TNode> source,
      Func<TNode, string> stringFormatter,
      int paddingSize)
    {
      var lines = new List<string>();
      foreach (var line in source.ToFormattedLines(stringFormatter, paddingSize))
      {
        lines.Add(line);
      }

      return string.Join(Environment.NewLine, lines);
    }
  }
}
