// <auto-generated>
//   Generated from AsyncTreenumerable.Do.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Linq.Treenumerators;
using System;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>
    /// Async <c>Do</c>: runs a side effect on every emitted visit, forwarding the visit stream
    /// unchanged. Deferred (the effect runs during enumeration, once per <c>MoveNextAsync</c>).
    /// </summary>
    public static ITreenumerable<TNode> Do<TNode>(
      this ITreenumerable<TNode> source,
      Action<NodeVisit<TNode>> onNext)
    {
      if (onNext == null)
        return source;

      return
        TreenumerableFactory
        .Create(
          () => new DoTreenumerator<TNode>(source.GetBreadthFirstTreenumerator, onNext),
          () => new DoTreenumerator<TNode>(source.GetDepthFirstTreenumerator, onNext));
    }

    public static IDepthFirstTreenumerable<TNode> Do<TNode>(
      this IDepthFirstTreenumerable<TNode> source,
      Action<NodeVisit<TNode>> onNext)
    {
      if (onNext == null)
        return source;

      return
        TreenumerableFactory.CreateDepthFirst(
          () => new DoTreenumerator<TNode>(source.GetDepthFirstTreenumerator, onNext));
    }

    public static IBreadthFirstTreenumerable<TNode> Do<TNode>(
      this IBreadthFirstTreenumerable<TNode> source,
      Action<NodeVisit<TNode>> onNext)
    {
      if (onNext == null)
        return source;

      return
        TreenumerableFactory.CreateBreadthFirst(
          () => new DoTreenumerator<TNode>(source.GetBreadthFirstTreenumerator, onNext));
    }
  }
}
