// <auto-generated>
//   Generated from AsyncTreenumerable.Union.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Linq.Treenumerators;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>
    /// Async <c>Union</c>: the structural merge of two trees by position -- each merged node carries
    /// whichever side(s) have a node at that position. The engine behind the other set ops. Deferred.
    /// </summary>
    public static ITreenumerable<MergeNode<TLeft, TRight>> Union<TLeft, TRight>(
      this ITreenumerable<TLeft> leftTreenumerable,
      ITreenumerable<TRight> rightTreenumerable)
      => TreenumerableFactory.Create(
        () => new StructuralMergeBreadthFirstTreenumerator<TLeft, TRight>(
          leftTreenumerable.GetBreadthFirstTreenumerator,
          rightTreenumerable.GetBreadthFirstTreenumerator),
        () => new StructuralMergeDepthFirstTreenumerator<TLeft, TRight>(
          leftTreenumerable.GetDepthFirstTreenumerator,
          rightTreenumerable.GetDepthFirstTreenumerator));

    public static IDepthFirstTreenumerable<MergeNode<TLeft, TRight>> Union<TLeft, TRight>(
      this IDepthFirstTreenumerable<TLeft> leftTreenumerable,
      IDepthFirstTreenumerable<TRight> rightTreenumerable)
      => TreenumerableFactory.CreateDepthFirst(
        () => new StructuralMergeDepthFirstTreenumerator<TLeft, TRight>(
          leftTreenumerable.GetDepthFirstTreenumerator,
          rightTreenumerable.GetDepthFirstTreenumerator));

    public static IBreadthFirstTreenumerable<MergeNode<TLeft, TRight>> Union<TLeft, TRight>(
      this IBreadthFirstTreenumerable<TLeft> leftTreenumerable,
      IBreadthFirstTreenumerable<TRight> rightTreenumerable)
      => TreenumerableFactory.CreateBreadthFirst(
        () => new StructuralMergeBreadthFirstTreenumerator<TLeft, TRight>(
          leftTreenumerable.GetBreadthFirstTreenumerator,
          rightTreenumerable.GetBreadthFirstTreenumerator));
  }
}
