// <auto-generated>
//   Generated from AsyncTreenumerable.LeaffixDispatch.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Stores;
using Copse.Treenumerables;
using Copse.Treenumerators;
using Copse.Core;
using Copse.Linq.Treenumerables;
using Copse.Linq.Stores;
using Copse.Linq.Treenumerators;
using Copse.Linq.Extensions;
using System;
using System.Collections.Generic;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>
    /// The sibling-complete tier of the leaffix pair: every node gets an accumulated value --
    /// leaves from <paramref name="leafNodeSelector"/>, internal nodes from
    /// <paramref name="survey"/>, which sees ALL of its children's accumulated values at once
    /// through the no-copy <see cref="ChildAccumulations{TAccumulate}"/> view (subtree-span
    /// hops, zero per-node allocation). Sibling-complete visibility is the point -- median of
    /// children, top-k, anything that must compare children to each other, and boundary-only
    /// contributions like leaf count; a fold that only needs one child at a time belongs to
    /// LeaffixScan (sugar over this operator). The result tree has the same shape as the
    /// source. This is the upward dual of RootfixScan: the survey runs once per node receiving
    /// everything that arrives (n children up, versus one parent value down), and the boundary
    /// where nothing arrives -- leaves -- takes <paramref name="leafNodeSelector"/> (or the
    /// fixed <c>seed</c> overload), mirroring rootfix's rootNodeSelector/seed pair.
    ///
    /// <para>Callbacks run during the deferred build, once per node; the view enumerates
    /// children in sibling order. Invocation timing relative to the source walk is not
    /// specified, so callbacks should be pure.</para>
    ///
    /// <para>Returns an <see cref="IAsyncTreenumerableBuffer{TValue}"/> because LeaffixDispatch
    /// MANUFACTURES owned O(n) storage: the surveyed accumulations are new values that exist
    /// nowhere in the source, and a root's value IS its whole subtree's aggregate -- the source
    /// is fully consumed before the first result visit can be published, so the result is a
    /// completed capture, not a lazy stream. Deferred (hence the sync name): construction is
    /// pinned to the first treenumerator acquisition (Tree.Lazy), and the awaited build runs
    /// ONCE, on the first replay pull, through the lazy-built store's grow seam. The source is
    /// consumed depth-first only, so a streamed narrow source can leaffix.</para>
    ///
    /// <para>Single forward DFS pass into flat pre-order arrays; see the sync operator for the
    /// construction notes (subtree-size hop, O(depth) working set).</para>
    /// </summary>
    public static ITreenumerableBuffer<TAccumulate> LeaffixDispatch<TSource, TAccumulate>(
      this IDepthFirstTreenumerable<TSource> source,
      Func<NodeContext<TSource>, TAccumulate> leafNodeSelector,
      Func<NodeContext<TSource>, ChildAccumulations<TAccumulate>, TAccumulate> survey)
      => new TreenumerableBuffer<TAccumulate>(
        Tree.Lazy(() => PreorderDispatch(source, leafNodeSelector, survey)), BufferLayout.Preorder);

    /// <summary>
    /// The breadth-first-only source overload -- the DISCLOSURE RULE's escalation written once,
    /// here, instead of at every call site: a leaffix survey runs in depth-first subtree-close
    /// order, which a level-order arrival cannot provide, so the source is captured (the same
    /// O(n) every LeaffixDispatch pays, disclosed by the buffer return type) and the survey runs
    /// over the capture's depth-first replay.
    /// </summary>
    public static ITreenumerableBuffer<TAccumulate> LeaffixDispatch<TSource, TAccumulate>(
      this IBreadthFirstTreenumerable<TSource> source,
      Func<NodeContext<TSource>, TAccumulate> leafNodeSelector,
      Func<NodeContext<TSource>, ChildAccumulations<TAccumulate>, TAccumulate> survey)
      => new TreenumerableBuffer<TAccumulate>(
        Tree.Lazy(() => PreorderDispatchBreadthFirstSource(source, leafNodeSelector, survey)), BufferLayout.Preorder);

    /// <summary>Disambiguation overload for full trees; keeps the historical depth-first consumption.</summary>
    public static ITreenumerableBuffer<TAccumulate> LeaffixDispatch<TSource, TAccumulate>(
      this ITreenumerable<TSource> source,
      Func<NodeContext<TSource>, TAccumulate> leafNodeSelector,
      Func<NodeContext<TSource>, ChildAccumulations<TAccumulate>, TAccumulate> survey)
      => LeaffixDispatch((IDepthFirstTreenumerable<TSource>)source, leafNodeSelector, survey);

    /// <summary>
    /// The fixed-seed form -- RootfixScan's constant-seed overload, mirrored: every leaf starts
    /// the accumulation at <paramref name="seed"/>. The canonical use is boundary-only
    /// contribution, e.g. leaf count (seed 1, survey sums children).
    /// </summary>
    public static ITreenumerableBuffer<TAccumulate> LeaffixDispatch<TSource, TAccumulate>(
      this IDepthFirstTreenumerable<TSource> source,
      TAccumulate seed,
      Func<NodeContext<TSource>, ChildAccumulations<TAccumulate>, TAccumulate> survey)
      => LeaffixDispatch(source, _ => seed, survey);

    public static ITreenumerableBuffer<TAccumulate> LeaffixDispatch<TSource, TAccumulate>(
      this IBreadthFirstTreenumerable<TSource> source,
      TAccumulate seed,
      Func<NodeContext<TSource>, ChildAccumulations<TAccumulate>, TAccumulate> survey)
      => LeaffixDispatch(source, _ => seed, survey);

    public static ITreenumerableBuffer<TAccumulate> LeaffixDispatch<TSource, TAccumulate>(
      this ITreenumerable<TSource> source,
      TAccumulate seed,
      Func<NodeContext<TSource>, ChildAccumulations<TAccumulate>, TAccumulate> survey)
      => LeaffixDispatch((IDepthFirstTreenumerable<TSource>)source, _ => seed, survey);

    // Preorder for BOTH dimensions, deliberately: pinning a level-order layout on a
    // breadth-first-first pull (Tree.Lazy's dimension dispatch, one transpose pass into
    // LevelOrderArrayStore) was built and MEASURED OUT -- over raw array stores the
    // breadth-first cross-decode tax is only ~1.08x (the Memoize replay rows' 1.53x is
    // memo-store overhead, not layout), so the transpose plus transient double storage
    // needs ~5 replays to break even and taxes the common single-drain case ~8%.
    private static ITreenumerable<TAccumulate> PreorderDispatch<TSource, TAccumulate>(
      IDepthFirstTreenumerable<TSource> source,
      Func<NodeContext<TSource>, TAccumulate> leafNodeSelector,
      Func<NodeContext<TSource>, ChildAccumulations<TAccumulate>, TAccumulate> survey)
    {
      var surveyed = new LazyPreorderStore<TAccumulate>(
        () => BuildLeaffixDispatch(source, leafNodeSelector, survey));

      return new PreorderTreenumerable<TAccumulate, LazyPreorderStore<TAccumulate>>(surveyed);
    }

    private static ITreenumerable<TAccumulate> PreorderDispatchBreadthFirstSource<TSource, TAccumulate>(
      IBreadthFirstTreenumerable<TSource> source,
      Func<NodeContext<TSource>, TAccumulate> leafNodeSelector,
      Func<NodeContext<TSource>, ChildAccumulations<TAccumulate>, TAccumulate> survey)
    {
      var surveyed = new LazyPreorderStore<TAccumulate>(
        () => BuildLeaffixDispatchFromBreadthFirst(source, leafNodeSelector, survey));

      return new PreorderTreenumerable<TAccumulate, LazyPreorderStore<TAccumulate>>(surveyed);
    }

    private static PreorderArrayStore<TAccumulate> BuildLeaffixDispatchFromBreadthFirst<TSource, TAccumulate>(
      IBreadthFirstTreenumerable<TSource> source,
      Func<NodeContext<TSource>, TAccumulate> leafNodeSelector,
      Func<NodeContext<TSource>, ChildAccumulations<TAccumulate>, TAccumulate> survey)
    {
      var capture = source.Materialize();

      return BuildLeaffixDispatch(capture, leafNodeSelector, survey);
    }

    private static PreorderArrayStore<TAccumulate> BuildLeaffixDispatch<TSource, TAccumulate>(
      IDepthFirstTreenumerable<TSource> source,
      Func<NodeContext<TSource>, TAccumulate> leafNodeSelector,
      Func<NodeContext<TSource>, ChildAccumulations<TAccumulate>, TAccumulate> survey)
    {
      var accumulations = new List<TAccumulate>();
      var subtreeSizes = new List<int>();
      var path = new Stack<PendingNode<TSource>>(); // open ancestors of the current node

      void Close()
      {
        var pending = path.Pop();
        var index = pending.Index;

        subtreeSizes[index] = accumulations.Count - index;
        accumulations[index] =
          subtreeSizes[index] == 1
          ? leafNodeSelector(pending.Context)
          : survey(pending.Context, new ChildAccumulations<TAccumulate>(accumulations, subtreeSizes, index));
      }

      var treenumerator = source.GetDepthFirstTreenumerator();
      using (treenumerator)
      {
        while (treenumerator.MoveNext(NodeTraversalStrategies.TraverseAll))
        {
          if (treenumerator.Mode != TreenumeratorMode.SchedulingNode)
            continue;

          // Returning to this depth (or shallower) means every deeper open node is complete.
          while (path.Count > treenumerator.Position.Depth)
            Close();

          path.Push(new PendingNode<TSource>(accumulations.Count, treenumerator.ToNodeContext()));
          accumulations.Add(default); // backfilled when this node closes
          subtreeSizes.Add(0);
        }
      }

      while (path.Count > 0)
        Close();

      return new PreorderArrayStore<TAccumulate>(accumulations.ToArray(), subtreeSizes.ToArray());
    }
  }
}
