// <auto-generated>
//   Generated from AsyncBreadthFirstTreenumerator.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Traversal;
using System;
using System.Collections.Generic;

namespace Copse.Treenumerators
{
  /// <summary>
  /// Breadth-first <b>async</b> treenumerator: the direct-style async port of
  /// <c>Copse.Treenumerators.BreadthFirstTreenumerator</c>, over the shared
  /// <see cref="BreadthFirstPathState{TNode, TEnumerator}"/>, with the child/root pulls awaited.
  ///
  /// <para><b>The BFS engine's async wrinkle.</b> The sync driver's seam is
  /// <c>TryScheduleNextChildOf(ref BreadthFirstFrame parent)</c> -- a <b>ref parameter</b> -- and it
  /// binds <c>ref var front = ref _Path.Front</c> -- a <b>ref local</b>. Both are illegal in async
  /// methods. So the single ref-parameter seam splits into two parameterless awaited seams (one over the
  /// schedule-stack top, one over the queue front) and the ref-local front is inlined as repeated
  /// <c>_Path.Front</c> access (semantically identical -- Front returns a ref to the same slot). This is
  /// the one restructuring the async port imposes on the engines; everything else mirrors the sync driver.</para>
  /// </summary>
  public sealed class BreadthFirstTreenumerator<TValue, TNode, TChildEnumerator>
    : ITreenumerator<TValue>
    where TChildEnumerator : IChildCursor<TNode>
  {
    public BreadthFirstTreenumerator(
      IEnumerable<TNode> rootNodes,
      Func<NodeContext<TNode>, TChildEnumerator> childEnumeratorFactory,
      Func<TNode, TValue> map)
    {
      _RootsEnumerator = rootNodes.GetEnumerator();
      _Path = new BreadthFirstPathState<TNode, TChildEnumerator>(childEnumeratorFactory);
      _Map = map;
    }

    private readonly IEnumerator<TNode> _RootsEnumerator;
    private BreadthFirstPathState<TNode, TChildEnumerator> _Path;
    private readonly Func<TNode, TValue> _Map;

    private bool _Finished;
    private bool _RootsEnumeratorFinished = false;
    private bool _RootsScheduled = false;

    public TValue Node { get; private set; } = default;
    public int VisitCount { get; private set; } = 0;
    public TreenumeratorMode Mode { get; private set; } = default;
    public NodePosition Position { get; private set; } = NodePosition.ForestRoot;

    public bool MoveNext(NodeTraversalStrategies nodeTraversalStrategies)
    {
      if (_Finished)
        return false;

      if (Mode == TreenumeratorMode.SchedulingNode && _Path.HasScheduledNode)
        ApplyStrategy(nodeTraversalStrategies);

      var moved = Advance();

      if (!moved)
        _Finished = true;

      return moved;
    }

    private bool Advance()
    {
      while (true)
      {
        // 1) Descend: schedule the next child of the schedule-stack top.
        if (_Path.HasScheduledNode)
        {
          if (TryScheduleNextChildOfScheduleTop())
            return true;

          _Path.PopScheduleStack();
          continue;
        }

        // 2) Schedule the next root.
        if (!_RootsScheduled)
        {
          if (TryScheduleNextRoot())
            return true;

          _RootsScheduled = true;
          _Path.ClearSlotCarry();
          continue;
        }

        if (_Path.QueueIsEmpty)
          return false;

        // 3) Visit the active parent (queue front) and drive its children. Inlines _Path.Front.
        if (_Path.Front.VisitCount == 0)
        {
          _Path.Front.VisitCount = 1;
          Publish(ref _Path.Front);
          return true;
        }

        if (_Path.FrontSlotEnqueuedNode)
        {
          _Path.ClearSlotCarry();
          _Path.Front.VisitCount++;
          Publish(ref _Path.Front);
          return true;
        }

        if (TryScheduleNextChildOfFront())
          return true;

        _Path.RetireFront();
      }
    }

    private void ApplyStrategy(NodeTraversalStrategies nodeTraversalStrategies)
    {
      if (nodeTraversalStrategies.HasNodeTraversalStrategies(NodeTraversalStrategies.SkipSiblings))
        if (_Path.SkipRemainingSiblings())
          _RootsEnumeratorFinished = true;

      if (nodeTraversalStrategies.HasNodeTraversalStrategies(NodeTraversalStrategies.SkipNodeAndDescendants))
      {
        _Path.PopScheduleStack();
        return;
      }

      if (nodeTraversalStrategies.HasNodeTraversalStrategies(NodeTraversalStrategies.SkipNode))
        return;

      if (nodeTraversalStrategies.HasNodeTraversalStrategies(NodeTraversalStrategies.SkipDescendants))
        _Path.DisposeScheduleTopEnumerator();

      _Path.AcceptScheduledNode();
    }

    // THE SEAM (schedule-stack top): awaited child pull. Reads the parent (ScheduleTop) inline instead
    // of via a ref parameter, which async methods forbid.
    private bool TryScheduleNextChildOfScheduleTop()
    {
      var result = _Path.ScheduleTop.ChildEnumerator.MoveNext();
      if (!result.HasChild)
        return false;

      Publish(ref _Path.PushScheduledChild(_Path.ScheduleTop.Position.Depth, result.Child.Node, result.Child.SiblingIndex));
      return true;
    }

    // THE SEAM (queue front): awaited child pull.
    private bool TryScheduleNextChildOfFront()
    {
      var result = _Path.Front.ChildEnumerator.MoveNext();
      if (!result.HasChild)
        return false;

      Publish(ref _Path.PushScheduledChild(_Path.Front.Position.Depth, result.Child.Node, result.Child.SiblingIndex));
      return true;
    }

    private bool TryScheduleNextRoot()
    {
      if (_RootsEnumeratorFinished || !_RootsEnumerator.MoveNext())
        return false;

      Publish(ref _Path.PushScheduledRoot(_RootsEnumerator.Current));
      return true;
    }

    private void Publish(ref BreadthFirstFrame<TNode, TChildEnumerator> frame)
    {
      Mode = frame.VisitCount == 0 ? TreenumeratorMode.SchedulingNode : TreenumeratorMode.VisitingNode;
      Node = _Map(frame.Node);
      VisitCount = frame.VisitCount;
      Position = frame.Position;
    }

    public void Dispose()
    {
      _Path.Dispose();
      _RootsEnumerator.Dispose();
    }
  }
}
