// <auto-generated>
//   Generated from AsyncBreadthFirstTreenumerator.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Traversal;
using System;
using System.Collections.Generic;

namespace Copse.Treenumerators
{
  /// <summary>
  /// Breadth-first <b>async</b> treenumerator: the direct-style async port of the original
  /// hand-written sync engine, over the shared
  /// <see cref="BreadthFirstPathState{TNode, TEnumerator}"/>, with the child/root pulls PROBED
  /// so a pull that completes inline costs no state machine at all (the fast-path probe idiom --
  /// see AsyncToSync).
  ///
  /// <para><b>The BFS engine's async wrinkle.</b> The original sync driver's seam was
  /// <c>TryScheduleNextChildOf(ref BreadthFirstFrame parent)</c> -- a <b>ref parameter</b> -- and it
  /// bound <c>ref var front = ref _Path.Front</c> -- a <b>ref local</b>. Both are illegal in the async
  /// continuations a pending pull resumes through. So the single ref-parameter seam splits into two
  /// parameterless probed seams (one over the schedule-stack top, one over the queue front) and the
  /// ref-local front is inlined as repeated <c>_Path.Front</c> access (semantically identical -- Front
  /// returns a ref to the same slot). This is the one restructuring the async port imposes on the
  /// engines; everything else mirrors the original sync driver.</para>
  /// </summary>
  public sealed class BreadthFirstTreenumerator<TValue, TNode, TChildEnumerator>
    : ITreenumerator<TValue>
    where TChildEnumerator : IChildEnumerator<TNode>
  {
    public BreadthFirstTreenumerator(
      IEnumerable<TNode> rootNodes,
      Func<NodeContext<TNode>, TChildEnumerator> childEnumeratorFactory,
      Func<TNode, TValue> map)
    {
      _RootsEnumerator = rootNodes.GetEnumerator();
      _Path = new BreadthFirstPathState<TNode, TChildEnumerator>(childEnumeratorFactory);
      _Map = map;
    }

    private readonly IEnumerator<TNode> _RootsEnumerator;
    private BreadthFirstPathState<TNode, TChildEnumerator> _Path;
    private readonly Func<TNode, TValue> _Map;

    private bool _Finished;
    private bool _RootsEnumeratorFinished = false;
    private bool _RootsScheduled = false;

    public TValue Node { get; private set; } = default;
    public int VisitCount { get; private set; } = 0;
    public TreenumeratorMode Mode { get; private set; } = default;
    public NodePosition Position { get; private set; } = NodePosition.ForestRoot;

    // NOT async, and neither are the helpers below: every pull is PROBED, and a pull that
    // completes inline stays ordinary method calls with no state machine -- the fast-path probe
    // idiom (see AsyncToSync). A pull ADVANCES its cursor, so a pending pull resumes through a
    // continuation that CONSUMES the pulled result; Advance's loop state lives entirely in
    // fields, so the schedule continuations then perform the loop's between-iteration mutation
    // and re-enter Advance -- exactly its `continue`.
    public bool MoveNext(NodeTraversalStrategies nodeTraversalStrategies)
    {
      if (_Finished)
        return false;

      if (Mode == TreenumeratorMode.SchedulingNode && _Path.HasScheduledNode)
        ApplyStrategy(nodeTraversalStrategies);

      var moved = Advance();

      if (!moved)
        _Finished = true;

      return moved;
    }

    private bool Advance()
    {
      while (true)
      {
        // 1) Descend: schedule the next child of the schedule-stack top.
        if (_Path.HasScheduledNode)
        {
          var scheduled = TryScheduleNextChildOfScheduleTop();

          if (scheduled)
            return true;

          _Path.PopScheduleStack();
          continue;
        }

        // 2) Schedule the next root.
        if (!_RootsScheduled)
        {
          var scheduled = TryScheduleNextRoot();

          if (scheduled)
            return true;

          _RootsScheduled = true;
          _Path.ClearSlotCarry();
          continue;
        }

        if (_Path.QueueIsEmpty)
          return false;

        // 3) Visit the active parent (queue front) and drive its children. Inlines _Path.Front.
        if (_Path.Front.VisitCount == 0)
        {
          _Path.Front.VisitCount = 1;
          Publish(ref _Path.Front);
          return true;
        }

        if (_Path.FrontSlotEnqueuedNode)
        {
          _Path.ClearSlotCarry();
          _Path.Front.VisitCount++;
          Publish(ref _Path.Front);
          return true;
        }

        var frontScheduled = TryScheduleNextChildOfFront();

        if (frontScheduled)
          return true;

        _Path.RetireFront();
      }
    }

    private void ApplyStrategy(NodeTraversalStrategies nodeTraversalStrategies)
    {
      if (nodeTraversalStrategies.HasNodeTraversalStrategies(NodeTraversalStrategies.SkipSiblings))
        if (_Path.SkipRemainingSiblings())
          _RootsEnumeratorFinished = true;

      if (nodeTraversalStrategies.HasNodeTraversalStrategies(NodeTraversalStrategies.SkipNodeAndDescendants))
      {
        _Path.PopScheduleStack();
        return;
      }

      if (nodeTraversalStrategies.HasNodeTraversalStrategies(NodeTraversalStrategies.SkipNode))
        return;

      if (nodeTraversalStrategies.HasNodeTraversalStrategies(NodeTraversalStrategies.SkipDescendants))
        _Path.DisposeScheduleTopEnumerator();

      _Path.AcceptScheduledNode();
    }

    // THE SEAM (schedule-stack top): the child pull, probed. Reads the parent (ScheduleTop) inline
    // instead of via a ref parameter (see the class doc). The pulled result lands through the same
    // consume helper whether the pull answered inline or through the pending continuation.
    private bool TryScheduleNextChildOfScheduleTop()
    {
      var result = _Path.ScheduleTop.ChildEnumerator.MoveNext();

      return TrySchedulePulledChildOfScheduleTop(result);
    }

    // THE SEAM (queue front): the child pull, probed.
    private bool TryScheduleNextChildOfFront()
    {
      var result = _Path.Front.ChildEnumerator.MoveNext();

      return TrySchedulePulledChildOfFront(result);
    }

    private bool TryScheduleNextRoot()
    {
      if (_RootsEnumeratorFinished)
        return false;

      var moved = _RootsEnumerator.MoveNext();

      if (!moved)
        return false;

      Publish(ref _Path.PushScheduledRoot(_RootsEnumerator.Current));
      return true;
    }

    // Land a pulled child under the schedule-stack top; false when the enumerator was exhausted.
    private bool TrySchedulePulledChildOfScheduleTop(ChildResult<TNode> result)
    {
      if (!result.HasChild)
        return false;

      Publish(ref _Path.PushScheduledChild(_Path.ScheduleTop.Position.Depth, result.Child.Node, result.Child.SiblingIndex));
      return true;
    }

    // Land a pulled child under the queue front; false when the enumerator was exhausted.
    private bool TrySchedulePulledChildOfFront(ChildResult<TNode> result)
    {
      if (!result.HasChild)
        return false;

      Publish(ref _Path.PushScheduledChild(_Path.Front.Position.Depth, result.Child.Node, result.Child.SiblingIndex));
      return true;
    }


    private void Publish(ref BreadthFirstFrame<TNode, TChildEnumerator> frame)
    {
      Mode = frame.VisitCount == 0 ? TreenumeratorMode.SchedulingNode : TreenumeratorMode.VisitingNode;
      Node = _Map(frame.Node);
      VisitCount = frame.VisitCount;
      Position = frame.Position;
    }

    public void Dispose()
    {
      _Path.Dispose();
      _RootsEnumerator.Dispose();
    }
  }
}
