// <auto-generated>
//   Generated from AsyncBreadthFirstTreenumerator.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Traversal;
using System;
using System.Collections.Generic;

namespace Copse.Treenumerators
{
  // Direct style over the shared color-agnostic BreadthFirstPathState, with the child/root
  // pulls PROBED so a pull that completes inline costs no state machine at all (the fast-path
  // probe idiom -- see ToSync).
  //
  // The BFS engine's async wrinkle: a ref parameter and a ref local are both illegal in the
  // async continuations a pending pull resumes through, so the sync driver's single
  // ref-parameter seam splits into two parameterless probed seams (one over the schedule-stack
  // top, one over the queue front) and the ref-local front is inlined as repeated _Path.Front
  // access (semantically identical -- Front returns a ref to the same slot). This is the one
  // restructuring the async port imposes on the engines.
  /// <summary>
  /// The breadth-first engine cursor over a hierarchical source: roots from an async stream,
  /// children pulled per node through <typeparamref name="TChildEnumerator"/>. Normally
  /// constructed by <c>Treenumerable</c> rather than directly.
  /// </summary>
  public sealed class BreadthFirstTreenumerator<TNode, THandle, TChildEnumerator>
    : ITreenumerator<TNode>
    where TChildEnumerator : IChildEnumerator<THandle>
  {
    /// <summary>Builds the traversal from the pull topology: the roots, a factory producing
    /// each handle's child enumerator, and the map resolving a handle to its node.</summary>
    public BreadthFirstTreenumerator(
      IEnumerable<THandle> roots,
      Func<NodeContext<THandle>, TChildEnumerator> childEnumeratorFactory,
      Func<THandle, TNode> handleToNodeMap)
    {
      _RootsEnumerator = roots.GetEnumerator();
      _Path = new BreadthFirstPathState<TNode, THandle, TChildEnumerator>(childEnumeratorFactory, handleToNodeMap);

    }

    private readonly IEnumerator<THandle> _RootsEnumerator;
    private BreadthFirstPathState<TNode, THandle, TChildEnumerator> _Path;


    private bool _Finished;
    private bool _RootsEnumeratorFinished = false;
    private bool _RootsScheduled = false;

    /// <inheritdoc/>
    public TNode Node { get; private set; } = default;
    /// <inheritdoc/>
    public int VisitCount { get; private set; } = 0;
    /// <inheritdoc/>
    public TreenumeratorMode Mode { get; private set; } = default;
    /// <inheritdoc/>
    public NodePosition Position { get; private set; } = NodePosition.ForestRoot;

    // NOT async, and neither are the helpers below: every pull is PROBED, and a pull that
    // completes inline stays ordinary method calls with no state machine -- the fast-path probe
    // idiom (see ToSync). A pull ADVANCES its cursor, so a pending pull resumes through a
    // continuation that CONSUMES the pulled result; Advance's loop state lives entirely in
    // fields, so the schedule continuations then perform the loop's between-iteration mutation
    // and re-enter Advance -- exactly its `continue`.
    /// <inheritdoc/>
    public bool MoveNext(NodeTraversalStrategies nodeTraversalStrategies)
    {
      if (_Finished)
        return false;

      if (Mode == TreenumeratorMode.SchedulingNode && _Path.HasScheduledNode)
        ApplyStrategy(nodeTraversalStrategies);

      var moved = Advance();

      if (!moved)
        _Finished = true;

      return moved;
    }

    private bool Advance()
    {
      while (true)
      {
        // 1) Descend: schedule the next child of the schedule-stack top.
        if (_Path.HasScheduledNode)
        {
          var scheduled = TryScheduleNextChildOfScheduleTop();

          if (scheduled)
            return true;

          _Path.PopScheduleStack();
          continue;
        }

        // 2) Schedule the next root.
        if (!_RootsScheduled)
        {
          var scheduled = TryScheduleNextRoot();

          if (scheduled)
            return true;

          _RootsScheduled = true;
          _Path.ClearSlotCarry();
          continue;
        }

        if (_Path.QueueIsEmpty)
          return false;

        // 3) Visit the active parent (queue front) and drive its children. Inlines _Path.Front.
        if (_Path.Front.VisitCount == 0)
        {
          _Path.Front.VisitCount = 1;
          Publish(ref _Path.Front);
          return true;
        }

        if (_Path.FrontSlotEnqueuedNode)
        {
          _Path.ClearSlotCarry();
          _Path.Front.VisitCount++;
          Publish(ref _Path.Front);
          return true;
        }

        var frontScheduled = TryScheduleNextChildOfFront();

        if (frontScheduled)
          return true;

        _Path.RetireFront();
      }
    }

    private void ApplyStrategy(NodeTraversalStrategies nodeTraversalStrategies)
    {
      if (nodeTraversalStrategies.HasNodeTraversalStrategies(NodeTraversalStrategies.PruneSiblings))
        if (_Path.SkipRemainingSiblings())
          _RootsEnumeratorFinished = true;

      if (nodeTraversalStrategies.HasNodeTraversalStrategies(NodeTraversalStrategies.PruneSubtree))
      {
        _Path.PopScheduleStack();
        return;
      }

      if (nodeTraversalStrategies.HasNodeTraversalStrategies(NodeTraversalStrategies.SkipNode))
        return;

      if (nodeTraversalStrategies.HasNodeTraversalStrategies(NodeTraversalStrategies.PruneDescendants))
        _Path.DisposeScheduleTopEnumerator();

      _Path.AcceptScheduledNode();
    }

    // THE SEAM (schedule-stack top): the child pull, probed. Reads the parent (ScheduleTop) inline
    // instead of via a ref parameter (see the class doc). The pulled result lands through the same
    // consume helper whether the pull answered inline or through the pending continuation.
    private bool TryScheduleNextChildOfScheduleTop()
    {
      var result = _Path.ScheduleTop.ChildEnumerator.MoveNext();

      return TrySchedulePulledChildOfScheduleTop(result);
    }

    // THE SEAM (queue front): the child pull, probed.
    private bool TryScheduleNextChildOfFront()
    {
      var result = _Path.Front.ChildEnumerator.MoveNext();

      return TrySchedulePulledChildOfFront(result);
    }

    private bool TryScheduleNextRoot()
    {
      if (_RootsEnumeratorFinished)
        return false;

      var moved = _RootsEnumerator.MoveNext();

      if (!moved)
        return false;

      Publish(ref _Path.PushScheduledRoot(_RootsEnumerator.Current));
      return true;
    }

    // Land a pulled child under the schedule-stack top; false when the enumerator was exhausted.
    private bool TrySchedulePulledChildOfScheduleTop(Option<HandleAndSiblingIndex<THandle>> result)
    {
      if (!result.HasValue)
        return false;

      Publish(ref _Path.PushScheduledChild(_Path.ScheduleTop.Position.Depth, result.Value.Handle, result.Value.SiblingIndex));
      return true;
    }

    // Land a pulled child under the queue front; false when the enumerator was exhausted.
    private bool TrySchedulePulledChildOfFront(Option<HandleAndSiblingIndex<THandle>> result)
    {
      if (!result.HasValue)
        return false;

      Publish(ref _Path.PushScheduledChild(_Path.Front.Position.Depth, result.Value.Handle, result.Value.SiblingIndex));
      return true;
    }


    private void Publish(ref BreadthFirstFrame<TNode, TChildEnumerator> frame)
    {
      Mode = TreenumeratorModes.FromVisitCount(frame.VisitCount);
      Node = frame.Node;
      VisitCount = frame.VisitCount;
      Position = frame.Position;
    }

    /// <inheritdoc/>
    public void Dispose()
    {
      _Path.Dispose();
      _RootsEnumerator.Dispose();
    }
  }
}
