// <auto-generated>
//   Generated from AsyncSelectDepthFirstTreenumerable.g.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
// <auto-generated>
//   Generated from AsyncSelectTreenumerable.cs by Copse.CodeGen (composite->narrow transcription).
//   Do not edit; edit the composite-width source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Linq.Treenumerators;
using System;

namespace Copse.Linq.Treenumerables
{
  /// <summary>
  /// The canonical projection treenumerable: a source and a value selector, applied per
  /// node with the visit stream forwarded unchanged (positions never move under a
  /// projection). This is the type the <c>Select</c> operator builds, made PUBLIC
  /// (design-docs/PUBLIC_COMPOSITION_SURFACE_DESIGN.md) as the citizenship's canonical
  /// vehicle: a citizen whose own type cannot vary its output parameter absorbs a
  /// projection by returning <c>new AsyncSelectTreenumerable(sourceOrSelf,
  /// composedSelector)</c> -- and chains over the result still collapse to this ONE
  /// wrapper, because its own doors compose selectors instead of stacking.
  /// </summary>
  internal sealed partial class SelectDepthFirstTreenumerable<TSource, TResult> : ISelectWhereDepthFirstTreenumerable<TResult>
  {
    /// <summary>Wraps <paramref name="source"/> with a per-node projection.</summary>
    public SelectDepthFirstTreenumerable(
      IDepthFirstTreenumerable<TSource> source,
      Func<TSource, TResult> selector)
    {
      if (source == null)
        throw new ArgumentNullException(nameof(source));
      if (selector == null)
        throw new ArgumentNullException(nameof(selector));

      _Source = source;
      _Selector = nodeContext => selector(nodeContext.Node);
    }

    // The context-shaped recipe seat (internal: the operators' positional flavors ride it).
    internal SelectDepthFirstTreenumerable(
      IDepthFirstTreenumerable<TSource> source,
      Func<NodeContext<TSource>, TResult> selector)
    {
      _Source = source;
      _Selector = selector;
    }

    private readonly IDepthFirstTreenumerable<TSource> _Source;
    private readonly Func<NodeContext<TSource>, TResult> _Selector;

    // ---- The internal algebra, explicit (the visibility audit: the public surface is
    // the ctor and the public doors; the driver recipe stays internal) ----

    // Projections never relabel.
    bool ISelectWhereDepthFirstTreenumerable<TResult>.Relabels => false;

    // The fast path: a projection composed onto a projection is still a projection, so the
    // chain keeps the light acquisition.
    IDepthFirstTreenumerable<TOuterResult> ISelectWhereDepthFirstTreenumerable<TResult>.Compose<TOuterResult>(Func<NodeContext<TResult>, TOuterResult> selector)
    {
      return new SelectDepthFirstTreenumerable<TSource, TOuterResult>(
        _Source, SelectWhereComposition.SelectThenSelect(_Selector, selector));
    }

    // A prune-after joins: promote to the middle tier (light passthrough driver), never the
    // filter driver -- the chain nesting in the TYPE (attempt #2, kept for review).
    IDepthFirstTreenumerable<TResult> ISelectWhereDepthFirstTreenumerable<TResult>.ComposePruneAfter(Func<NodeContext<TResult>, bool> predicate)
    {
      return new SelectPruneAfterDepthFirstTreenumerable<TSource, TResult, ComposedResultSelector<TSource, TResult, TResult, SelectResultSelector<TSource, TResult>, PruneAfterResultSelector<TResult>>>(
        _Source,
        new ComposedResultSelector<TSource, TResult, TResult, SelectResultSelector<TSource, TResult>, PruneAfterResultSelector<TResult>>(
          new SelectResultSelector<TSource, TResult>(_Selector), new PruneAfterResultSelector<TResult>(predicate)));
    }

    // The Func splice: the struct splice with the closure as its one leaf.
    IDepthFirstTreenumerable<TOuterResult> ISelectWhereDepthFirstTreenumerable<TResult>.Compose<TOuterResult>(
      Func<NodeContext<TResult>, SelectWhereResult<TOuterResult>> resultSelector,
      bool relabels)
      => ComposeCore<TOuterResult, FuncResultSelector<TResult, TOuterResult>>(
        new FuncResultSelector<TResult, TOuterResult>(resultSelector), relabels);

    // The struct-composed form -- THE LIGHT TIER DONATING A STRUCT LEG (the reunification
    // gate's decisive case: the tier seal existed because this wrapper's pieces used to
    // arrive as bare Funcs and de-inlined the whole splice chain; here its projection rides
    // an inlinable struct leg, the user lambda staying a leaf call).
    IDepthFirstTreenumerable<TOuterResult> ISelectWhereDepthFirstTreenumerable<TResult>.Compose<TOuterResult, TOuterSelector>(
      TOuterSelector outerSelector,
      bool relabels)
      => ComposeCore<TOuterResult, TOuterSelector>(outerSelector, relabels);

    private IDepthFirstTreenumerable<TOuterResult> ComposeCore<TOuterResult, TOuterSelector>(
      TOuterSelector outerSelector,
      bool relabels)
      where TOuterSelector : struct, IResultSelector<TResult, TOuterResult>
    {
      return new SelectWhereDepthFirstTreenumerable<TSource, TOuterResult, ComposedResultSelector<TSource, TResult, TOuterResult, SelectResultSelector<TSource, TResult>, TOuterSelector>>(
        _Source,
        new ComposedResultSelector<TSource, TResult, TOuterResult, SelectResultSelector<TSource, TResult>, TOuterSelector>(
          new SelectResultSelector<TSource, TResult>(_Selector), outerSelector),
        relabels);
    }

    /// <inheritdoc/>
    public ITreenumerator<TResult> GetDepthFirstTreenumerator() =>
      new SelectTreenumerator<TSource, TResult>(_Source.GetDepthFirstTreenumerator, _Selector);
  }
}
