// <auto-generated>
//   Generated from AsyncSelectResultSelector.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using System;

namespace Copse.Linq.Treenumerables
{
  // A projection as a result-selector leg: never rejects, carries no strategies -- the user
  // lambda is the leaf call; the struct is the inlinable plumbing around it.
  internal readonly struct SelectResultSelector<TSource, TResult> : IResultSelector<TSource, TResult>
  {
    public SelectResultSelector(Func<NodeAndPosition<TSource>, TResult> selector)
    {
      _Selector = selector;
    }

    private readonly Func<NodeAndPosition<TSource>, TResult> _Selector;

    public SelectWhereResult<TResult> GetResult(NodeAndPosition<TSource> nodeAndPosition)
      => new SelectWhereResult<TResult>(_Selector(nodeAndPosition), NodeTraversalStrategies.TraverseAll);
  }
}
