// <auto-generated>
//   Generated from AsyncExtendWalkable.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using System;

namespace Copse.Linq.Treenumerables
{
  // The comonad's defining operation, made concrete: a relabeling of the SAME shape where
  // every node's new value is an arbitrary observation of its focus -- the observer receives
  // the source walkable and the handle, so it can see anything reachable from that vantage
  // (depth, ancestors, subtree facts) that a streaming Select never could. Adjacency and
  // handles are delegated untouched (extend never reshapes -- the comonad covers relabelings
  // only); the streaming half is the Walk adapter driving the source's adjacency under the
  // observer's labeling. Laws pinned by the walker comonad law suites: extend(extract) is the
  // identity, extract after extend recovers the observer, and extend co-associates.
  internal sealed class ExtendWalkable<TValue, THandle, TResult> : IWalkableTreenumerable<TResult, THandle>, ITreeTopology<TResult, THandle>
  {
    public ExtendWalkable(
      ITreeTopology<TValue, THandle> source,
      Func<ITreeTopology<TValue, THandle>, THandle, TResult> observer)
    {
      _Source = source;
      _Observer = observer;
      _Walk = WalkerWalk.Create(source, observer);
    }

    private readonly ITreeTopology<TValue, THandle> _Source;
    private readonly Func<ITreeTopology<TValue, THandle>, THandle, TResult> _Observer;
    private readonly ITreenumerable<TResult> _Walk;

    public ITreenumerator<TResult> GetDepthFirstTreenumerator() => _Walk.GetDepthFirstTreenumerator();

    public ITreenumerator<TResult> GetBreadthFirstTreenumerator() => _Walk.GetBreadthFirstTreenumerator();

    public TResult GetValue(THandle handle) => _Observer(_Source, handle);

    public ParentResult<THandle> TryGetParent(THandle handle) => _Source.TryGetParent(handle);

    public ChildResult<THandle> TryGetChildAt(THandle handle, int childIndex) => _Source.TryGetChildAt(handle, childIndex);

    public ChildResult<THandle> TryGetRootAt(int rootIndex) => _Source.TryGetRootAt(rootIndex);

    // The door (walker factory design, Stage A): the relabeled view is its own topology.
    public TreeWalkerResult<TResult, THandle> TryGetTreeWalker()
    {
      var rootResult = TryGetRootAt(0);

      return rootResult.HasChild
        ? new TreeWalkerResult<TResult, THandle>(new TreeWalker<TResult, THandle>(this, rootResult.Child.Node))
        : default;
    }
  }
}
