// <auto-generated>
//   Generated from AsyncSubtreeWalkable.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Treenumerables;
using Copse.Core;
using System.Collections.Generic;

namespace Copse.Linq.Treenumerables
{
  // The re-rooted view -- the region floor's first lens, and the label type of the cofree
  // duplicate (Subtrees): the source seen with one node as the sole root, upward sight severed
  // AT that node and nowhere else. Nothing is copied and nothing re-addressed -- handles are
  // the source's own, descendants answer every probe by delegation, and exactly two answers
  // are rewritten: the root's parent probe says "none", and the virtual forest-root's child
  // group is the single root. The streaming half is the Walk adapter driving THIS view's
  // adjacency, so positions come out re-rooted for free (depth 0, sibling 0 at the root --
  // the engine computes them from the walk, no arithmetic here).
  //
  // The root comparison is HANDLE equality, never value equality: positional identity on the
  // provider's own terms (the contract's clause), the identity axiom untouched. Handles from
  // outside the subtree are not reachable from this view's root; probing with one is answered
  // by blind delegation, unspecified like any foreign-handle probe.
  internal sealed class SubtreeWalkable<TValue, THandle> : IWalkableTreenumerable<TValue, THandle>, ITreeTopology<TValue, THandle>
  {
    public SubtreeWalkable(ITreeTopology<TValue, THandle> source, THandle root)
    {
      _Source = source;
      _Root = root;
      _Walk = Tree.FromTopology(this);
    }

    private readonly ITreeTopology<TValue, THandle> _Source;
    private readonly THandle _Root;
    private readonly ITreenumerable<TValue> _Walk;

    public ITreenumerator<TValue> GetDepthFirstTreenumerator() => _Walk.GetDepthFirstTreenumerator();

    public ITreenumerator<TValue> GetBreadthFirstTreenumerator() => _Walk.GetBreadthFirstTreenumerator();

    public TValue GetValue(THandle handle) => _Source.GetValue(handle);

    public ParentResult<THandle> TryGetParent(THandle handle)
      => EqualityComparer<THandle>.Default.Equals(handle, _Root)
        ? default
        : _Source.TryGetParent(handle);

    public ChildResult<THandle> TryGetChildAt(THandle handle, int childIndex) => _Source.TryGetChildAt(handle, childIndex);

    public ChildResult<THandle> TryGetRootAt(int rootIndex)
      => rootIndex == 0
        ? new ChildResult<THandle>(new NodeAndSiblingIndex<THandle>(_Root, 0))
        : default;

    // The door (walker factory design, Stage A): the severed view has exactly one root --
    // the walker stands there, never missing.
    public TreeWalkerResult<TValue, THandle> TryGetTreeWalker()
      => new TreeWalkerResult<TValue, THandle>(new TreeWalker<TValue, THandle>(this, _Root));
  }
}
