// <auto-generated>
//   Generated from PreorderRead.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
namespace Copse.Stores
{
  // What one forward-only preorder read yields: the value and the depth it sits at. A payload,
  // not an answer -- whether there WAS a read is the option that carries this, so a stream reads
  // Option<PreorderRead<TValue>> and an exhausted stream is the miss. (The struct-return shape is
  // mandatory on the async side: out params cannot cross an await.) Small and transient (returned
  // and immediately consumed, never stored per-frame), so it carries no allocation cost.
  public readonly struct PreorderRead<TValue>
  {
    public PreorderRead(TValue value, int depth)
    {
      Value = value;
      Depth = depth;
    }

    public readonly TValue Value;
    public readonly int Depth;
  }
}
