// <auto-generated>
//   Generated from AsyncSelectPruneDescendantsWhereTreenumerable.cs by Copse.CodeGen (composite->narrow transcription).
//   Do not edit; edit the composite-width source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core.Async;
using Copse.Linq.Async;
using System;

namespace Copse.Linq.Async.Treenumerables
{
  // The middle representation tier: a composed chain of projections and prune-afters. Every
  // result preserves labels and never carries SkipNode, so the chain runs on the light
  // passthrough driver -- no promotion machinery, no path state, one driver class for both
  // dimensions. Only composition produces this wrapper (plain Select and plain PruneDescendantsWhere
  // keep their own cheapest machinery), so its IN-TIER arrow is delegate-bound by nature;
  // when a rejecting operator splices over it, its chain rides as one FuncResultSelector
  // leaf under struct plumbing.
  internal sealed partial class AsyncSelectPruneDescendantsWhereBreadthFirstTreenumerable<TSource, TResult> : IAsyncSelectWhereBreadthFirstTreenumerable<TResult>
  {
    public AsyncSelectPruneDescendantsWhereBreadthFirstTreenumerable(
      IAsyncBreadthFirstTreenumerable<TSource> source,
      Func<NodeContext<TSource>, SelectWhereResult<TResult>> resultSelector)
    {
      _Source = source;
      _ResultSelector = resultSelector;
    }

    private readonly IAsyncBreadthFirstTreenumerable<TSource> _Source;
    private readonly Func<NodeContext<TSource>, SelectWhereResult<TResult>> _ResultSelector;

    // This tier never moves a label, so the position-reading doors ARE the blind doors.
    public IAsyncBreadthFirstTreenumerable<TOuterResult> ComposePositional<TOuterResult>(Func<NodeContext<TResult>, TOuterResult> selector)
      => Compose(selector);

    public IAsyncBreadthFirstTreenumerable<TOuterResult> ComposePositional<TOuterResult, TOuterSelector>(
      TOuterSelector outerSelector,
      bool relabels)
      where TOuterSelector : struct, IResultSelector<TResult, TOuterResult>
      => Compose<TOuterResult, TOuterSelector>(outerSelector, relabels);
    public IAsyncBreadthFirstTreenumerable<TOuterResult> Compose<TOuterResult>(Func<NodeContext<TResult>, TOuterResult> selector)
    {
      return new AsyncSelectPruneDescendantsWhereBreadthFirstTreenumerable<TSource, TOuterResult>(
        _Source, SelectWhereComposition.SelectPruneDescendantsWhereThenSelect(_ResultSelector, selector));
    }

    // A rejecting operator splices over this chain: the composed closure rides as one
    // FuncResultSelector leaf; the splice plumbing and the outer leg are structs.
    public IAsyncBreadthFirstTreenumerable<TOuterResult> Compose<TOuterResult, TOuterSelector>(
      TOuterSelector outerSelector,
      bool relabels)
      where TOuterSelector : struct, IResultSelector<TResult, TOuterResult>
    {
      return new AsyncSelectWhereBreadthFirstTreenumerable<TSource, TOuterResult, ComposedResultSelector<TSource, TResult, TOuterResult, FuncResultSelector<TSource, TResult>, TOuterSelector>>(
        _Source,
        new ComposedResultSelector<TSource, TResult, TOuterResult, FuncResultSelector<TSource, TResult>, TOuterSelector>(
          new FuncResultSelector<TSource, TResult>(_ResultSelector), outerSelector));
    }

    // A prune-after composes in-tier.
    public IAsyncBreadthFirstTreenumerable<TResult> ComposePruneDescendantsWhere(Func<NodeContext<TResult>, bool> predicate)
    {
      return new AsyncSelectPruneDescendantsWhereBreadthFirstTreenumerable<TSource, TResult>(
        _Source, SelectWhereComposition.SelectPruneDescendantsWhereThenPruneDescendantsWhere(_ResultSelector, predicate));
    }

    public IAsyncTreenumerator<TResult> GetAsyncBreadthFirstTreenumerator() =>
      new AsyncSelectPruneDescendantsWhereTreenumerator<TSource, TResult>(_Source.GetAsyncBreadthFirstTreenumerator, _ResultSelector);
  }
}
