// <auto-generated>
//   Generated from AsyncPruneDescendantsWhereTreenumerable.Citizenship.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using System;

namespace Copse.Linq.Treenumerables
{
  // The public doors (PUBLIC_COMPOSITION_SURFACE_DESIGN.md), in their own partial part
  // because the CompositeToNarrow fan-out is file-granular and the narrow twins must not
  // claim composite-width doors (narrow parity is deferred). Both doors are the value
  // flavors of this wrapper's in-tier arrows.
  partial class PruneDescendantsWhereTreenumerable<TNode>
  {
    /// <inheritdoc/>
    public ISelectTreenumerable<TOuterResult> ComposeSelect<TOuterResult>(Func<TNode, TOuterResult> selector)
    {
      return new SelectPruneDescendantsWhereTreenumerable<TNode, TOuterResult>(
        _Source, SelectWhereComposition.PruneDescendantsWhereThenSelect(_Predicate, nodeAndPosition => selector(nodeAndPosition.Node)));
    }

    /// <inheritdoc/>
    public IPruneDescendantsWhereTreenumerable<TNode> ComposePruneDescendantsWhere(Func<TNode, bool> predicate)
    {
      return new PruneDescendantsWhereTreenumerable<TNode>(
        _Source, SelectWhereComposition.PruneDescendantsWhereThenPruneDescendantsWhere(_Predicate, nodeAndPosition => predicate(nodeAndPosition.Node)));
    }
  }
}
