// <auto-generated>
//   Generated from IAsyncAdjacencyProbes.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>

namespace Copse.Linq.Treenumerables
{
  // The four walkable probes over ordinal handles, as an internal seam: buffer classes hold
  // this polymorphically (a memo picks its engine by pinned layout at first probe) and the
  // two adjacency engines implement it per store layout. Probe semantics are the walkable
  // contract's (docs/WALKABLE_CONTRACT_DESIGN.md): a probe on a growing store is DEMAND and
  // forces the feed exactly as far as the answer needs; a probe past a retired feed surfaces
  // the store's own lifecycle behavior (ObjectDisposedException -- the memo replay rule,
  // inherited rather than reimplemented).
  internal interface IAdjacencyProbes<TValue>
  {
    TValue GetValue(int handle);
    ParentResult<int> TryGetParent(int handle);
    ChildResult<int> TryGetChildAt(int handle, int childIndex);
    ChildResult<int> TryGetRootAt(int rootIndex);
  }
}
