// <auto-generated>
//   Generated from AsyncLevelOrderArrayTopology.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Stores;

namespace Copse.Linq.Treenumerables
{
  // The COMPLETED level-order citizen (the 2026-08-16 adjacency split): the layout's native
  // affordances answer children (a bounds probe plus an offset -- contiguous runs) and roots
  // (the leading entries) with no state at all, exactly as the growing engine already does.
  // Only the parent axis needs an index, and on a finished store the incremental
  // suspendable sweep collapses to one two-cursor merge -- child runs tile the buffer in
  // parent order, so a single pass writes the exact int[] parent map on the first parent
  // probe. Every probe after is an array read. Contrast AsyncLevelOrderAdjacencyIndex, the
  // GROWING citizen, which keeps the sweep suspendable because its store may still be fed.
  // Single-threaded by contract, like every adjacency engine.
  internal sealed class LevelOrderArrayTopology<TValue> : ITreeTopology<TValue, int>
  {
    public LevelOrderArrayTopology(LevelOrderArrayStore<TValue> store)
    {
      _Store = store;
    }

    private const int NoParent = -1;

    private readonly LevelOrderArrayStore<TValue> _Store;

    internal LevelOrderArrayStore<TValue> Store => _Store;

    // Built on the first parent probe; exact size, no per-node machinery.
    private int[] _ParentIndexes;

    public TValue GetValue(int handle)
      => _Store.GetValue(handle);

    public Option<int> TryGetParent(int handle)
    {
      if (_ParentIndexes == null)
        _ParentIndexes = BuildParentIndexes();

      var parentIndex = _ParentIndexes[handle];

      return parentIndex == NoParent
        ? default
        : new Option<int>(parentIndex);
    }

    public Option<NodeAndSiblingIndex<int>> TryGetChildAt(int handle, int childIndex)
    {
      if (childIndex < 0 || !_Store.EnsureChildAvailable(handle, childIndex))
        return default;

      // GetFirstChildIndex is meaningful once the parent has an available child, which the
      // successful probe above just established.
      return new Option<NodeAndSiblingIndex<int>>(new NodeAndSiblingIndex<int>(_Store.GetFirstChildIndex(handle) + childIndex, childIndex));
    }

    public Option<NodeAndSiblingIndex<int>> TryGetRootAt(int rootIndex)
    {
      if (rootIndex < 0 || !_Store.EnsureRootAvailable(rootIndex))
        return default;

      // Root ordinal k is buffer index k: the roots are the store's leading entries.
      return new Option<NodeAndSiblingIndex<int>>(new NodeAndSiblingIndex<int>(rootIndex, rootIndex));
    }

    // The stackless two-cursor merge, run to completion: seed the roots (the leading
    // entries), then advance the parent cursor through the buffer writing itself under each
    // of its children. Completeness means every availability probe answers immediately and
    // the cursor never suspends. The store's voids complete synchronously; the awaits
    // are contract courtesy, not suspension points.
    private int[] BuildParentIndexes()
    {
      var parentIndexes = new int[_Store.Count];
      var writtenCount = 0;

      while (_Store.EnsureRootAvailable(writtenCount))
      {
        parentIndexes[writtenCount] = NoParent;
        writtenCount++;
      }

      var parentCursor = 0;

      while (writtenCount < parentIndexes.Length)
      {
        var childOrdinal = 0;

        while (_Store.EnsureChildAvailable(parentCursor, childOrdinal))
        {
          parentIndexes[_Store.GetFirstChildIndex(parentCursor) + childOrdinal] = parentCursor;
          childOrdinal++;
          writtenCount++;
        }

        parentCursor++;
      }

      return parentIndexes;
    }
  }
}
