// <auto-generated>
//   Generated from AsyncMaterializeTreenumerable.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Stores;
using Copse.Treenumerables;
using Copse.Core;

namespace Copse.Linq.Treenumerables
{
  // The buffer Materialize returns over a LIVE MEMO source (2026-08-10, the lazy-Materialize
  // reshape): the memo's one capture COMPLETED IN BULK at the first pull, presented as the
  // non-disposable capture marker. Nothing is enumerated before that pull -- an unconsumed
  // instance holds exactly what the unconsumed memo already held -- and the feed retires inside
  // the settle, which is what distinguishes this from the memo itself (Memoize grows
  // incrementally and needs disposing; Materialize delivers the whole capture at one deferred
  // moment and nothing to dispose after it).
  //
  // The layout guarantee rides the same settle. With a requested layout the pin lands AT
  // CONSTRUCTION -- acquiring a memo treenumerator in the requested dimension creates the
  // capture and pulls no nodes -- so an intervening consumer of the shared memo cannot pin it
  // the other way; the held pin treenumerator is retired inside the settle. If the shared
  // memo's history already pinned the other layout, the settle TRANSPOSES from the completed
  // capture (source untouched, a new instance), and replays serve from the transposed store.
  //
  // Single-threaded by contract, like the memo it wraps.
  internal sealed class MaterializeTreenumerable<TValue> : ITreenumerableBuffer<TValue>
  {
    public MaterializeTreenumerable(IMemoizeTreenumerableBuffer<TValue> memo, BufferLayout? requestedLayout)
    {
      _Memo = memo;
      _RequestedLayout = requestedLayout;

      if (requestedLayout == BufferLayout.Preorder)
        _LayoutPinHold = memo.GetDepthFirstTreenumerator();
      else if (requestedLayout == BufferLayout.LevelOrder)
        _LayoutPinHold = memo.GetBreadthFirstTreenumerator();
    }

    private readonly IMemoizeTreenumerableBuffer<TValue> _Memo;
    private readonly BufferLayout? _RequestedLayout;
    private ITreenumerator<TValue> _LayoutPinHold;
    private ITreenumerableBuffer<TValue> _Settled;

    internal IMemoizeTreenumerableBuffer<TValue> Memo => _Memo;

    // With a requested layout this is the guarantee, reported from the call onward; otherwise a
    // live view of the memo's pin (null while nothing has pulled or consumed yet).
    public BufferLayout? NativeLayout
    {
      get
      {
        if (_RequestedLayout != null)
          return _RequestedLayout;

        return _Settled != null ? _Settled.NativeLayout : _Memo.NativeLayout;
      }
    }

    public ITreenumerator<TValue> GetDepthFirstTreenumerator()
      => _Settled != null
        ? _Settled.GetDepthFirstTreenumerator()
        : new MaterializeTreenumerator<TValue>(
          this,
          TreeTraversalStrategy.DepthFirst,
          _Memo.GetDepthFirstTreenumerator());

    public ITreenumerator<TValue> GetBreadthFirstTreenumerator()
      => _Settled != null
        ? _Settled.GetBreadthFirstTreenumerator()
        : new MaterializeTreenumerator<TValue>(
          this,
          TreeTraversalStrategy.BreadthFirst,
          _Memo.GetBreadthFirstTreenumerator());

    // The one deferred moment: retire the pin hold, complete the memo's capture in bulk, and --
    // only when a requested layout lost the pin race to the shared memo's own history --
    // transpose from the completed capture. Idempotent; every replay pulls through it.
    internal ITreenumerableBuffer<TValue> Settle()
    {
      if (_Settled != null)
        return _Settled;

      if (_LayoutPinHold != null)
      {
        _LayoutPinHold.Dispose();
        _LayoutPinHold = null;
      }

      _Memo.Complete();

      if (_RequestedLayout == null || _Memo.NativeLayout == _RequestedLayout)
      {
        _Settled = _Memo;
        return _Settled;
      }

      if (_RequestedLayout == BufferLayout.Preorder)
      {
        // The memo is complete (the CompleteAsync above), so its count presizes the transpose
        // capture (the counted fast path -- final arrays exact, no chunked build buffer).
        var preorderStore = PreorderCapture.CaptureFrom(_Memo, _Memo.GetBufferedCount());

        _Settled = new TreenumerableBuffer<TValue>(
          new PreorderTreenumerable<TValue, PreorderArrayStore<TValue>>(preorderStore),
          BufferLayout.Preorder,
          new PreorderArrayTopology<TValue>(preorderStore));

        return _Settled;
      }

      var levelOrderStore = LevelOrderCapture.CaptureFrom(_Memo, _Memo.GetBufferedCount());

      _Settled = new TreenumerableBuffer<TValue>(
        new LevelOrderTreenumerable<TValue, LevelOrderArrayStore<TValue>>(levelOrderStore),
        BufferLayout.LevelOrder,
        new LevelOrderArrayTopology<TValue>(levelOrderStore));

      return _Settled;
    }

    // The adjacency half rides the settle: probing IS consumption, so a probe on an unsettled
    // instance completes the memo's capture exactly as the first stream pull would, then
    // delegates to the settled buffer's own probes (the memo's, or the transposed capture's).
    // The door (walker factory design, Stage A): the settled capture manufactures the walker,
    // so the stance rides the settled topology directly.
    public TreeWalker<TValue, int> GetTreeWalker()
      => (Settle()).GetTreeWalker();

    // Probe members removed (Stage C, the cut): the contract no longer carries them.
  }
}
