// <auto-generated>
//   Generated from AsyncScanProductBuffer.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Stores;
using Copse.Treenumerables;
using Copse.Core;
using Copse.Linq.Stores;
using System;

namespace Copse.Linq.Treenumerables
{
  // The scan family's citizen buffer (SELECT_INTO_CAPTURES_DESIGN.md): a deferred capture
  // whose product is productSelector(node, accumulate) over a SHARED fold pass -- the
  // canonical pairing by default, and ComposeSelect returns a SIBLING variant over the same
  // pass with the selector composed (f after the current selector: the pair still forms per
  // node, on the stack, never stored). Closure is the signature's doing; the at-most-once
  // rule is the pass's. The inner buffer is constructed eagerly -- construction is cheap,
  // the O(n) zip is pinned to the first pull through the lazy store, and probes ride the
  // product store at birth (the InPlaceLeaffixScan wiring, hoisted).
  internal sealed class ScanProductBuffer<TSource, TAccumulate, TProduct>
    : ISelectComposableTreenumerableBuffer<TProduct>
  {
    public ScanProductBuffer(
      ScanFoldPass<TSource, TAccumulate> foldPass,
      Func<TSource, TAccumulate, TProduct> productSelector,
      bool isCanonicalPairing = false)
    {
      _FoldPass = foldPass;
      _ProductSelector = productSelector;

      var productStore = new LazyPreorderStore<TProduct>(() => Zip(foldPass, productSelector, isCanonicalPairing));

      _Inner = new TreenumerableBuffer<TProduct>(
        new PreorderTreenumerable<TProduct, LazyPreorderStore<TProduct>>(productStore),
        BufferLayout.Preorder,
        new PreorderAdjacencyIndex<TProduct, LazyPreorderStore<TProduct>>(productStore));
    }

    private readonly ScanFoldPass<TSource, TAccumulate> _FoldPass;
    private readonly Func<TSource, TAccumulate, TProduct> _ProductSelector;
    private readonly TreenumerableBuffer<TProduct> _Inner;

    public BufferLayout? NativeLayout => _Inner.NativeLayout;

    public ITreenumerator<TProduct> GetDepthFirstTreenumerator()
      => _Inner.GetDepthFirstTreenumerator();

    public ITreenumerator<TProduct> GetBreadthFirstTreenumerator()
      => _Inner.GetBreadthFirstTreenumerator();

    public TreeWalkerResult<TProduct, int> TryGetTreeWalker()
      => _Inner.TryGetTreeWalker();

    public ISelectComposableTreenumerableBuffer<TResult> ComposeSelect<TResult>(Func<TProduct, TResult> selector)
    {
      var currentProductSelector = _ProductSelector;

      return new ScanProductBuffer<TSource, TAccumulate, TResult>(
        _FoldPass,
        (node, accumulate) => selector(currentProductSelector(node, accumulate)));
    }

    // The finisher: one zip over the shared pass into this variant's own product store,
    // the skeleton array shared. The lazy store releases this closure after the build, so
    // a built variant no longer references the pass. The canonical variant asks the pass to
    // FUSE its pairs into the fold loop (the first-caller fusion); when it built first, the
    // fused array IS its product -- the cast is exact, TProduct is the pairing when the
    // flag is set -- and no zip runs at all.
    private static PreorderArrayStore<TProduct> Zip(
      ScanFoldPass<TSource, TAccumulate> foldPass,
      Func<TSource, TAccumulate, TProduct> productSelector,
      bool isCanonicalPairing)
    {
      var (artifacts, fusedPairProducts) = foldPass.Ensure(isCanonicalPairing);

      if (isCanonicalPairing && fusedPairProducts != null)
        return new PreorderArrayStore<TProduct>((TProduct[])(object)fusedPairProducts, artifacts.SubtreeSizes);

      var products = new TProduct[artifacts.Count];

      for (var nodeIndex = 0; nodeIndex < products.Length; nodeIndex++)
        products[nodeIndex] = productSelector(artifacts.ValueAt(nodeIndex), artifacts.Accumulates[nodeIndex]);

      return new PreorderArrayStore<TProduct>(products, artifacts.SubtreeSizes);
    }
  }
}
