// <auto-generated>
//   Generated from AsyncTreenumerableBuffer.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Stores;
using Copse.Core;

namespace Copse.Linq.Treenumerables
{
  // A completed, owned, in-memory capture presented as the non-disposable ITreenumerableBuffer
  // marker: a thin wrapper that delegates both dimensions to an inner in-memory treenumerable
  // (a flat store). This is what the eager capture operators (LeaffixScan, Invert) return once
  // their store is built -- the O(n) is disclosed by the buffer type, but there is no live
  // source feed, so nothing to dispose.
  //
  // The inner may build lazily on first acquisition; "completed" is about there being no live
  // feed to retire, not about eagerness. (The flat-store treenumerable is in Copse and cannot
  // implement this Copse.Linq interface directly, hence the wrapper.)
  //
  // The adjacency half (the buffer re-parent): construction sites that hold the store pass an
  // adjacency engine over it, and probes delegate. The dimension-dispatched case (layout
  // undecided until the first pull -- the inner is an opaque lazy build, no store in hand)
  // has no engine; its first PROBE settles by capturing the inner into a preorder store and
  // probing that -- one extra O(n) capture, paid once, only on the rare undecided path, and
  // only if anyone probes at all. The stream half is untouched by the settle (replays keep
  // riding the inner), and NativeLayout keeps reporting the stream side's truth.
  internal sealed class TreenumerableBuffer<TValue> : ITreenumerableBuffer<TValue>
  {
    public TreenumerableBuffer(ITreenumerable<TValue> capture, BufferLayout? nativeLayout)
      : this(capture, nativeLayout, null)
    {
    }

    public TreenumerableBuffer(
      ITreenumerable<TValue> capture,
      BufferLayout? nativeLayout,
      IAdjacencyProbes<TValue> adjacencyProbes)
    {
      _Capture = capture;
      NativeLayout = nativeLayout;
      _AdjacencyProbes = adjacencyProbes;
    }

    private readonly ITreenumerable<TValue> _Capture;
    private IAdjacencyProbes<TValue> _AdjacencyProbes;

    // Null when the layout is decided by the first pull (Invert-F's dimension dispatch) --
    // Materialize's layout guarantee then transposes conservatively rather than guessing.
    public BufferLayout? NativeLayout { get; }

    public ITreenumerator<TValue> GetDepthFirstTreenumerator() => _Capture.GetDepthFirstTreenumerator();

    public ITreenumerator<TValue> GetBreadthFirstTreenumerator() => _Capture.GetBreadthFirstTreenumerator();

    public TValue GetValue(int handle)
      => (EnsureAdjacencyProbes()).GetValue(handle);

    public ParentResult<int> TryGetParent(int handle)
      => (EnsureAdjacencyProbes()).TryGetParent(handle);

    public ChildResult<int> TryGetChildAt(int handle, int childIndex)
      => (EnsureAdjacencyProbes()).TryGetChildAt(handle, childIndex);

    public ChildResult<int> TryGetRootAt(int rootIndex)
      => (EnsureAdjacencyProbes()).TryGetRootAt(rootIndex);

    // The settle respects the declared layout: handles are ordinals in the CAPTURE'S OWN
    // encoding (the per-capture clause), so a level-order buffer's probes speak level-order
    // ordinals; the undecided case settles preorder (probing is consumption; the fresh-memo
    // pin rule's shape).
    // The bulk-fold fast path's door (the LeaffixScan2 experiment, 2026-08-14): a
    // preorder-settled buffer hands whole-tree algorithms its raw store -- Materialize's
    // `is ITreenumerableBuffer` receiver-smart idiom, one level deeper. Sync-only for
    // now: the async Ensure is awaited, so the async seam needs an async shape (no out
    // across an await) when a consumer arrives.
    internal bool TryGetPreorderStore(out PreorderArrayStore<TValue> store)
    {
      if (NativeLayout != BufferLayout.LevelOrder
        && EnsureAdjacencyProbes() is PreorderAdjacencyIndex<TValue, PreorderArrayStore<TValue>> preorderIndex)
      {
        store = preorderIndex.Store;
        return true;
      }

      store = default;
      return false;
    }

    private IAdjacencyProbes<TValue> EnsureAdjacencyProbes()
    {
      if (_AdjacencyProbes != null)
        return _AdjacencyProbes;

      if (NativeLayout == BufferLayout.LevelOrder)
      {
        var levelOrderStore = LevelOrderCapture.CaptureFrom(_Capture);

        _AdjacencyProbes = new LevelOrderAdjacencyIndex<TValue, LevelOrderArrayStore<TValue>>(levelOrderStore);

        return _AdjacencyProbes;
      }

      var preorderStore = PreorderCapture.CaptureFrom(_Capture);

      _AdjacencyProbes = new PreorderAdjacencyIndex<TValue, PreorderArrayStore<TValue>>(preorderStore);

      return _AdjacencyProbes;
    }
  }
}
