// <auto-generated>
//   Generated from ComposableTreenumerable.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Linq.Treenumerators;
using System;

namespace Copse.Linq.Treenumerables
{
  // The reified stage chain (docs/OPERATOR_FUSION_DESIGN.md, "the result monad"): one wrapper
  // holding the Kleisli-composed result of every fused stage, so value-lambda chains of any
  // length and order collapse to ONE layer over the source. Plain single-stage operators
  // instantiate with their bespoke selector STRUCT (inlined by the JIT -- zero seam cost);
  // spliced chains carry the composed closure in a FuncResultSelector (fusion inherently
  // holds user delegates). Splicing is total: every legality decision was made outer-side.
  internal sealed class ComposableTreenumerable<TSource, TResult, TResultSelector> : IComposableTreenumerable<TResult>
    where TResultSelector : struct, IResultSelector<TSource, TResult>
  {
    public ComposableTreenumerable(
      ITreenumerable<TSource> source,
      TResultSelector resultSelector,
      bool containsRelabelingStage)
    {
      _Source = source;
      _ResultSelector = resultSelector;
      ContainsRelabelingStage = containsRelabelingStage;
    }

    private readonly ITreenumerable<TSource> _Source;
    private readonly TResultSelector _ResultSelector;

    public bool ContainsRelabelingStage { get; }

    public ITreenumerator<TResult> GetBreadthFirstTreenumerator() =>
      new WhereBreadthFirstTreenumerator<TSource, TResult, TResultSelector>(
        _Source.GetBreadthFirstTreenumerator, _ResultSelector);

    public ITreenumerator<TResult> GetDepthFirstTreenumerator() =>
      new WhereDepthFirstTreenumerator<TSource, TResult, TResultSelector>(
        _Source.GetDepthFirstTreenumerator, _ResultSelector);

    // fmap over the result carrier: the composed arrow runs first; a rejected node never
    // reaches the appended selector (the stacked pipeline's Select layer never received it,
    // so it has no outer value), an accepted node's value maps and its strategies ride.
    public ITreenumerable<TOuterResult> ComposeSelect<TOuterResult>(Func<NodeContext<TResult>, TOuterResult> selector)
    {
      var resultSelector = _ResultSelector;

      return new ComposableTreenumerable<TSource, TOuterResult, FuncResultSelector<TSource, TOuterResult>>(
        _Source,
        new FuncResultSelector<TSource, TOuterResult>(nodeContext =>
        {
          var innerResult = resultSelector.GetResult(nodeContext);

          return innerResult.Strategies.HasNodeTraversalStrategies(NodeTraversalStrategies.SkipNode)
            ? new CompositionResult<TOuterResult>(default, innerResult.Strategies)
            : new CompositionResult<TOuterResult>(
                selector(new NodeContext<TResult>(innerResult.Value, nodeContext.Position)),
                innerResult.Strategies);
        }),
        ContainsRelabelingStage);
    }

    // The composition law, written once: the fold stops at the first SkipNode-carrying result
    // (that node left the logical tree, so later stages never saw it in the stacked
    // pipeline); while accepting, strategies union.
    public ITreenumerable<TResult> ComposeFilter(Func<NodeContext<TResult>, CompositionResult<TResult>> stage, bool relabels)
    {
      var resultSelector = _ResultSelector;

      return new ComposableTreenumerable<TSource, TResult, FuncResultSelector<TSource, TResult>>(
        _Source,
        new FuncResultSelector<TSource, TResult>(nodeContext =>
        {
          var innerResult = resultSelector.GetResult(nodeContext);

          if (innerResult.Strategies.HasNodeTraversalStrategies(NodeTraversalStrategies.SkipNode))
            return innerResult;

          var stageResult = stage(new NodeContext<TResult>(innerResult.Value, nodeContext.Position));

          return new CompositionResult<TResult>(stageResult.Value, stageResult.Strategies | innerResult.Strategies);
        }),
        ContainsRelabelingStage | relabels);
    }
  }
}
