// <auto-generated>
//   Generated from FusionStage.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using System;

namespace Copse.Linq.Treenumerables
{
  // The Kleisli arrow with its own metadata (docs/OPERATOR_FUSION_DESIGN.md): everything an
  // appended operator contributes to a fused chain, as one value -- its behavior (a pure
  // projection XOR a verdict function), whether it relabels surviving nodes' positions, and
  // the composition law itself (ApplyAfter). FusionVerdict's sibling: both are discriminated
  // unions with factory constructors.
  //
  // The projection/verdict split is a TYPE-level purity promise: a wrapper holding only
  // projections reads Projection directly and stays on the light Select treenumerator; a
  // verdict-shaped closure could never be unwrapped back into one.
  internal readonly struct FusionStage<TInner, TNode>
  {
    private FusionStage(
      Func<NodeContext<TInner>, TNode> projection,
      Func<NodeContext<TInner>, FusionVerdict<TNode>> verdict,
      bool relabels)
    {
      Projection = projection;
      Verdict = verdict;
      Relabels = relabels;
    }

    // Exactly one is set.
    public readonly Func<NodeContext<TInner>, TNode> Projection;
    public readonly Func<NodeContext<TInner>, FusionVerdict<TNode>> Verdict;

    // Whether THIS stage moves surviving nodes' labels (Where and PruneBefore do -- promotion,
    // sibling renumbering; projections and PruneAfter do not).
    public readonly bool Relabels;

    public bool IsProjection => Projection != null;

    public static FusionStage<TInner, TNode> OfProjection(Func<NodeContext<TInner>, TNode> projection)
      => new FusionStage<TInner, TNode>(projection, null, relabels: false);

    public static FusionStage<TInner, TNode> OfFilter(
      Func<NodeContext<TInner>, FusionVerdict<TNode>> verdict,
      bool relabels)
      => new FusionStage<TInner, TNode>(null, verdict, relabels);

    // The composition law, written once: the first rejecting stage ends evaluation (in the
    // stacked pipeline, later layers never saw that node); accepting stages' strategies union.
    // The position is the chain's SOURCE position -- legal for whichever lambda is inside,
    // because the operator already applied the join rule before building this stage.
    public FusionVerdict<TNode> ApplyAfter(FusionVerdict<TInner> innerVerdict, NodePosition position)
    {
      if (innerVerdict.Rejected)
        return FusionVerdict<TNode>.Reject(innerVerdict.Strategies);

      var nodeContext = new NodeContext<TInner>(innerVerdict.Value, position);

      return IsProjection
        ? FusionVerdict<TNode>.Accept(Projection(nodeContext), innerVerdict.Strategies)
        : Verdict(nodeContext).WithEarlierStrategies(innerVerdict.Strategies);
    }
  }
}
