// <auto-generated>
//   Generated from AsyncHideTreenumerable.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Linq.Treenumerators;

namespace Copse.Linq
{
  // The barrier itself: a plain-contract wrapper, so the result claims no composition door and
  // nothing downstream can compose into or reroute on the source. That property belongs to THIS
  // type, not to the treenumerator -- which is why HideScope.Treenumerable can forward
  // acquisition untouched and still be a complete barrier.
  internal class HideTreenumerable<TNode> : ITreenumerable<TNode>
  {
    public HideTreenumerable(ITreenumerable<TNode> innerTreenumerable, HideScope scope)
    {
      _InnerTreenumerable = innerTreenumerable;
      _Scope = scope;
    }

    private readonly ITreenumerable<TNode> _InnerTreenumerable;
    private readonly HideScope _Scope;

    public ITreenumerator<TNode> GetBreadthFirstTreenumerator()
      => _Scope == HideScope.Treenumerator
        ? new HideTreenumerator<TNode>(_InnerTreenumerable.GetBreadthFirstTreenumerator)
        : _InnerTreenumerable.GetBreadthFirstTreenumerator();

    public ITreenumerator<TNode> GetDepthFirstTreenumerator()
      => _Scope == HideScope.Treenumerator
        ? new HideTreenumerator<TNode>(_InnerTreenumerable.GetDepthFirstTreenumerator)
        : _InnerTreenumerable.GetDepthFirstTreenumerator();
  }
}
