// <auto-generated>
//   Generated from AsyncMemoizeTreenumerable.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Treenumerators;
using Copse.Core;
using Copse.Linq.Stores;
using Copse.Linq.Treenumerators;

namespace Copse.Linq.Treenumerables
{
  // The memo behind Memoize(): a re-traversable, shared, lazily-growing capture of the source's
  // current shape. ONE capture: the first acquisition (or consume) pins the layout to its
  // dimension -- preorder for depth-first-first, level-order for breadth-first-first -- and
  // every replay in either dimension rides that one capture through the flat family's store
  // treenumerators (native combinations read sequentially; cross-order ones pay the accepted
  // locality tax, and over a still-growing capture an off-pin partial drain may over-pull --
  // the documented cost of the single feed; a caller who cares pins deliberately via
  // Consume/Materialize with a declared strategy). The source is enumerated AT MOST ONCE,
  // full stop: side effects upstream of the memo fire at most once per node, whichever
  // dimensions replay.
  //
  // This SUPERSEDES the dual-buffer design (one capture per dimension, the four-case serving
  // rule, completion races, ref-counted straggler replays -- see MEMOIZE_DESIGN.md's
  // superseding note, 2026-07-15): that design bought native-layout laziness in both
  // dimensions at the price of a second source enumeration, which broke at-most-once for
  // side-effecting sources and carried a page of drop/race machinery. The single capture is
  // the same model every capture operator (Invert-F's first-dimension pin, the narrow-source
  // memos) had already converged on.
  //
  // Single-threaded by contract: the buffer is append-only, but the shared feed is a live
  // treenumerator and concurrent fills would corrupt it.
  internal sealed class MemoizeTreenumerable<TValue> : ILazyTreenumerableBuffer<TValue>, IAsyncLayoutTaggedBuffer
  {
    // The pinned layout, null while fresh (nothing has pulled or consumed yet).
    public TreeTraversalStrategy? NativeLayout
      => _DepthFirstCapture != null ? TreeTraversalStrategy.DepthFirst
        : _BreadthFirstCapture != null ? TreeTraversalStrategy.BreadthFirst
        : (TreeTraversalStrategy?)null;

    public MemoizeTreenumerable(ITreenumerable<TValue> source)
    {
      _Source = source;
    }

    private readonly ITreenumerable<TValue> _Source;

    // Exactly ONE of these two is ever created -- whichever dimension pulls (or consumes)
    // first pins the capture's layout for the memo's whole life.
    private MemoizePreorderBuffer<TValue> _DepthFirstCapture;
    private MemoizeLevelOrderBuffer<TValue> _BreadthFirstCapture;

    private bool _Disposed;

    public bool IsComplete => _DepthFirstCapture?.Complete == true || _BreadthFirstCapture?.Complete == true;

    public int GetBufferedCount()
      => _DepthFirstCapture?.BufferedCount ?? _BreadthFirstCapture?.BufferedCount ?? 0;

    public void Consume(TreeTraversalStrategy strategy)
    {
      // The strategy is a PIN REQUEST, honored only while the memo is fresh: once a capture
      // exists, the invariant outranks the argument -- a source is never enumerated twice (a
      // second pass over an impure source could capture a DIFFERENT tree), so the existing
      // capture is completed whatever layout was asked for.
      if (_DepthFirstCapture != null)
      {
        _DepthFirstCapture.Consume();
        return;
      }

      if (_BreadthFirstCapture != null)
      {
        _BreadthFirstCapture.Consume();
        return;
      }

      if (strategy == TreeTraversalStrategy.DepthFirst)
        EnsureDepthFirstCapture().Consume();
      else
        EnsureBreadthFirstCapture().Consume();
    }

    public ITreenumerator<TValue> GetDepthFirstTreenumerator()
    {
      if (_BreadthFirstCapture != null)
        return new LevelOrderStoreDepthFirstTreenumerator<TValue, MemoizeLevelOrderBuffer<TValue>.Handle>(
          new MemoizeLevelOrderBuffer<TValue>.Handle(_BreadthFirstCapture));

      return new PreorderStoreDepthFirstTreenumerator<TValue, MemoizePreorderBuffer<TValue>.Handle>(
        new MemoizePreorderBuffer<TValue>.Handle(EnsureDepthFirstCapture()));
    }

    public ITreenumerator<TValue> GetBreadthFirstTreenumerator()
    {
      if (_DepthFirstCapture != null)
        return new PreorderStoreBreadthFirstTreenumerator<TValue, MemoizePreorderBuffer<TValue>.Handle>(
          new MemoizePreorderBuffer<TValue>.Handle(_DepthFirstCapture));

      return new LevelOrderStoreBreadthFirstTreenumerator<TValue, MemoizeLevelOrderBuffer<TValue>.Handle>(
        new MemoizeLevelOrderBuffer<TValue>.Handle(EnsureBreadthFirstCapture()));
    }

    private MemoizePreorderBuffer<TValue> EnsureDepthFirstCapture()
    {
      if (_DepthFirstCapture == null)
        _DepthFirstCapture = new MemoizePreorderBuffer<TValue>(_Source.GetDepthFirstTreenumerator);

      return _DepthFirstCapture;
    }

    private MemoizeLevelOrderBuffer<TValue> EnsureBreadthFirstCapture()
    {
      if (_BreadthFirstCapture == null)
        _BreadthFirstCapture = new MemoizeLevelOrderBuffer<TValue>(_Source.GetBreadthFirstTreenumerator);

      return _BreadthFirstCapture;
    }

    // Stops all future source consumption (retires the one feed). Existing and even new replays
    // keep working over the already-captured region; any replay that needs to pull past the
    // frontier gets ObjectDisposedException (see IAsyncTreenumerableBuffer).
    public void Dispose()
    {
      if (_Disposed)
        return;

      _Disposed = true;

      if (_DepthFirstCapture != null)
        _DepthFirstCapture.Dispose();

      if (_BreadthFirstCapture != null)
        _BreadthFirstCapture.Dispose();
    }
  }
}
