// <auto-generated>
//   Generated from PositionalWhereVerdictSelector.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using System;

namespace Copse.Linq.Treenumerables
{
  // Plain positional Where's verdict: the predicate sees (node, this layer's input labels).
  internal readonly struct PositionalWhereVerdictSelector<TNode> : IVerdictSelector<TNode, TNode>
  {
    public PositionalWhereVerdictSelector(Func<TNode, NodePosition, bool> predicate)
    {
      _Predicate = predicate;
    }

    private readonly Func<TNode, NodePosition, bool> _Predicate;

    public FusionVerdict<TNode> GetVerdict(NodeContext<TNode> nodeContext)
      => _Predicate(nodeContext.Node, nodeContext.Position)
        ? FusionVerdict<TNode>.Accept(nodeContext.Node)
        : FusionVerdict<TNode>.Reject(NodeTraversalStrategies.SkipNode);
  }
}
