// <auto-generated>
//   Generated from AsyncPruneAfterTreenumerable.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Linq.Treenumerators;
using System;

namespace Copse.Linq.Treenumerables
{
  // PruneAfter's named wrapper: plain acquisition keeps the bespoke prune-after driver (no
  // promotion machinery -- it only ever sheds whole subtrees below kept nodes), and composability
  // costs one property: PruneAfter is label-preserving (survivors keep their coordinates), so
  // its map carries relabeling: false and even positional lambdas may compose across it.
  internal sealed class PruneAfterTreenumerable<TNode> : IComposableTreenumerable<TNode>
  {
    public PruneAfterTreenumerable(
      ITreenumerable<TNode> source,
      Func<NodeContext<TNode>, bool> predicate)
    {
      _Source = source;
      _Predicate = predicate;
    }

    private readonly ITreenumerable<TNode> _Source;
    private readonly Func<NodeContext<TNode>, bool> _Predicate;

    public ICompositionMap<TNode> Map
    {
      get
      {
        var predicate = _Predicate;

        return CompositionMap<TNode, TNode>.OfResult(
          _Source,
          nodeContext => new CompositionResult<TNode>(
            nodeContext.Node,
            predicate(nodeContext)
              ? NodeTraversalStrategies.SkipDescendants
              : NodeTraversalStrategies.TraverseAll),
          containsRelabelingStage: false);
      }
    }

    public ITreenumerator<TNode> GetBreadthFirstTreenumerator() =>
      new PruneAfterTreenumerator<TNode>(_Source.GetBreadthFirstTreenumerator, _Predicate);

    public ITreenumerator<TNode> GetDepthFirstTreenumerator() =>
      new PruneAfterTreenumerator<TNode>(_Source.GetDepthFirstTreenumerator, _Predicate);
  }
}
