// <auto-generated>
//   Generated from AsyncRootfixScanProductTreenumerable.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Linq.Treenumerables;
using System;

namespace Copse.Linq.Treenumerators
{
  // A composed-projection variant of a rootfix scan (the streaming projection citizenship):
  // the same bare recipe as the plain citizen, with the product selector planted inside the
  // product engines -- one selector call at emission over a transient pairing, instead of a
  // wrapper layer per pull. Itself a citizen: further Selects compose onto the selector
  // (closure by signature).
  internal sealed class RootfixScanProductTreenumerable<TNode, TAccumulate, TProduct>
    : ISelectComposableTreenumerable<TProduct>
  {
    public RootfixScanProductTreenumerable(
      Func<ITreenumerator<TNode>> innerDepthFirstFactory,
      Func<ITreenumerator<TNode>> innerBreadthFirstFactory,
      Func<NodeContext<TAccumulate>, NodeContext<TNode>, TAccumulate> accumulator,
      TAccumulate seed,
      Func<NodeAccumulation<TNode, TAccumulate>, TProduct> productSelector)
    {
      _InnerDepthFirstFactory = innerDepthFirstFactory;
      _InnerBreadthFirstFactory = innerBreadthFirstFactory;
      _Accumulator = accumulator;
      _Seed = seed;
      _ProductSelector = productSelector;
    }

    private readonly Func<ITreenumerator<TNode>> _InnerDepthFirstFactory;
    private readonly Func<ITreenumerator<TNode>> _InnerBreadthFirstFactory;
    private readonly Func<NodeContext<TAccumulate>, NodeContext<TNode>, TAccumulate> _Accumulator;
    private readonly TAccumulate _Seed;
    private readonly Func<NodeAccumulation<TNode, TAccumulate>, TProduct> _ProductSelector;

    public ITreenumerator<TProduct> GetDepthFirstTreenumerator()
      => new RootfixScanProductDepthFirstTreenumerator<TNode, TAccumulate, TProduct>(
        _InnerDepthFirstFactory, _Accumulator, _Seed, _ProductSelector);

    public ITreenumerator<TProduct> GetBreadthFirstTreenumerator()
      => new RootfixScanProductBreadthFirstTreenumerator<TNode, TAccumulate, TProduct>(
        _InnerBreadthFirstFactory, _Accumulator, _Seed, _ProductSelector);

    public ISelectComposableTreenumerable<TResult> ComposeSelect<TResult>(Func<TProduct, TResult> selector)
    {
      var currentProductSelector = _ProductSelector;

      return new RootfixScanProductTreenumerable<TNode, TAccumulate, TResult>(
        _InnerDepthFirstFactory, _InnerBreadthFirstFactory, _Accumulator, _Seed,
        pairing => selector(currentProductSelector(pairing)));
    }
  }
}
