// <auto-generated>
//   Generated from AsyncSelectTreenumerable.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Linq.Treenumerators;
using System;

namespace Copse.Linq.Treenumerables
{
  // The pure-projection wrapper. Kept distinct from FusedTreenumerable deliberately: a chain of
  // nothing but Selects acquires through the light AsyncSelectTreenumerator, not the filter
  // driver -- plain operators keep their cheapest machinery; the general driver is paid only
  // when a filter joins (FuseStage converts, FuseProjection preserves the representation).
  internal sealed class SelectTreenumerable<TSource, TResult> : IFusableTreenumerable<TResult>
  {
    public SelectTreenumerable(
      ITreenumerable<TSource> source,
      Func<NodeContext<TSource>, TResult> selector)
    {
      _Source = source;
      _Selector = selector;
    }

    private readonly ITreenumerable<TSource> _Source;
    private readonly Func<NodeContext<TSource>, TResult> _Selector;

    // Projections never relabel.
    public bool ContainsRelabelingStage => false;

    public ITreenumerator<TResult> GetBreadthFirstTreenumerator() =>
      new SelectTreenumerator<TSource, TResult>(_Source.GetBreadthFirstTreenumerator, _Selector);

    public ITreenumerator<TResult> GetDepthFirstTreenumerator() =>
      new SelectTreenumerator<TSource, TResult>(_Source.GetDepthFirstTreenumerator, _Selector);

    // The bind, with the representation choice the stage's purity makes possible: a projection
    // composes selectors and stays on the light Select treenumerator; a filter converts the
    // chain to the verdict driver.
    public ITreenumerable<TOuterResult> Fuse<TOuterResult>(FusionStage<TResult, TOuterResult> stage)
    {
      var innerSelector = _Selector;

      if (stage.IsProjection)
      {
        var projection = stage.Projection;

        return new SelectTreenumerable<TSource, TOuterResult>(
          _Source,
          nodeContext => projection(new NodeContext<TResult>(innerSelector(nodeContext), nodeContext.Position)));
      }

      var verdict = stage.Verdict;

      return FusedTreenumerable.Create<TSource, TOuterResult, FuncVerdictSelector<TSource, TOuterResult>>(
        _Source,
        new FuncVerdictSelector<TSource, TOuterResult>(nodeContext =>
          verdict(new NodeContext<TResult>(innerSelector(nodeContext), nodeContext.Position))),
        stage.Relabels);
    }
  }
}
