// <auto-generated>
//   Generated from AsyncSelectTreenumerable.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Linq.Treenumerators;
using System;

namespace Copse.Linq.Treenumerables
{
  internal sealed class SelectTreenumerable<TSource, TResult> : IFusableTreenumerable<TResult>
  {
    public SelectTreenumerable(
      ITreenumerable<TSource> source,
      Func<NodeContext<TSource>, TResult> selector)
    {
      _Source = source;
      _Selector = selector;
    }

    private readonly ITreenumerable<TSource> _Source;
    private readonly Func<NodeContext<TSource>, TResult> _Selector;

    public ITreenumerator<TResult> GetBreadthFirstTreenumerator() =>
      new SelectTreenumerator<TSource, TResult>(_Source.GetBreadthFirstTreenumerator, _Selector);

    public ITreenumerator<TResult> GetDepthFirstTreenumerator() =>
      new SelectTreenumerator<TSource, TResult>(_Source.GetDepthFirstTreenumerator, _Selector);

    // Select's emission boundary is the identity on positions, so every appended operator may
    // cross it: both Where flavors fuse into the projection-carrying Where drivers (the fused
    // SelectWhere is an INSTANTIATION of the plain Where machinery, not a new driver), and an
    // appended Select composes selectors.
    public ITreenumerable<TResult> FuseWhere(Func<TResult, bool> predicate) =>
      FuseContextWhere(nodeContext => predicate(nodeContext.Node));

    public ITreenumerable<TResult> FusePositionalWhere(Func<TResult, NodePosition, bool> predicate) =>
      FuseContextWhere(nodeContext => predicate(nodeContext.Node, nodeContext.Position));

    public ITreenumerable<TOuterResult> FuseSelect<TOuterResult>(Func<NodeContext<TResult>, TOuterResult> outerSelector)
    {
      var innerSelector = _Selector;

      return
        new SelectTreenumerable<TSource, TOuterResult>(
          _Source,
          nodeContext => outerSelector(new NodeContext<TResult>(innerSelector(nodeContext), nodeContext.Position)));
    }

    private ITreenumerable<TResult> FuseContextWhere(Func<NodeContext<TResult>, bool> contextPredicate) =>
      TreenumerableFactory.Create(
        () => new WhereBreadthFirstTreenumerator<TSource, TResult>(
          _Source.GetBreadthFirstTreenumerator, _Selector, contextPredicate, NodeTraversalStrategies.SkipNode),
        () => new WhereDepthFirstTreenumerator<TSource, TResult>(
          _Source.GetDepthFirstTreenumerator, _Selector, contextPredicate, NodeTraversalStrategies.SkipNode));
  }
}
