// <auto-generated>
//   Generated from AsyncTakeSubtreesWhereProductTreenumerable.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Linq.Treenumerators;
using Copse;
using Copse.Core;
using Copse.Linq; // the sync transform needs the mapped using to resolve the treenumerator
using System;

namespace Copse.Linq.Treenumerables
{
  // The composed-projection variant of the TakeSubtreesWhere citizen: the same dispatched
  // recipe with a product selector, itself a citizen (further Selects compose onto the
  // selector -- closure by signature). Per dimension the selector rides the leanest seam
  // available: breadth-first it lands INSIDE the chain's SelectWhere driver (the lattice
  // absorbs it); depth-first it is one light Select wrapper over the bespoke O(1) wrapper --
  // one layer however long the composed chain, because composition happened on the selector.
  internal sealed class TakeSubtreesWhereProductTreenumerable<TNode, TProduct>
    : ISelectTreenumerable<TProduct>
  {
    public TakeSubtreesWhereProductTreenumerable(
      ITreenumerable<TNode> source,
      Func<NodeContext<TNode>, bool> predicate,
      Func<TNode, TProduct> productSelector)
    {
      _Source = source;
      _Predicate = predicate;
      _ProductSelector = productSelector;
    }

    private readonly ITreenumerable<TNode> _Source;
    private readonly Func<NodeContext<TNode>, bool> _Predicate;
    private readonly Func<TNode, TProduct> _ProductSelector;

    public ITreenumerator<TProduct> GetDepthFirstTreenumerator()
      => Tree.CreateDepthFirst(
          () => new TakeSubtreesWhereTreenumerator<TNode>(_Source.GetDepthFirstTreenumerator, _Predicate))
        .Select(_ProductSelector)
        .GetDepthFirstTreenumerator();

    public ITreenumerator<TProduct> GetBreadthFirstTreenumerator()
      => TakeSubtreesWhereTreenumerable<TNode>.GetBreadthFirstChain(_Source, _Predicate)
        .Select(_ProductSelector)
        .GetBreadthFirstTreenumerator();

    public ISelectTreenumerable<TResult> ComposeSelect<TResult>(Func<TProduct, TResult> selector)
    {
      var currentProductSelector = _ProductSelector;

      return new TakeSubtreesWhereProductTreenumerable<TNode, TResult>(
        _Source, _Predicate, node => selector(currentProductSelector(node)));
    }
  }
}
