// <auto-generated>
//   Generated from AsyncTreenumerable.TakeNodesUntil.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Linq.Treenumerators;
using Copse;
using Copse.Treenumerables;
using Copse.Core;
using Copse.Linq;
using System;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>
    /// <c>TakeNodesUntil</c>: forwards nodes until one matches the predicate, then stops
    /// scheduling (pruning that node's subtree and later siblings), keeping the matched node itself
    /// iff <paramref name="keepFinalNode"/>. Deferred. Value flavor primary; the positional
    /// flavor is the arity split (the Select/Where grammar).
    /// </summary>
    public static ITreenumerable<TNode> TakeNodesUntil<TNode>(
      this ITreenumerable<TNode> source,
      Func<TNode, bool> predicate,
      bool keepFinalNode)
      => TakeNodesUntilCore(source, nodeAndPosition => predicate(nodeAndPosition.Node), keepFinalNode);

    /// <summary>The positional flavor: the node's value and its position.</summary>
    public static ITreenumerable<TNode> TakeNodesUntil<TNode>(
      this ITreenumerable<TNode> source,
      Func<TNode, NodePosition, bool> predicate,
      bool keepFinalNode)
      => TakeNodesUntilCore(source, nodeAndPosition => predicate(nodeAndPosition.Node, nodeAndPosition.Position), keepFinalNode);

    /// <summary>
    /// <c>TakeNodesUntil</c>: forwards nodes until one matches the predicate, then stops
    /// scheduling (pruning that node's subtree and later siblings), keeping the matched node itself
    /// iff <paramref name="keepFinalNode"/>. Deferred. Value flavor primary; the positional
    /// flavor is the arity split (the Select/Where grammar).
    /// </summary>
    public static IDepthFirstTreenumerable<TNode> TakeNodesUntil<TNode>(
      this IDepthFirstTreenumerable<TNode> source,
      Func<TNode, bool> predicate,
      bool keepFinalNode)
      => TakeNodesUntilCore(source, nodeAndPosition => predicate(nodeAndPosition.Node), keepFinalNode);

    /// <summary>
    /// <c>TakeNodesUntil</c>: forwards nodes until one matches the predicate, then stops
    /// scheduling (pruning that node's subtree and later siblings), keeping the matched node itself
    /// iff <paramref name="keepFinalNode"/>. Deferred. Value flavor primary; the positional
    /// flavor is the arity split (the Select/Where grammar).
    /// </summary>
    public static IDepthFirstTreenumerable<TNode> TakeNodesUntil<TNode>(
      this IDepthFirstTreenumerable<TNode> source,
      Func<TNode, NodePosition, bool> predicate,
      bool keepFinalNode)
      => TakeNodesUntilCore(source, nodeAndPosition => predicate(nodeAndPosition.Node, nodeAndPosition.Position), keepFinalNode);

    /// <summary>
    /// <c>TakeNodesUntil</c>: forwards nodes until one matches the predicate, then stops
    /// scheduling (pruning that node's subtree and later siblings), keeping the matched node itself
    /// iff <paramref name="keepFinalNode"/>. Deferred. Value flavor primary; the positional
    /// flavor is the arity split (the Select/Where grammar).
    /// </summary>
    public static IBreadthFirstTreenumerable<TNode> TakeNodesUntil<TNode>(
      this IBreadthFirstTreenumerable<TNode> source,
      Func<TNode, bool> predicate,
      bool keepFinalNode)
      => TakeNodesUntilCore(source, nodeAndPosition => predicate(nodeAndPosition.Node), keepFinalNode);

    /// <summary>
    /// <c>TakeNodesUntil</c>: forwards nodes until one matches the predicate, then stops
    /// scheduling (pruning that node's subtree and later siblings), keeping the matched node itself
    /// iff <paramref name="keepFinalNode"/>. Deferred. Value flavor primary; the positional
    /// flavor is the arity split (the Select/Where grammar).
    /// </summary>
    public static IBreadthFirstTreenumerable<TNode> TakeNodesUntil<TNode>(
      this IBreadthFirstTreenumerable<TNode> source,
      Func<TNode, NodePosition, bool> predicate,
      bool keepFinalNode)
      => TakeNodesUntilCore(source, nodeAndPosition => predicate(nodeAndPosition.Node, nodeAndPosition.Position), keepFinalNode);

    private static ITreenumerable<TNode> TakeNodesUntilCore<TNode>(
      ITreenumerable<TNode> source,
      Func<NodeAndPosition<TNode>, bool> predicate,
      bool keepFinalNode)
      => Tree.Create(
        () => new TakeNodesUntilTreenumerator<TNode>(
          source.GetBreadthFirstTreenumerator,
          predicate,
          keepFinalNode),
        () => new TakeNodesUntilTreenumerator<TNode>(
          source.GetDepthFirstTreenumerator,
          predicate,
          keepFinalNode));

    private static IDepthFirstTreenumerable<TNode> TakeNodesUntilCore<TNode>(
      IDepthFirstTreenumerable<TNode> source,
      Func<NodeAndPosition<TNode>, bool> predicate,
      bool keepFinalNode)
      => Tree.CreateDepthFirst(
        () => new TakeNodesUntilTreenumerator<TNode>(
          source.GetDepthFirstTreenumerator,
          predicate,
          keepFinalNode));

    private static IBreadthFirstTreenumerable<TNode> TakeNodesUntilCore<TNode>(
      IBreadthFirstTreenumerable<TNode> source,
      Func<NodeAndPosition<TNode>, bool> predicate,
      bool keepFinalNode)
      => Tree.CreateBreadthFirst(
        () => new TakeNodesUntilTreenumerator<TNode>(
          source.GetBreadthFirstTreenumerator,
          predicate,
          keepFinalNode));
  }
}
