// <auto-generated>
//   Generated from AsyncTreenumerable.TakeTrees.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>Keeps only the first <paramref name="count"/> root trees (stops at the root whose sibling index reaches count). Deferred.</summary>
    public static ITreenumerable<TNode> TakeTrees<TNode>(
      this ITreenumerable<TNode> source,
      int count)
      => source.TakeNodesUntil(
        (_, position) => position.Depth == 0 && position.SiblingIndex == count,
        false);

    /// <summary>Keeps only the first <paramref name="count"/> root trees (stops at the root whose sibling index reaches count). Deferred.</summary>
    public static IDepthFirstTreenumerable<TNode> TakeTrees<TNode>(
      this IDepthFirstTreenumerable<TNode> source,
      int count)
      => source.TakeNodesUntil(
        (_, position) => position.Depth == 0 && position.SiblingIndex == count,
        false);

    /// <summary>Keeps only the first <paramref name="count"/> root trees (stops at the root whose sibling index reaches count). Deferred.</summary>
    public static IBreadthFirstTreenumerable<TNode> TakeTrees<TNode>(
      this IBreadthFirstTreenumerable<TNode> source,
      int count)
      => source.TakeNodesUntil(
        (_, position) => position.Depth == 0 && position.SiblingIndex == count,
        false);
  }
}
