// <auto-generated>
//   Generated from AsyncTreenumerable.GetBreadthFirstTraversal.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Linq.Extensions;
using System;
using System.Collections.Generic;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>The full breadth-first visit stream, with a per-node strategy selector.</summary>
    public static IEnumerable<NodeVisit<TNode>> GetBreadthFirstTraversal<TNode>(
      this IBreadthFirstTreenumerable<TNode> source,
      Func<TNode, NodeTraversalStrategies> nodeTraversalStrategiesSelector)
    {
      return EnumerateTraversal(source.GetBreadthFirstTreenumerator, nodeContext => nodeTraversalStrategiesSelector(nodeContext.Node));
    }

    /// <summary>The positional flavor: the node's value and its position.</summary>
    public static IEnumerable<NodeVisit<TNode>> GetBreadthFirstTraversal<TNode>(
      this IBreadthFirstTreenumerable<TNode> source,
      Func<TNode, NodePosition, NodeTraversalStrategies> nodeTraversalStrategiesSelector)
    {
      return EnumerateTraversal(source.GetBreadthFirstTreenumerator, nodeContext => nodeTraversalStrategiesSelector(nodeContext.Node, nodeContext.Position));
    }

    /// <summary>The full breadth-first visit stream (TraverseAll).</summary>
    public static IEnumerable<NodeVisit<TNode>> GetBreadthFirstTraversal<TNode>(
      this IBreadthFirstTreenumerable<TNode> source)
    {
      return EnumerateTraversal(source.GetBreadthFirstTreenumerator);
    }
  }
}
