// <auto-generated>
//   Generated from AsyncTreenumerable.CountNodes.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using System;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>
    /// Terminal: the number of nodes in the (filtered) tree. Each node is scheduled exactly once, so
    /// this counts scheduling visits. Value flavor primary; the positional flavor is the
    /// arity split (the Select/Where grammar).
    /// Awaitable -&gt; carries the <c>Async</c> suffix.
    /// </summary>
    public static int CountNodes<TNode>(this ITreenumerable<TNode> source)
      => CountNodesCore(source, _ => true, default);

    /// <summary>
    /// Terminal: the number of nodes in the (filtered) tree. Each node is scheduled exactly once, so
    /// this counts scheduling visits. Value flavor primary; the positional flavor is the
    /// arity split (the Select/Where grammar).
    /// Awaitable -&gt; carries the <c>Async</c> suffix.
    /// </summary>
    public static int CountNodes<TNode>(
      this ITreenumerable<TNode> source,
      Func<TNode, bool> predicate,
      TreeTraversalStrategy treeTraversalStrategy = default)
      => CountNodesCore(source, nodeContext => predicate(nodeContext.Node), treeTraversalStrategy);

    /// <summary>The positional flavor: the node's value and its position.</summary>
    public static int CountNodes<TNode>(
      this ITreenumerable<TNode> source,
      Func<TNode, NodePosition, bool> predicate,
      TreeTraversalStrategy treeTraversalStrategy = default)
      => CountNodesCore(source, nodeContext => predicate(nodeContext.Node, nodeContext.Position), treeTraversalStrategy);

    /// <summary>
    /// Terminal: the number of nodes in the (filtered) tree. Each node is scheduled exactly once, so
    /// this counts scheduling visits. Value flavor primary; the positional flavor is the
    /// arity split (the Select/Where grammar).
    /// Awaitable -&gt; carries the <c>Async</c> suffix.
    /// </summary>
    public static int CountNodes<TNode>(this IDepthFirstTreenumerable<TNode> source)
      => CountNodesCore(source, _ => true);

    /// <summary>
    /// Terminal: the number of nodes in the (filtered) tree. Each node is scheduled exactly once, so
    /// this counts scheduling visits. Value flavor primary; the positional flavor is the
    /// arity split (the Select/Where grammar).
    /// Awaitable -&gt; carries the <c>Async</c> suffix.
    /// </summary>
    public static int CountNodes<TNode>(
      this IDepthFirstTreenumerable<TNode> source,
      Func<TNode, bool> predicate)
      => CountNodesCore(source, nodeContext => predicate(nodeContext.Node));

    /// <summary>
    /// Terminal: the number of nodes in the (filtered) tree. Each node is scheduled exactly once, so
    /// this counts scheduling visits. Value flavor primary; the positional flavor is the
    /// arity split (the Select/Where grammar).
    /// Awaitable -&gt; carries the <c>Async</c> suffix.
    /// </summary>
    public static int CountNodes<TNode>(
      this IDepthFirstTreenumerable<TNode> source,
      Func<TNode, NodePosition, bool> predicate)
      => CountNodesCore(source, nodeContext => predicate(nodeContext.Node, nodeContext.Position));

    /// <summary>
    /// Terminal: the number of nodes in the (filtered) tree. Each node is scheduled exactly once, so
    /// this counts scheduling visits. Value flavor primary; the positional flavor is the
    /// arity split (the Select/Where grammar).
    /// Awaitable -&gt; carries the <c>Async</c> suffix.
    /// </summary>
    public static int CountNodes<TNode>(this IBreadthFirstTreenumerable<TNode> source)
      => CountNodesCore(source, _ => true);

    /// <summary>
    /// Terminal: the number of nodes in the (filtered) tree. Each node is scheduled exactly once, so
    /// this counts scheduling visits. Value flavor primary; the positional flavor is the
    /// arity split (the Select/Where grammar).
    /// Awaitable -&gt; carries the <c>Async</c> suffix.
    /// </summary>
    public static int CountNodes<TNode>(
      this IBreadthFirstTreenumerable<TNode> source,
      Func<TNode, bool> predicate)
      => CountNodesCore(source, nodeContext => predicate(nodeContext.Node));

    /// <summary>
    /// Terminal: the number of nodes in the (filtered) tree. Each node is scheduled exactly once, so
    /// this counts scheduling visits. Value flavor primary; the positional flavor is the
    /// arity split (the Select/Where grammar).
    /// Awaitable -&gt; carries the <c>Async</c> suffix.
    /// </summary>
    public static int CountNodes<TNode>(
      this IBreadthFirstTreenumerable<TNode> source,
      Func<TNode, NodePosition, bool> predicate)
      => CountNodesCore(source, nodeContext => predicate(nodeContext.Node, nodeContext.Position));

    private static int CountNodesCore<TNode>(
      ITreenumerable<TNode> source,
      Func<NodeContext<TNode>, bool> predicate,
      TreeTraversalStrategy treeTraversalStrategy)
    {
      if (source == null)
        return 0;

      var result = 0;

      var treenumerator = source.GetTreenumerator(treeTraversalStrategy);
      using (treenumerator)
        while (treenumerator.MoveNext(NodeTraversalStrategies.SkipNode))
        {
          if (predicate(new NodeContext<TNode>(treenumerator.Node, treenumerator.Position)))
            result++;
        }

      return result;
    }

    private static int CountNodesCore<TNode>(
      IDepthFirstTreenumerable<TNode> source,
      Func<NodeContext<TNode>, bool> predicate)
    {
      if (source == null)
        return 0;

      var result = 0;

      var treenumerator = source.GetDepthFirstTreenumerator();
      using (treenumerator)
        while (treenumerator.MoveNext(NodeTraversalStrategies.SkipNode))
        {
          if (predicate(new NodeContext<TNode>(treenumerator.Node, treenumerator.Position)))
            result++;
        }

      return result;
    }

    private static int CountNodesCore<TNode>(
      IBreadthFirstTreenumerable<TNode> source,
      Func<NodeContext<TNode>, bool> predicate)
    {
      if (source == null)
        return 0;

      var result = 0;

      var treenumerator = source.GetBreadthFirstTreenumerator();
      using (treenumerator)
        while (treenumerator.MoveNext(NodeTraversalStrategies.SkipNode))
        {
          if (predicate(new NodeContext<TNode>(treenumerator.Node, treenumerator.Position)))
            result++;
        }

      return result;
    }
  }
}
