// <auto-generated>
//   Generated from AsyncTreenumerable.AllNodes.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using System;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    // All(p) == !Any(!p). (Fixed 2026-07-05: the outer negation was missing, so the operator
    // returned the complement of its name -- "at least one node fails" -- with no test coverage
    // to catch it. Regression-pinned in AllNodesTests.) Value flavor primary; positional is
    // the arity-split (the Select/Where grammar, swept family-wide 2026-08-05).
    /// <summary>The positional flavor: the node's value and its position.</summary>
    public static bool AllNodes<TNode>(
      this ITreenumerable<TNode> source,
      Func<TNode, bool> predicate,
      TreeTraversalStrategy treeTraversalStrategy = default)
      => !source.AnyNodes(node => !predicate(node), treeTraversalStrategy);

    /// <summary>The positional flavor: the node's value and its position.</summary>
    public static bool AllNodes<TNode>(
      this ITreenumerable<TNode> source,
      Func<TNode, NodePosition, bool> predicate,
      TreeTraversalStrategy treeTraversalStrategy = default)
      => !source.AnyNodes((node, position) => !predicate(node, position), treeTraversalStrategy);

    /// <summary>The positional flavor: the node's value and its position.</summary>
    public static bool AllNodes<TNode>(
      this IDepthFirstTreenumerable<TNode> source,
      Func<TNode, bool> predicate)
      => !source.AnyNodes(node => !predicate(node));

    /// <summary>The positional flavor: the node's value and its position.</summary>
    public static bool AllNodes<TNode>(
      this IDepthFirstTreenumerable<TNode> source,
      Func<TNode, NodePosition, bool> predicate)
      => !source.AnyNodes((node, position) => !predicate(node, position));

    /// <summary>The positional flavor: the node's value and its position.</summary>
    public static bool AllNodes<TNode>(
      this IBreadthFirstTreenumerable<TNode> source,
      Func<TNode, bool> predicate)
      => !source.AnyNodes(node => !predicate(node));

    /// <summary>The positional flavor: the node's value and its position.</summary>
    public static bool AllNodes<TNode>(
      this IBreadthFirstTreenumerable<TNode> source,
      Func<TNode, NodePosition, bool> predicate)
      => !source.AnyNodes((node, position) => !predicate(node, position));
  }
}
