// <auto-generated>
//   Generated from AsyncTreenumerable.AnyNodes.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Linq.Extensions;
using System;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>
    /// Terminal: whether any node satisfies the predicate. Short-circuits on the first match.
    /// Drives with SkipNode where possible so each node is seen exactly once (at scheduling);
    /// the breadth-first dimension traverses all (its schedules front-run the skips).
    /// Value flavor primary; the positional flavor is the arity-split (the Select/Where
    /// grammar, swept family-wide 2026-08-05). Awaitable -&gt; carries the <c>Async</c> suffix.
    /// </summary>
    public static bool AnyNodes<TNode>(
      this ITreenumerable<TNode> source,
      Func<TNode, bool> predicate,
      TreeTraversalStrategy treeTraversalStrategy = default)
      => AnyNodesCore(source, nodeContext => predicate(nodeContext.Node), treeTraversalStrategy);

    /// <summary>The positional flavor: the node's value and its position.</summary>
    public static bool AnyNodes<TNode>(
      this ITreenumerable<TNode> source,
      Func<TNode, NodePosition, bool> predicate,
      TreeTraversalStrategy treeTraversalStrategy = default)
      => AnyNodesCore(source, nodeContext => predicate(nodeContext.Node, nodeContext.Position), treeTraversalStrategy);

    /// <summary>
    /// Terminal: whether any node satisfies the predicate. Short-circuits on the first match.
    /// Drives with SkipNode where possible so each node is seen exactly once (at scheduling);
    /// the breadth-first dimension traverses all (its schedules front-run the skips).
    /// Value flavor primary; the positional flavor is the arity-split (the Select/Where
    /// grammar, swept family-wide 2026-08-05). Awaitable -&gt; carries the <c>Async</c> suffix.
    /// </summary>
    public static bool AnyNodes<TNode>(
      this IDepthFirstTreenumerable<TNode> source,
      Func<TNode, bool> predicate)
      => AnyNodesCore(source, nodeContext => predicate(nodeContext.Node));

    /// <summary>
    /// Terminal: whether any node satisfies the predicate. Short-circuits on the first match.
    /// Drives with SkipNode where possible so each node is seen exactly once (at scheduling);
    /// the breadth-first dimension traverses all (its schedules front-run the skips).
    /// Value flavor primary; the positional flavor is the arity-split (the Select/Where
    /// grammar, swept family-wide 2026-08-05). Awaitable -&gt; carries the <c>Async</c> suffix.
    /// </summary>
    public static bool AnyNodes<TNode>(
      this IDepthFirstTreenumerable<TNode> source,
      Func<TNode, NodePosition, bool> predicate)
      => AnyNodesCore(source, nodeContext => predicate(nodeContext.Node, nodeContext.Position));

    /// <summary>
    /// Terminal: whether any node satisfies the predicate. Short-circuits on the first match.
    /// Drives with SkipNode where possible so each node is seen exactly once (at scheduling);
    /// the breadth-first dimension traverses all (its schedules front-run the skips).
    /// Value flavor primary; the positional flavor is the arity-split (the Select/Where
    /// grammar, swept family-wide 2026-08-05). Awaitable -&gt; carries the <c>Async</c> suffix.
    /// </summary>
    public static bool AnyNodes<TNode>(
      this IBreadthFirstTreenumerable<TNode> source,
      Func<TNode, bool> predicate)
      => AnyNodesCore(source, nodeContext => predicate(nodeContext.Node));

    /// <summary>
    /// Terminal: whether any node satisfies the predicate. Short-circuits on the first match.
    /// Drives with SkipNode where possible so each node is seen exactly once (at scheduling);
    /// the breadth-first dimension traverses all (its schedules front-run the skips).
    /// Value flavor primary; the positional flavor is the arity-split (the Select/Where
    /// grammar, swept family-wide 2026-08-05). Awaitable -&gt; carries the <c>Async</c> suffix.
    /// </summary>
    public static bool AnyNodes<TNode>(
      this IBreadthFirstTreenumerable<TNode> source,
      Func<TNode, NodePosition, bool> predicate)
      => AnyNodesCore(source, nodeContext => predicate(nodeContext.Node, nodeContext.Position));

    private static bool AnyNodesCore<TNode>(
      ITreenumerable<TNode> source,
      Func<NodeContext<TNode>, bool> predicate,
      TreeTraversalStrategy treeTraversalStrategy)
    {
      var nodeTraversalStrategies =
        treeTraversalStrategy == TreeTraversalStrategy.BreadthFirst
        ? NodeTraversalStrategies.TraverseAll
        : NodeTraversalStrategies.SkipNode;

      var treenumerator = source.GetTreenumerator(treeTraversalStrategy);
      using (treenumerator)
        while (treenumerator.MoveNext(nodeTraversalStrategies))
        {
          if (treenumerator.Mode == TreenumeratorMode.SchedulingNode && predicate(treenumerator.ToNodeContext()))
            return true;
        }

      return false;
    }

    private static bool AnyNodesCore<TNode>(
      IDepthFirstTreenumerable<TNode> source,
      Func<NodeContext<TNode>, bool> predicate)
    {
      var treenumerator = source.GetDepthFirstTreenumerator();
      using (treenumerator)
        while (treenumerator.MoveNext(NodeTraversalStrategies.SkipNode))
        {
          if (treenumerator.Mode == TreenumeratorMode.SchedulingNode && predicate(treenumerator.ToNodeContext()))
            return true;
        }

      return false;
    }

    private static bool AnyNodesCore<TNode>(
      IBreadthFirstTreenumerable<TNode> source,
      Func<NodeContext<TNode>, bool> predicate)
    {
      var treenumerator = source.GetBreadthFirstTreenumerator();
      using (treenumerator)
        while (treenumerator.MoveNext(NodeTraversalStrategies.TraverseAll))
        {
          if (treenumerator.Mode == TreenumeratorMode.SchedulingNode && predicate(treenumerator.ToNodeContext()))
            return true;
        }

      return false;
    }
  }
}
