// <auto-generated>
//   Generated from AsyncTreenumerable.Materialize.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Stores;
using Copse.Treenumerables;
using Copse.Core;
using Copse.Linq.Stores;
using Copse.Linq.Treenumerables;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>
    /// The re-traversable capture of the source's shape, DEFERRED (2026-08-10; eager until
    /// then): nothing is enumerated at the call. Construction is pinned to the first pull and
    /// runs through the lazy store's grow seam -- the LeaffixScan/Invert cost shape,
    /// capture(deferred-once) -- and THE FIRST CONSUMER PINS THE LAYOUT: depth-first-first
    /// captures preorder, breadth-first-first level-order (the lazy-Materialize law:
    /// construction is uniformly lazy; the pin is a commitment made at the earliest moment it
    /// is free, which for this overload is the first pull). No longer awaitable, so the Async
    /// suffix is gone. The source is enumerated AT MOST ONCE; both dimensions replay from the
    /// one capture; an unconsumed result holds exactly what the unconsumed pipeline already
    /// held, since nothing opens before the first pull.
    ///
    /// <para>Idempotent on a capture (probe order matters: the lazy interface derives from the
    /// completed one, so it is tested first): a live memo is wrapped so its one capture
    /// COMPLETES IN BULK at the first pull -- inheriting whatever layout the memo's own history
    /// pinned, and retiring the feed at the settle, which is what distinguishes the result from
    /// the memo itself; a completed buffer is returned as-is (re-capturing would copy every
    /// node for nothing). Disposal of the result is nothing after the settle and vacuously
    /// nothing before it.</para>
    /// </summary>
    public static ITreenumerableBuffer<TNode> Materialize<TNode>(this ITreenumerable<TNode> source)
    {
      if (source is IMemoizeTreenumerableBuffer<TNode> lazyBuffer)
        return new MaterializeTreenumerable<TNode>(lazyBuffer, requestedLayout: null);

      if (source is ITreenumerableBuffer<TNode> completedBuffer)
        return completedBuffer;

      return new TreenumerableBuffer<TNode>(
        Tree.Lazy(firstDimension =>
          firstDimension == TreeTraversalStrategy.BreadthFirst
            ? DeferredLevelOrderCapture(source)
            : DeferredPreorderCapture(source)),
        nativeLayout: null); // decided by the first pull (the dimension dispatch above)
    }

    /// <summary>
    /// Materialize with a GUARANTEED capture layout, deferred: the returned buffer's native
    /// layout is <paramref name="layout"/>, whatever the input -- the argument is never
    /// ignored -- but the O(n) construction is pinned to the first pull. The parameter speaks
    /// STORAGE vocabulary (<see cref="BufferLayout"/>'s naming rule: a strategy is how you
    /// WALK, a layout is how a capture is SHAPED -- and the layout is exactly this operator's
    /// deliverable; until 2026-08-10 it took a TreeTraversalStrategy and opened by converting
    /// it, the tell that it spoke the wrong vocabulary). The PIN lands NOW, because now is when
    /// it is free: a plain tree's capture layout is simply recorded; a live memo's capture is
    /// created for the layout's native dimension at this call (acquisition is the pin, zero
    /// nodes pulled), so an intervening consumer of a shared memo cannot pin it the other way.
    /// A buffer already in the layout is returned as-is (a capture is never re-captured); a
    /// mismatched or undecided one is TRANSPOSED -- from the buffer, never from the source
    /// (buffer traversal is effect-free by contract, so at-most-once holds), at the first pull,
    /// a NEW instance. A memo whose history had already pinned the other layout completes its
    /// pinned capture first (the one source enumeration), then transposes, all inside the first
    /// pull's settle. This stays the both-layouts recipe: materialize once, then materialize
    /// THAT in the other layout. Contrast Consume(strategy), which correctly keeps TRAVERSAL
    /// vocabulary -- Consume walks; Materialize shapes, and returns the buffer, so the layout
    /// IS the deliverable.
    /// </summary>
    public static ITreenumerableBuffer<TNode> Materialize<TNode>(this ITreenumerable<TNode> source, BufferLayout layout)
    {
      if (source is IMemoizeTreenumerableBuffer<TNode> lazyBuffer)
        return new MaterializeTreenumerable<TNode>(lazyBuffer, layout);

      if (source is ITreenumerableBuffer<TNode> completedBuffer)
      {
        if (completedBuffer.NativeLayout == layout)
          return completedBuffer;

        return layout == BufferLayout.Preorder
          ? PreorderCaptureBuffer(completedBuffer)
          : LevelOrderCaptureBuffer(completedBuffer);
      }

      return layout == BufferLayout.Preorder
        ? PreorderCaptureBuffer(source)
        : LevelOrderCaptureBuffer(source);
    }

    /// <summary>
    /// The single-dimension upgrades, deferred like the composite: the capture layout is FORCED
    /// by the source's one affordable dimension (a depth-first-only source can only be consumed
    /// depth-first, so the capture is preorder) -- known at the call, reported by
    /// <c>NativeLayout</c> immediately, paid at the first pull. The same buffer probes apply: a
    /// narrow source that is secretly a capture is wrapped (memo) or returned as-is (buffer),
    /// never re-captured.
    /// </summary>
    public static ITreenumerableBuffer<TNode> Materialize<TNode>(this IDepthFirstTreenumerable<TNode> source)
    {
      if (source is IMemoizeTreenumerableBuffer<TNode> lazyBuffer)
        return new MaterializeTreenumerable<TNode>(lazyBuffer, requestedLayout: null);

      if (source is ITreenumerableBuffer<TNode> completedBuffer)
        return completedBuffer;

      return PreorderCaptureBuffer(source);
    }

    /// <summary>
    /// The re-traversable capture of the source's shape, DEFERRED (2026-08-10; eager until
    /// then): nothing is enumerated at the call. Construction is pinned to the first pull and
    /// runs through the lazy store's grow seam -- the LeaffixScan/Invert cost shape,
    /// capture(deferred-once) -- and THE FIRST CONSUMER PINS THE LAYOUT: depth-first-first
    /// captures preorder, breadth-first-first level-order (the lazy-Materialize law:
    /// construction is uniformly lazy; the pin is a commitment made at the earliest moment it
    /// is free, which for this overload is the first pull). No longer awaitable, so the Async
    /// suffix is gone. The source is enumerated AT MOST ONCE; both dimensions replay from the
    /// one capture; an unconsumed result holds exactly what the unconsumed pipeline already
    /// held, since nothing opens before the first pull.
    ///
    /// <para>Idempotent on a capture (probe order matters: the lazy interface derives from the
    /// completed one, so it is tested first): a live memo is wrapped so its one capture
    /// COMPLETES IN BULK at the first pull -- inheriting whatever layout the memo's own history
    /// pinned, and retiring the feed at the settle, which is what distinguishes the result from
    /// the memo itself; a completed buffer is returned as-is (re-capturing would copy every
    /// node for nothing). Disposal of the result is nothing after the settle and vacuously
    /// nothing before it.</para>
    /// </summary>
    public static ITreenumerableBuffer<TNode> Materialize<TNode>(this IBreadthFirstTreenumerable<TNode> source)
    {
      if (source is IMemoizeTreenumerableBuffer<TNode> lazyBuffer)
        return new MaterializeTreenumerable<TNode>(lazyBuffer, requestedLayout: null);

      if (source is ITreenumerableBuffer<TNode> completedBuffer)
        return completedBuffer;

      return LevelOrderCaptureBuffer(source);
    }

    // The deferral seam both layouts share (the LeaffixScan/Invert pattern): a lazy store whose
    // awaited build -- ONE capture walk of the source -- runs through the grow seam on the
    // first replay pull, both dimensions replaying from the completed store thereafter.
    // The declared-layout builders share ONE lazy store between the stream half and the
    // adjacency probes -- probes attach at construction, so the settle path (which would
    // re-capture the buffer's own capture from its visit stream) never runs for a
    // Materialize-built buffer. The organic overload cannot pre-attach (its layout is
    // decided by the first pull's dimension), so it keeps the settle.
    // The presize fast-path's Linq half (2026-08-16): a source that is secretly a completed
    // concrete buffer can promise its exact node count (the buffer's counted-source door), so
    // the capture allocates final arrays exactly and skips the chunked build buffer -- the
    // transpose path's ~2n transient drops to 1n. The door is a pure read; a source whose
    // count is not already known takes the uncounted path unchanged.
    private static PreorderArrayStore<TNode> CapturePreorder<TNode>(IDepthFirstTreenumerable<TNode> source)
    {
      if (source is TreenumerableBuffer<TNode> buffer)
      {
        var countResult = buffer.TryGetNodeCount();

        if (countResult.HasValue)
          return PreorderCapture.CaptureFrom(source, countResult.Value);
      }

      return PreorderCapture.CaptureFrom(source);
    }

    private static LevelOrderArrayStore<TNode> CaptureLevelOrder<TNode>(IBreadthFirstTreenumerable<TNode> source)
    {
      if (source is TreenumerableBuffer<TNode> buffer)
      {
        var countResult = buffer.TryGetNodeCount();

        if (countResult.HasValue)
          return LevelOrderCapture.CaptureFrom(source, countResult.Value);
      }

      return LevelOrderCapture.CaptureFrom(source);
    }

    private static TreenumerableBuffer<TNode> PreorderCaptureBuffer<TNode>(IDepthFirstTreenumerable<TNode> source)
    {
      var lazyStore = new LazyPreorderStore<TNode>(() => CapturePreorder(source));

      return new TreenumerableBuffer<TNode>(
        new PreorderTreenumerable<TNode, LazyPreorderStore<TNode>>(lazyStore),
        BufferLayout.Preorder,
        new PreorderAdjacencyIndex<TNode, LazyPreorderStore<TNode>>(lazyStore));
    }

    private static TreenumerableBuffer<TNode> LevelOrderCaptureBuffer<TNode>(IBreadthFirstTreenumerable<TNode> source)
    {
      var lazyStore = new LazyLevelOrderStore<TNode>(() => CaptureLevelOrder(source));

      return new TreenumerableBuffer<TNode>(
        new LevelOrderTreenumerable<TNode, LazyLevelOrderStore<TNode>>(lazyStore),
        BufferLayout.LevelOrder,
        new LevelOrderAdjacencyIndex<TNode, LazyLevelOrderStore<TNode>>(lazyStore));
    }

    private static ITreenumerable<TNode> DeferredPreorderCapture<TNode>(IDepthFirstTreenumerable<TNode> source)
      => new PreorderTreenumerable<TNode, LazyPreorderStore<TNode>>(
        new LazyPreorderStore<TNode>(() => CapturePreorder(source)));

    private static ITreenumerable<TNode> DeferredLevelOrderCapture<TNode>(IBreadthFirstTreenumerable<TNode> source)
      => new LevelOrderTreenumerable<TNode, LazyLevelOrderStore<TNode>>(
        new LazyLevelOrderStore<TNode>(() => CaptureLevelOrder(source)));
  }
}
