// <auto-generated>
//   Generated from AsyncTreenumerable.PruneBefore.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Linq.Treenumerables;
using System;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>
    /// Async <c>PruneBefore</c> over node VALUES (prune polarity: true = prune): removes each
    /// matching node AND its whole subtree. Deferred.
    /// </summary>
    public static ITreenumerable<TNode> PruneBefore<TNode>(
      this ITreenumerable<TNode> source,
      Func<TNode, bool> predicate)
    {
      if (predicate == null)
        return source;

      // A value predicate observes no coordinates, so it composes unconditionally. The selector
      // is the plain path's struct: the operator's semantics, stated once.
      if (source is ISelectWhereTreenumerable<TNode> selectWhereSource)
        return selectWhereSource.Compose<TNode, PruneBeforeResultSelector<TNode>>(
          new PruneBeforeResultSelector<TNode>(predicate), relabels: true);

      return new SelectWhereTreenumerable<TNode, TNode, PruneBeforeResultSelector<TNode>>(
        source, new PruneBeforeResultSelector<TNode>(predicate));
    }

    /// <summary>
    /// Async <c>PruneBefore</c> over (node, position) (prune polarity: true = prune). Deferred.
    /// Each positional predicate sees ITS input tree's labels.
    /// </summary>
    public static ITreenumerable<TNode> PruneBefore<TNode>(
      this ITreenumerable<TNode> source,
      Func<TNode, NodePosition, bool> predicate)
    {
      if (predicate == null)
        return source;

      // The join rule: a positional predicate composes only over a label-preserving chain.
      if (source is ISelectWhereTreenumerable<TNode> selectWhereSource)
        return selectWhereSource.ComposePositional<TNode, PositionalPruneBeforeResultSelector<TNode>>(
          new PositionalPruneBeforeResultSelector<TNode>(predicate), relabels: true);

      return new SelectWhereTreenumerable<TNode, TNode, PositionalPruneBeforeResultSelector<TNode>>(
        source, new PositionalPruneBeforeResultSelector<TNode>(predicate));
    }

    public static IDepthFirstTreenumerable<TNode> PruneBefore<TNode>(
      this IDepthFirstTreenumerable<TNode> source,
      Func<TNode, bool> predicate)
    {
      if (predicate == null)
        return source;

      // The narrow probes mirror the composite overload's. A composite-width wrapper arriving
      // through a narrow-typed receiver composes on its own representation -- the successor
      // keeps both dimensions; a narrow chain composes to a narrow successor.
      if (source is ISelectWhereTreenumerable<TNode> selectWhereSource)
        return selectWhereSource.Compose<TNode, PruneBeforeResultSelector<TNode>>(
          new PruneBeforeResultSelector<TNode>(predicate), relabels: true);

      if (source is ISelectWhereDepthFirstTreenumerable<TNode> depthFirstSelectWhereSource)
        return depthFirstSelectWhereSource.Compose<TNode, PruneBeforeResultSelector<TNode>>(
          new PruneBeforeResultSelector<TNode>(predicate), relabels: true);

      return new SelectWhereDepthFirstTreenumerable<TNode, TNode, PruneBeforeResultSelector<TNode>>(
        source, new PruneBeforeResultSelector<TNode>(predicate));
    }

    public static IDepthFirstTreenumerable<TNode> PruneBefore<TNode>(
      this IDepthFirstTreenumerable<TNode> source,
      Func<TNode, NodePosition, bool> predicate)
    {
      if (predicate == null)
        return source;

      // The join rule, as in the composite positional overload: splice only while the chain
      // is label-preserving.
      if (source is ISelectWhereTreenumerable<TNode> selectWhereSource)
        return selectWhereSource.ComposePositional<TNode, PositionalPruneBeforeResultSelector<TNode>>(
          new PositionalPruneBeforeResultSelector<TNode>(predicate), relabels: true);

      if (source is ISelectWhereDepthFirstTreenumerable<TNode> depthFirstSelectWhereSource)
        return depthFirstSelectWhereSource.ComposePositional<TNode, PositionalPruneBeforeResultSelector<TNode>>(
          new PositionalPruneBeforeResultSelector<TNode>(predicate), relabels: true);

      return new SelectWhereDepthFirstTreenumerable<TNode, TNode, PositionalPruneBeforeResultSelector<TNode>>(
        source, new PositionalPruneBeforeResultSelector<TNode>(predicate));
    }

    public static IBreadthFirstTreenumerable<TNode> PruneBefore<TNode>(
      this IBreadthFirstTreenumerable<TNode> source,
      Func<TNode, bool> predicate)
    {
      if (predicate == null)
        return source;

      if (source is ISelectWhereTreenumerable<TNode> selectWhereSource)
        return selectWhereSource.Compose<TNode, PruneBeforeResultSelector<TNode>>(
          new PruneBeforeResultSelector<TNode>(predicate), relabels: true);

      if (source is ISelectWhereBreadthFirstTreenumerable<TNode> breadthFirstSelectWhereSource)
        return breadthFirstSelectWhereSource.Compose<TNode, PruneBeforeResultSelector<TNode>>(
          new PruneBeforeResultSelector<TNode>(predicate), relabels: true);

      return new SelectWhereBreadthFirstTreenumerable<TNode, TNode, PruneBeforeResultSelector<TNode>>(
        source, new PruneBeforeResultSelector<TNode>(predicate));
    }

    public static IBreadthFirstTreenumerable<TNode> PruneBefore<TNode>(
      this IBreadthFirstTreenumerable<TNode> source,
      Func<TNode, NodePosition, bool> predicate)
    {
      if (predicate == null)
        return source;

      if (source is ISelectWhereTreenumerable<TNode> selectWhereSource)
        return selectWhereSource.ComposePositional<TNode, PositionalPruneBeforeResultSelector<TNode>>(
          new PositionalPruneBeforeResultSelector<TNode>(predicate), relabels: true);

      if (source is ISelectWhereBreadthFirstTreenumerable<TNode> breadthFirstSelectWhereSource)
        return breadthFirstSelectWhereSource.ComposePositional<TNode, PositionalPruneBeforeResultSelector<TNode>>(
          new PositionalPruneBeforeResultSelector<TNode>(predicate), relabels: true);

      return new SelectWhereBreadthFirstTreenumerable<TNode, TNode, PositionalPruneBeforeResultSelector<TNode>>(
        source, new PositionalPruneBeforeResultSelector<TNode>(predicate));
    }
  }
}
