// <auto-generated>
//   Generated from AsyncTreenumerable.GetDepthFirstTraversal.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Linq.Extensions;
using System;
using System.Collections.Generic;

namespace Copse.Linq
{
  public static partial class Treenumerable
  {
    /// <summary>
    /// The full depth-first visit stream (every scheduling/visiting visit), with a per-node
    /// strategy selector. Value flavor primary; the positional flavor is the arity split (the
    /// Select/Where grammar).
    /// </summary>
    public static IEnumerable<NodeVisit<TNode>> GetDepthFirstTraversal<TNode>(
      this IDepthFirstTreenumerable<TNode> source,
      Func<TNode, NodeTraversalStrategies> nodeTraversalStrategiesSelector)
    {
      return EnumerateTraversal(source.GetDepthFirstTreenumerator, nodeContext => nodeTraversalStrategiesSelector(nodeContext.Node));
    }

    /// <summary>The positional flavor: the node's value and its position.</summary>
    public static IEnumerable<NodeVisit<TNode>> GetDepthFirstTraversal<TNode>(
      this IDepthFirstTreenumerable<TNode> source,
      Func<TNode, NodePosition, NodeTraversalStrategies> nodeTraversalStrategiesSelector)
    {
      return EnumerateTraversal(source.GetDepthFirstTreenumerator, nodeContext => nodeTraversalStrategiesSelector(nodeContext.Node, nodeContext.Position));
    }

    /// <summary>The full depth-first visit stream (TraverseAll).</summary>
    public static IEnumerable<NodeVisit<TNode>> GetDepthFirstTraversal<TNode>(
      this IDepthFirstTreenumerable<TNode> source)
    {
      return EnumerateTraversal(source.GetDepthFirstTreenumerator);
    }
  }
}
