// <auto-generated>
//   Generated from AsyncDoorTopology.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using System;

namespace Copse.Linq.Topologies
{
  // The door's topology, deferred (Stage C): the walkable no longer exposes its topology,
  // so machinery that must build lazily over "whatever topology this walkable's door will
  // bind" holds THIS -- the door is knocked once, at the first probe, and the bound
  // topology answers everything after. The empty forest needs no special citizen: its
  // door misses, so the result-typed probes miss honestly (no roots, no parents, no
  // children) and the one probe that MUST produce a value (GetValue) throws -- on an empty
  // forest every handle is forged, so the ask is a violation, not a miss (the two-channel
  // doctrine).
  internal sealed class DoorTopology<TValue, THandle> : ITreeTopology<TValue, THandle>
  {
    public DoorTopology(IWalkableTreenumerable<TValue, THandle> source)
    {
      _Source = source;
    }

    private readonly IWalkableTreenumerable<TValue, THandle> _Source;
    private ITreeTopology<TValue, THandle> _Topology;
    private bool _Resolved;

    private ITreeTopology<TValue, THandle> Resolve()
    {
      if (_Resolved)
        return _Topology;

      var door = _Source.TryGetTreeWalker();

      // The re-plumb (2026-08-15): the bound topology is reconstituted from the walker's
      // public steps, never extracted -- the door yields a vantage, and the vantage is enough.
      _Topology = door.HasWalker ? new WalkerTopology<TValue, THandle>(door.Walker) : null;
      _Resolved = true;

      return _Topology;
    }

    public TValue GetValue(THandle handle)
    {
      var topology = Resolve();

      if (topology == null)
        throw new InvalidOperationException("The empty forest has no nodes; no handle can be valid here (the foreign-handle clause).");

      return topology.GetValue(handle);
    }

    public ParentResult<THandle> TryGetParent(THandle handle)
    {
      var topology = Resolve();

      return topology == null ? default : topology.TryGetParent(handle);
    }

    public ChildResult<THandle> TryGetChildAt(THandle handle, int childIndex)
    {
      var topology = Resolve();

      return topology == null ? default : topology.TryGetChildAt(handle, childIndex);
    }

    public ChildResult<THandle> TryGetRootAt(int rootIndex)
    {
      var topology = Resolve();

      return topology == null ? default : topology.TryGetRootAt(rootIndex);
    }
  }
}
