// <auto-generated>
//   Generated from AsyncWalkerTopology.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;

namespace Copse.Linq.Topologies
{
  // The SPI reconstituted from a vantage (2026-08-15, the seed-what-breaks re-plumb): every
  // answer is a public walker step, so this adapter -- and everything built over it -- uses
  // no access a third party lacks. It exists because the machinery's native currency is the
  // topology (the Walk adapter and the lens delegations all consume the SPI), while what a
  // walker publicly affords is steps; this is the bridge, replacing the family-IVT
  // extraction of the walker's private topology. One extra struct copy per answer (the At),
  // then the same single probe the extraction paid.
  internal sealed class WalkerTopology<TValue, THandle> : ITreeTopology<TValue, THandle>
  {
    public WalkerTopology(TreeWalker<TValue, THandle> walker)
    {
      _Walker = walker;
    }

    private readonly TreeWalker<TValue, THandle> _Walker;

    public TValue GetValue(THandle handle) => _Walker.At(handle).GetValue();

    public ParentResult<THandle> TryGetParent(THandle handle)
    {
      var step = _Walker.At(handle).MoveToParent();

      return step.HasWalker ? new ParentResult<THandle>(step.Walker.Focus) : default;
    }

    public ChildResult<THandle> TryGetChildAt(THandle handle, int childIndex)
    {
      var step = _Walker.At(handle).MoveToChild(childIndex);

      return step.HasWalker
        ? new ChildResult<THandle>(new NodeAndSiblingIndex<THandle>(step.Walker.Focus, childIndex))
        : default;
    }

    public ChildResult<THandle> TryGetRootAt(int rootIndex)
    {
      var step = _Walker.MoveToRoot(rootIndex);

      return step.HasWalker
        ? new ChildResult<THandle>(new NodeAndSiblingIndex<THandle>(step.Walker.Focus, rootIndex))
        : default;
    }
  }
}
