// <auto-generated>
//   Generated from AsyncWalkableTopology.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using System;

namespace Copse.Linq.Topologies
{
  // The walkable's topology, reconstituted lazily -- WalkerTopology's deferred sibling.
  // The pair names its sources: WalkerTopology answers from a walker already in hand; THIS
  // answers for a walkable whose door has not been knocked yet. Machinery that must build
  // lazily over "whatever topology this walkable's door will bind" holds this: the knock
  // happens once, at the first probe (Tree.Lazy semantics -- call-by-need, cached, never
  // re-knocked), and every answer after flows through the walker the knock produced. The
  // empty forest needs no special citizen: its door misses, so the result-typed probes
  // miss honestly (no roots, no parents, no children) and the one probe that MUST produce
  // a value (GetValue) throws -- on an empty forest every handle is forged, so the ask is
  // a violation, not a miss (the two-channel doctrine).
  internal sealed class WalkableTopology<TValue, THandle> : ITreeTopology<TValue, THandle>
  {
    public WalkableTopology(IWalkableTreenumerable<TValue, THandle> source)
    {
      _Source = source;
    }

    private readonly IWalkableTreenumerable<TValue, THandle> _Source;
    private ITreeTopology<TValue, THandle> _Topology;
    private bool _Resolved;

    private ITreeTopology<TValue, THandle> Resolve()
    {
      if (_Resolved)
        return _Topology;

      var door = _Source.TryGetTreeWalker();

      // The door yields a vantage; its public Topology property is the bound physics
      // (the frame-of-reference ruling, 2026-08-15).
      _Topology = door.HasWalker ? door.Walker.Topology : null;
      _Resolved = true;

      return _Topology;
    }

    public TValue GetValue(THandle handle)
    {
      var topology = Resolve();

      if (topology == null)
        throw new InvalidOperationException("The empty forest has no nodes; no handle can be valid here (the foreign-handle clause).");

      return topology.GetValue(handle);
    }

    public ParentResult<THandle> TryGetParent(THandle handle)
    {
      var topology = Resolve();

      return topology == null ? default : topology.TryGetParent(handle);
    }

    public ChildResult<THandle> TryGetChildAt(THandle handle, int childIndex)
    {
      var topology = Resolve();

      return topology == null ? default : topology.TryGetChildAt(handle, childIndex);
    }

    public ChildResult<THandle> TryGetRootAt(int rootIndex)
    {
      var topology = Resolve();

      return topology == null ? default : topology.TryGetRootAt(rootIndex);
    }
  }
}
