// <auto-generated>
//   Generated from IAsyncSelectPruneAfterBreadthFirstTreenumerable.g.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
// <auto-generated>
//   Generated from IAsyncSelectPruneAfterTreenumerable.cs by Copse.CodeGen (composite->narrow transcription).
//   Do not edit; edit the composite-width source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using System;

namespace Copse.Linq.Treenumerables
{
  // The light tier, declared only where it exists: a wrapper whose composed chain NEVER
  // carries SkipNode -- projections and prune-afters only -- composes further members of
  // that family without converting to the filter driver. Nothing in the tier moves a label
  // (the relabels-nothing row of the gradient: no promotion, no renumbering), so even
  // positional lambdas compose across it.
  //
  // Both signatures are the type-enforced tier boundary: a projection returns a bare value
  // and a prune-after returns a bool -- neither can smuggle SkipNode, so composing through
  // these doors provably stays in the tier.
  //
  // THE TIER IS SEALED (boundary ruling 2026-08-04): this interface deliberately does NOT
  // extend the general-splice surface, so a rejecting operator (Where, PruneBefore) STACKS
  // its inlined-struct driver over a light wrapper instead of converting it. Conversion was
  // measured underwater both ways -- the light wrapper is the one splice participant with no
  // struct leg to donate, so absorbing it trades a near-free passthrough layer for an
  // all-delegate FuncResultSelector chain (Where.Dft_Triangle_Mixed, +25%). The one
  // exception is the bare projection wrapper: AsyncSelectTreenumerable additionally
  // implements IAsyncSelectWhereTreenumerable (dual citizenship), because absorbing a full
  // projection layer is the composition family's measured win.
  internal interface ISelectPruneAfterBreadthFirstTreenumerable<TNode> : IBreadthFirstTreenumerable<TNode>
  {
    // Compose a projection, staying on the tier's light machinery.
    IBreadthFirstTreenumerable<TOuterResult> Compose<TOuterResult>(Func<NodeContext<TNode>, TOuterResult> selector);

    // THE SEAL EXPERIMENT (reunification phase 2, 2026-08-18): a rejecting operator's
    // struct leg splices OVER this tier's composed closure -- the closure rides as ONE
    // FuncResultSelector leaf (the delegate the chain already pays per visit today), the
    // splice plumbing and the rejecting leg are structs. This is the donation whose
    // Func-shaped form caused the 2026-08-04 Mixed regression; the Mixed rows rule on it.
    IBreadthFirstTreenumerable<TOuterResult> ComposeRejecting<TOuterResult, TOuterSelector>(
      TOuterSelector outerSelector,
      bool relabels)
      where TOuterSelector : struct, IResultSelector<TNode, TOuterResult>;

    // Compose a prune-after (keep the node, shed its subtree on a match), staying on the
    // tier's light machinery.
    IBreadthFirstTreenumerable<TNode> ComposePruneAfter(Func<NodeContext<TNode>, bool> predicate);
  }
}
