// <auto-generated>
//   Generated from AsyncPruneAfterBreadthFirstTreenumerable.g.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
// <auto-generated>
//   Generated from AsyncPruneAfterTreenumerable.cs by Copse.CodeGen (composite->narrow transcription).
//   Do not edit; edit the composite-width source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Linq.Treenumerators; // the sync transform needs the mapped using to resolve the treenumerator
using System;

namespace Copse.Linq.Treenumerables
{
  // PruneAfter's named wrapper: plain acquisition keeps the bespoke prune-after driver (no
  // promotion machinery -- it only ever sheds whole subtrees below kept nodes). PruneAfter is
  // label-preserving (survivors keep their coordinates), so even positional lambdas compose
  // across it -- but only IN-TIER: this wrapper is sealed against general splices (see the
  // interface's boundary ruling), so a rejecting operator stacks over it.
  internal sealed class PruneAfterBreadthFirstTreenumerable<TNode> : ISelectPruneAfterBreadthFirstTreenumerable<TNode>
  {
    public PruneAfterBreadthFirstTreenumerable(
      IBreadthFirstTreenumerable<TNode> source,
      Func<NodeContext<TNode>, bool> predicate)
    {
      _Source = source;
      _Predicate = predicate;
    }

    private readonly IBreadthFirstTreenumerable<TNode> _Source;
    private readonly Func<NodeContext<TNode>, bool> _Predicate;

    // PruneAfter over PruneAfter stays on the bespoke driver: the pair merges into ONE
    // wrapper by predicate union.
    public IBreadthFirstTreenumerable<TNode> ComposePruneAfter(Func<NodeContext<TNode>, bool> outerPredicate)
    {
      return new PruneAfterBreadthFirstTreenumerable<TNode>(
        _Source, SelectWhereComposition.PruneAfterThenPruneAfter(_Predicate, outerPredicate));
    }

    // A projection joins: promote to the middle tier (light passthrough driver), never the
    // filter driver.
    public IBreadthFirstTreenumerable<TOuterResult> Compose<TOuterResult>(Func<NodeContext<TNode>, TOuterResult> selector)
    {
      return new SelectPruneAfterBreadthFirstTreenumerable<TNode, TOuterResult>(
        _Source, SelectWhereComposition.PruneAfterThenSelect(_Predicate, selector));
    }

    public ITreenumerator<TNode> GetBreadthFirstTreenumerator() =>
      new PruneAfterTreenumerator<TNode>(_Source.GetBreadthFirstTreenumerator, _Predicate);
  }
}
