// <auto-generated>
//   Generated from SelectWhereDepthFirstTreenumerable.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Linq.Treenumerators;
using System;

namespace Copse.Linq.Treenumerables
{
  // SelectWhereTreenumerable's depth-first-only twin: the reified operator chain over a source
  // that affords just that dimension. Same representation, same drivers, same algebra
  // (SelectWhereComposition) -- only the successor's width differs.
  internal sealed class SelectWhereDepthFirstTreenumerable<TSource, TResult, TResultSelector> : ISelectWhereDepthFirstTreenumerable<TResult>
    where TResultSelector : struct, IResultSelector<TSource, TResult>
  {
    public SelectWhereDepthFirstTreenumerable(
      IDepthFirstTreenumerable<TSource> source,
      TResultSelector resultSelector,
      bool relabels)
    {
      _Source = source;
      _ResultSelector = resultSelector;
      Relabels = relabels;
    }

    private readonly IDepthFirstTreenumerable<TSource> _Source;
    private readonly TResultSelector _ResultSelector;

    public bool Relabels { get; }

    public ITreenumerator<TResult> GetDepthFirstTreenumerator() =>
      new WhereDepthFirstTreenumerator<TSource, TResult, TResultSelector>(
        _Source.GetDepthFirstTreenumerator, _ResultSelector);

    public IDepthFirstTreenumerable<TOuterResult> Compose<TOuterResult>(
      Func<NodeContext<TResult>, SelectWhereResult<TOuterResult>> resultSelector,
      bool relabels)
    {
      return new SelectWhereDepthFirstTreenumerable<TSource, TOuterResult, FuncResultSelector<TSource, TOuterResult>>(
        _Source,
        new FuncResultSelector<TSource, TOuterResult>(
          SelectWhereComposition.ResultSelectorThenResultSelector<TSource, TResult, TResultSelector, TOuterResult>(
            _ResultSelector, resultSelector)),
        Relabels | relabels);
    }
  }
}
