// <auto-generated>
//   Generated from AsyncSelectPruneAfterTreenumerable.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Linq.Treenumerators;
using System;

namespace Copse.Linq.Treenumerables
{
  // The middle representation tier: a composed chain of projections and prune-afters. Every
  // result preserves labels and never carries SkipNode, so the chain runs on the light
  // passthrough driver -- no promotion machinery, no path state, one driver class for both
  // dimensions. Only composition produces this wrapper (plain Select and plain PruneAfter
  // keep their own cheapest machinery), so the arrow is delegate-bound by nature and needs
  // no struct seam.
  internal sealed class SelectPruneAfterTreenumerable<TSource, TResult> : ISelectPruneAfterTreenumerable<TResult>
  {
    public SelectPruneAfterTreenumerable(
      ITreenumerable<TSource> source,
      Func<NodeContext<TSource>, SelectWhereResult<TResult>> resultSelector)
    {
      _Source = source;
      _ResultSelector = resultSelector;
    }

    private readonly ITreenumerable<TSource> _Source;
    private readonly Func<NodeContext<TSource>, SelectWhereResult<TResult>> _ResultSelector;

    // The tier invariant: nothing in the chain moves a label.
    public bool Relabels => false;

    // A projection composes in-tier.
    public ITreenumerable<TOuterResult> Compose<TOuterResult>(Func<NodeContext<TResult>, TOuterResult> selector)
    {
      return new SelectPruneAfterTreenumerable<TSource, TOuterResult>(
        _Source, SelectWhereComposition.SelectPruneAfterThenSelect(_ResultSelector, selector));
    }

    // A prune-after composes in-tier.
    public ITreenumerable<TResult> ComposePruneAfter(Func<NodeContext<TResult>, bool> predicate)
    {
      return new SelectPruneAfterTreenumerable<TSource, TResult>(
        _Source, SelectWhereComposition.SelectPruneAfterThenPruneAfter(_ResultSelector, predicate));
    }

    // A rejecting operator arrived: convert to the general representation.
    public ITreenumerable<TOuterResult> Compose<TOuterResult>(
      Func<NodeContext<TResult>, SelectWhereResult<TOuterResult>> resultSelector,
      bool relabels)
    {
      return new SelectWhereTreenumerable<TSource, TOuterResult, FuncResultSelector<TSource, TOuterResult>>(
        _Source,
        new FuncResultSelector<TSource, TOuterResult>(
          SelectWhereComposition.SelectPruneAfterThenResultSelector(_ResultSelector, resultSelector)),
        relabels);
    }

    public ITreenumerator<TResult> GetBreadthFirstTreenumerator() =>
      new SelectPruneAfterTreenumerator<TSource, TResult>(_Source.GetBreadthFirstTreenumerator, _ResultSelector);

    public ITreenumerator<TResult> GetDepthFirstTreenumerator() =>
      new SelectPruneAfterTreenumerator<TSource, TResult>(_Source.GetDepthFirstTreenumerator, _ResultSelector);
  }
}
