// <auto-generated>
//   Generated from AsyncSelectWhereTreenumerable.Citizenship.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using System;

namespace Copse.Linq.Treenumerables
{
  // The public doors (PUBLIC_COMPOSITION_SURFACE_DESIGN.md), in their own partial part
  // because the CompositeToNarrow fan-out is file-granular and the narrow twins must not
  // claim composite-width doors (narrow parity is deferred). The driver's doors are its
  // best machinery per the door-optimality law: a projection nests as a struct leg onto
  // the composed chain; a prune-after stacks the light wrapper (the in-tier-only boundary
  // ruling).
  partial class SelectWhereTreenumerable<TSource, TResult, TResultSelector>
  {
    public ISelectTreenumerable<TOuterResult> ComposeSelect<TOuterResult>(Func<TResult, TOuterResult> selector)
    {
      return new SelectWhereTreenumerable<TSource, TOuterResult, ComposedResultSelector<TSource, TResult, TOuterResult, TResultSelector, SelectResultSelector<TResult, TOuterResult>>>(
        _Source,
        new ComposedResultSelector<TSource, TResult, TOuterResult, TResultSelector, SelectResultSelector<TResult, TOuterResult>>(
          _ResultSelector, new SelectResultSelector<TResult, TOuterResult>(nodeContext => selector(nodeContext.Node))),
        Relabels);
    }

    public IPruneAfterTreenumerable<TResult> ComposePruneAfter(Func<TResult, bool> predicate)
      => new PruneAfterTreenumerable<TResult>(this, nodeContext => predicate(nodeContext.Node));
  }
}
