// <auto-generated>
//   Generated from AsyncSelectPruneAfterDepthFirstTreenumerable.g.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using Copse.Linq.Treenumerators;
using System;

namespace Copse.Linq.Treenumerables
{
  // The middle representation tier: a composed chain of projections and prune-afters. Every
  // result preserves labels and never carries SkipNode, so the chain runs on the light
  // passthrough driver -- no promotion machinery, no path state, one driver class for both
  // dimensions. Only composition produces this wrapper (plain Select and plain PruneAfter
  // keep their own cheapest machinery), so the arrow is delegate-bound by nature and needs
  // no struct seam.
  internal sealed class SelectPruneAfterDepthFirstTreenumerable<TSource, TResult> : ISelectPruneAfterDepthFirstTreenumerable<TResult>
  {
    public SelectPruneAfterDepthFirstTreenumerable(
      IDepthFirstTreenumerable<TSource> source,
      Func<NodeContext<TSource>, SelectWhereResult<TResult>> resultSelector)
    {
      _Source = source;
      _ResultSelector = resultSelector;
    }

    private readonly IDepthFirstTreenumerable<TSource> _Source;
    private readonly Func<NodeContext<TSource>, SelectWhereResult<TResult>> _ResultSelector;

    // A projection composes in-tier.
    public IDepthFirstTreenumerable<TOuterResult> Compose<TOuterResult>(Func<NodeContext<TResult>, TOuterResult> selector)
    {
      return new SelectPruneAfterDepthFirstTreenumerable<TSource, TOuterResult>(
        _Source, SelectWhereComposition.SelectPruneAfterThenSelect(_ResultSelector, selector));
    }

    // The seal experiment's donation: the chain's composed closure rides as one
    // FuncResultSelector leaf; the splice and the rejecting leg are structs.
    public IDepthFirstTreenumerable<TOuterResult> ComposeRejecting<TOuterResult, TOuterSelector>(
      TOuterSelector outerSelector,
      bool relabels)
      where TOuterSelector : struct, IResultSelector<TResult, TOuterResult>
    {
      return new SelectWhereDepthFirstTreenumerable<TSource, TOuterResult, ComposedResultSelector<TSource, TResult, TOuterResult, FuncResultSelector<TSource, TResult>, TOuterSelector>>(
        _Source,
        new ComposedResultSelector<TSource, TResult, TOuterResult, FuncResultSelector<TSource, TResult>, TOuterSelector>(
          new FuncResultSelector<TSource, TResult>(_ResultSelector), outerSelector),
        relabels);
    }

    // A prune-after composes in-tier.
    public IDepthFirstTreenumerable<TResult> ComposePruneAfter(Func<NodeContext<TResult>, bool> predicate)
    {
      return new SelectPruneAfterDepthFirstTreenumerable<TSource, TResult>(
        _Source, SelectWhereComposition.SelectPruneAfterThenPruneAfter(_ResultSelector, predicate));
    }

    public ITreenumerator<TResult> GetDepthFirstTreenumerator() =>
      new SelectPruneAfterTreenumerator<TSource, TResult>(_Source.GetDepthFirstTreenumerator, _ResultSelector);
  }
}
