// <auto-generated>
//   Generated from AsyncFuncExpansionSelector.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;
using System;

namespace Copse.Linq.Treenumerables
{
  // The user's selector as the leaf leg: value-only, position ignored.
  internal readonly struct FuncExpansionSelector<TSource, TResult> : IExpansionSelector<TSource, TResult>
  {
    public FuncExpansionSelector(Func<TSource, Expansion<TResult>> selector)
    {
      _Selector = selector;
    }

    private readonly Func<TSource, Expansion<TResult>> _Selector;

    public Expansion<TResult> GetExpansion(NodeContext<TSource> nodeContext) => _Selector(nodeContext.Node);
  }
}
