// <auto-generated>
//   Generated from IAsyncExpansionSelector.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using Copse.Core;

namespace Copse.Linq.Treenumerables
{
  // The bind's selector as a struct leg, so the driver's per-node call inlines and the
  // left door (SELECTMANY_DESIGN.md Addendum V) can nest a collapsed chain's arrow in the
  // TYPE ahead of the user's selector -- the same shape as IResultSelector for the
  // SelectWhere lattice. Context-shaped: a folded chain's positional legs read the source
  // position exactly as they did in the chain.
  internal interface IExpansionSelector<TSource, TResult>
  {
    Expansion<TResult> GetExpansion(NodeContext<TSource> nodeContext);
  }
}
