// <auto-generated>
//   Generated from AsyncMemoizeLevelOrderStore.cs by Copse.CodeGen (async->sync transcription).
//   Do not edit; edit the async source and regenerate: dotnet run --project Copse.CodeGen
// </auto-generated>
using System.Runtime.CompilerServices;

namespace Copse.Linq.Stores
{
  // Presents a memo's BFT dimension buffer as an ILevelOrderStore for the native playback
  // treenumerator (LevelOrderStoreBreadthFirstTreenumerator). A struct so the playback's store
  // calls specialize and inline -- the same unboxed pattern as the engine's TChildEnumerator.
  //
  // Taxonomy (docs/STORE_FAMILY_REVIEW.md): SPI handle over AsyncMemoizeLevelOrderBuffer (unboxing adapter, not a store of its own).
  internal readonly struct MemoizeLevelOrderStore<TValue> : ILevelOrderStore<TValue>
  {
    public MemoizeLevelOrderStore(MemoizeLevelOrderBuffer<TValue> buffer)
    {
      _Buffer = buffer;
    }

    private readonly MemoizeLevelOrderBuffer<TValue> _Buffer;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool EnsureRootAvailable(int k) => _Buffer.EnsureRootAvailable(k);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public bool EnsureChildAvailable(int parentIndex, int k) => _Buffer.EnsureChildAvailable(parentIndex, k);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public int GetFirstChildIndex(int parentIndex) => _Buffer.GetFirstChildIndex(parentIndex);

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public TValue GetValue(int index) => _Buffer.GetValue(index);
  }
}
